INSERT INTO city_local_name VALUES ('Qurghonteppa','Khatlon','TJ','Қурғонтеппа');
INSERT INTO city_local_name VALUES ('Barnaul','Altayskiy','R','Барнаул');
INSERT INTO city_local_name VALUES ('Tanta','Egypt','ET','طنطا');
INSERT INTO city_local_name VALUES ('Nha Trang','North and South Central Coast','VN','Nha Trang');
INSERT INTO city_local_name VALUES ('Sapporo','Hokkaido','J','札幌市');
INSERT INTO city_local_name VALUES ('Wenzhou','Zhejiang','CN','温州市');
INSERT INTO city_local_name VALUES ('Casablanca','Grand Casablanca','MA','الدار البيضاء');
INSERT INTO city_local_name VALUES ('Massaua','Eritrea','ER','ምጽዋዕ');
INSERT INTO city_local_name VALUES ('Hamah','Hamah','SYR','حماة');
INSERT INTO city_local_name VALUES ('Funabashi','Chiba','J','船橋市');
INSERT INTO city_local_name VALUES ('Nanchang','Jiangxi','CN','南昌市');
INSERT INTO city_local_name VALUES ('Al Iskandariyah','Egypt','ET','الاسكندري');
INSERT INTO city_local_name VALUES ('Blida','Algeria','DZ','البليدة');
INSERT INTO city_local_name VALUES ('Taganrog','Rostovskaya','R','Таганрог');
INSERT INTO city_local_name VALUES ('Al Manāmah','Bahrain','BRN','المنامة');
INSERT INTO city_local_name VALUES ('Sumgayit','Azerbaijan','AZ','Sumqayıt');
INSERT INTO city_local_name VALUES ('Bojnurd','North Khorasan','IR','بجنورد');
INSERT INTO city_local_name VALUES ('Changsha','Hunan','CN','长沙市');
INSERT INTO city_local_name VALUES ('Orumiyeh','West Azarbayejan','IR','اروميه');
INSERT INTO city_local_name VALUES ('Chalkida','Stereas Elladas','GR','Χαλκιδέων');
INSERT INTO city_local_name VALUES ('Kremenchuk','Poltavska','UA','Кременчук');
INSERT INTO city_local_name VALUES ('Cherepovets','Vologodskaya','R','Череповец');
INSERT INTO city_local_name VALUES ('Kaluga','Kaluzhskaya','R','Калуга');
INSERT INTO city_local_name VALUES ('Al Mansurah','Egypt','ET','المنصورة');
INSERT INTO city_local_name VALUES ('Astrakhan','Astrakhanskaya','R','Астрахань');
INSERT INTO city_local_name VALUES ('Chon Buri','Thailand','THA','ชลบุรี');
INSERT INTO city_local_name VALUES ('Al Mahallah al Kubra','Egypt','ET','المحلة الكبرى');
INSERT INTO city_local_name VALUES ('Cam Pha','Northern Midlands and Mountains','VN','Cam Pha');
INSERT INTO city_local_name VALUES ('Al Ismailiyah','Egypt','ET','الاسماعيلي');
INSERT INTO city_local_name VALUES ('Kaedi','Gorgol','RIM','كيهيدي');
INSERT INTO city_local_name VALUES ('Ad-Damazīn','An-Nīl al-Azraq','SUD','الدمازين');
INSERT INTO city_local_name VALUES ('Gorgan','Golestan','IR','گرگان');
INSERT INTO city_local_name VALUES ('Gwangju','South Korea','ROK','광주광역시');
INSERT INTO city_local_name VALUES ('Kerman','Kerman','IR','کرمان');
INSERT INTO city_local_name VALUES ('Brest','Brest','BY','Брест');
INSERT INTO city_local_name VALUES ('Taizz','Yemen','YE','تعز');
INSERT INTO city_local_name VALUES ('Orenburg','Orenburgskaya','R','Оренбург');
INSERT INTO city_local_name VALUES ('Ahvaz','Khuzestan','IR','اهواز');
INSERT INTO city_local_name VALUES ('Tunis','Tunisia','TN','تونس العاصمة');
INSERT INTO city_local_name VALUES ('Pingtung','Taiwan','RC','屏東市');
INSERT INTO city_local_name VALUES ('Temirtau','Karaganda','KZ','Теміртау');
INSERT INTO city_local_name VALUES ('Hims','Hims','SYR','حمص');
INSERT INTO city_local_name VALUES ('Masjed Soleyman','Khuzestan','IR','مسجدسليمان');
INSERT INTO city_local_name VALUES ('Yokohama','Kanagawa','J','横浜市');
INSERT INTO city_local_name VALUES ('Vinh','North and South Central Coast','VN','Vinh');
INSERT INTO city_local_name VALUES ('Jeju','South Korea','ROK','제주시');
INSERT INTO city_local_name VALUES ('al Hudaydah','Yemen','YE','الحديده');
INSERT INTO city_local_name VALUES ('Chernivtsi','Chernivetska','UA','Чернівці');
INSERT INTO city_local_name VALUES ('Kemerovo','Kemerovskaya','R','Кемерово');
INSERT INTO city_local_name VALUES ('Hangzhou','Zhejiang','CN','杭州市');
INSERT INTO city_local_name VALUES ('Xian','Shaanxi','CN','西安市');
INSERT INTO city_local_name VALUES ('Fukuoka','Fukuoka','J','福岡市');
INSERT INTO city_local_name VALUES ('Sofia','Bulgaria','BG','София');
INSERT INTO city_local_name VALUES ('Al-Fūlah','Gharb Kurdufān','SUD','الفولة');
INSERT INTO city_local_name VALUES ('Abadan','Khuzestan','IR','آبادان');
INSERT INTO city_local_name VALUES ('Lutsk','Volynska','UA','Луцьк');
INSERT INTO city_local_name VALUES ('As Seeb','Oman','OM','السيب');
INSERT INTO city_local_name VALUES ('Najafabad','Esfahan','IR','نجف آباد');
INSERT INTO city_local_name VALUES ('Mashhad','Khorasan-e-Razavi','IR','مشهد');
INSERT INTO city_local_name VALUES ('Wuxi','Jiangsu','CN','无锡市');
INSERT INTO city_local_name VALUES ('Volzhsky','Volgogradskaya','R','Волжский');
INSERT INTO city_local_name VALUES ('Keelung','Taiwan','RC','基隆市');
INSERT INTO city_local_name VALUES ('Sidi Bel Abbës','Algeria','DZ','سيدي بلعباس');
INSERT INTO city_local_name VALUES ('Bobruysk','Mogilev','BY','Бобруйск');
INSERT INTO city_local_name VALUES ('Ulyanovsk','Ulyanovskaya','R','Ульяновск');
INSERT INTO city_local_name VALUES ('Zarqa','Jordan','JOR','الزرقاء');
INSERT INTO city_local_name VALUES ('Cherkasy','Cherkaska','UA','Черкаси');
INSERT INTO city_local_name VALUES ('Novosibirsk','Novosibirskaya','R','Новосибирск');
INSERT INTO city_local_name VALUES ('Sevastopol','Sevastopol','UA','Севастополь');
INSERT INTO city_local_name VALUES ('Hamamatsu','Shizuoka','J','浜松市');
INSERT INTO city_local_name VALUES ('Belgorod','Belgorodskaya','R','Белгород');
INSERT INTO city_local_name VALUES ('Kurashiki','Okayama','J','倉敷市');
INSERT INTO city_local_name VALUES ('Qingdao','Shandong','CN','青岛市');
INSERT INTO city_local_name VALUES ('Dubai','United Arab Emirates','UAE','دبي');
INSERT INTO city_local_name VALUES ('Tolyatti','Samarskaya','R','Тольятти');
INSERT INTO city_local_name VALUES ('Makiïvka','Donetska','UA','Макіївка');
INSERT INTO city_local_name VALUES ('Beni Mellal','Tadla Azilal','MA','بني ملال');
INSERT INTO city_local_name VALUES ('Omdurman','Al-Kharṭūm','SUD','أمدرمان');
INSERT INTO city_local_name VALUES ('Halab','Halab','SYR','حلب‎');
INSERT INTO city_local_name VALUES ('Guiyang','Guizhou','CN','贵阳市');
INSERT INTO city_local_name VALUES ('Taldykurgan','Almaty','KZ','Талдықорған');
INSERT INTO city_local_name VALUES ('Asyut','Egypt','ET','أسيوط');
INSERT INTO city_local_name VALUES ('Seongnam','South Korea','ROK','성남시');
INSERT INTO city_local_name VALUES ('Mykolaïv','Mykolaïvska','UA','Миколаїв');
INSERT INTO city_local_name VALUES ('Yaroslavl','Yaroslavskaya','R','Ярославль');
INSERT INTO city_local_name VALUES ('Khoy','West Azarbayejan','IR','خوئ');
INSERT INTO city_local_name VALUES ('Daegu','South Korea','ROK','대구광역시');
INSERT INTO city_local_name VALUES ('Skopje','North Macedonia','MK','Град Скопје');
INSERT INTO city_local_name VALUES ('Rhodes','Notioy Aigaioy','GR','Ρόδου');
INSERT INTO city_local_name VALUES ('Chiang Mai','Thailand','THA','เชียงใหม่');
INSERT INTO city_local_name VALUES ('Banha','Egypt','ET','بنها');
INSERT INTO city_local_name VALUES ('Higashiosaka','Osaka','J','東大阪市');
INSERT INTO city_local_name VALUES ('Niš','Serbia','SRB','Ниш');
INSERT INTO city_local_name VALUES ('Hiroshima','Hiroshima','J','広島市');
INSERT INTO city_local_name VALUES ('Kaliningrad','Kaliningradskaya','R','Калининград');
INSERT INTO city_local_name VALUES ('Ansan','South Korea','ROK','안산시');
INSERT INTO city_local_name VALUES ('Chita','Zabaykalskiy','R','Чита');
INSERT INTO city_local_name VALUES ('Lamia','Stereas Elladas','GR','Λαμία');
INSERT INTO city_local_name VALUES ('Cheboksary','Chuvashia','R','Чебоксары');
INSERT INTO city_local_name VALUES ('Semei','East-Kazakhstan','KZ','Семей');
INSERT INTO city_local_name VALUES ('Chania','Kritis','GR','Χανίων');
INSERT INTO city_local_name VALUES ('Safi','Doukala Abda','MA','آسفي');
INSERT INTO city_local_name VALUES ('Ivanovo','Ivanovskaya','R','Иваново');
INSERT INTO city_local_name VALUES ('Rudniy','Kostanai','KZ','Рудный');
INSERT INTO city_local_name VALUES ('Akureyri','Iceland','IS','Akureyri');
INSERT INTO city_local_name VALUES ('Dunqulā','Ash-Shamālīyah','SUD','دنقلا');
INSERT INTO city_local_name VALUES ('Arak','Markazi','IR','اراک');
INSERT INTO city_local_name VALUES ('Uzhhorod','Zakarpatska','UA','Ужгород');
INSERT INTO city_local_name VALUES ('Okayama','Okayama','J','岡山市');
INSERT INTO city_local_name VALUES ('Kunming','Yunnan','CN','昆明市');
INSERT INTO city_local_name VALUES ('Ech Chelif','Algeria','DZ','الشلف');
INSERT INTO city_local_name VALUES ('Qui Nhon','North and South Central Coast','VN','Quy Nhơn');
INSERT INTO city_local_name VALUES ('Vung Tau','Southeast','VN','Vũng Tàu');
INSERT INTO city_local_name VALUES ('Jinan','Shandong','CN','济南市');
INSERT INTO city_local_name VALUES ('Malayer','Hamedan','IR','ملاير');
INSERT INTO city_local_name VALUES ('Nam Dinh','Red River Delta','VN','Nam Định');
INSERT INTO city_local_name VALUES ('Kirov','Kirovskaya','R','Киров');
INSERT INTO city_local_name VALUES ('Yokosuka','Kanagawa','J','横須賀市');
INSERT INTO city_local_name VALUES ('Varna','Bulgaria','BG','Варна');
INSERT INTO city_local_name VALUES ('Biskra','Algeria','DZ','بسكرة');
INSERT INTO city_local_name VALUES ('Kāduqlī','Janūb Kurdufān','SUD','كادقلي');
INSERT INTO city_local_name VALUES ('Rabak','An-Nīl al-Abyaḍ','SUD','ربك');
INSERT INTO city_local_name VALUES ('Taiyuan','Shanxi','CN','太原市');
INSERT INTO city_local_name VALUES ('Abu Dhabi','United Arab Emirates','UAE','أبوظبي');
INSERT INTO city_local_name VALUES ('Al Ain','United Arab Emirates','UAE','العين');
INSERT INTO city_local_name VALUES ('Kustanay','Kostanai','KZ','Қостанай');
INSERT INTO city_local_name VALUES ('Rostov-na-Donu','Rostovskaya','R','Ростов-на-Дону');
INSERT INTO city_local_name VALUES ('Machida','Tokyo','J','町田市');
INSERT INTO city_local_name VALUES ('Sakai','Osaka','J','堺市');
INSERT INTO city_local_name VALUES ('Perm','Permskij','R','Пермь');
INSERT INTO city_local_name VALUES ('Matsudo','Chiba','J','松戸市');
INSERT INTO city_local_name VALUES ('Osh','Kyrgyzstan','KG','Ош');
INSERT INTO city_local_name VALUES ('Ekibastuz','Pavlodar','KZ','Екібастұз');
INSERT INTO city_local_name VALUES ('Tula','Tulskaya','R','Тула');
INSERT INTO city_local_name VALUES ('Suhaj','Egypt','ET','سوهاج');
INSERT INTO city_local_name VALUES ('Dimashq','Dimashq','SYR','مدينة دمشق');
INSERT INTO city_local_name VALUES ('Rasht','Gilan','IR','رشت');
INSERT INTO city_local_name VALUES ('Niigata','Niigata','J','新潟市');
INSERT INTO city_local_name VALUES ('Vitebsk','Vitebsk','BY','Витебск');
INSERT INTO city_local_name VALUES ('Nazareth','HaZafon','IL','נצרת');
INSERT INTO city_local_name VALUES ('Bangkok','Thailand','THA','กรุงเทพมหานคร');
INSERT INTO city_local_name VALUES ('Al Ladhiqiyah','Al Ladhiqiyah','SYR','اللاذقية');
INSERT INTO city_local_name VALUES ('Temara','Rabat Sale Zemmour Zaer','MA','تمارة');
INSERT INTO city_local_name VALUES ('Wuhan','Hubei','CN','武汉市');
INSERT INTO city_local_name VALUES ('Tokyo','Tokyo','J','特別区部');
INSERT INTO city_local_name VALUES ('Xiangyang','Hubei','CN','襄阳市');
INSERT INTO city_local_name VALUES ('Khorramabad','Lorestan','IR','خرم آباد');
INSERT INTO city_local_name VALUES ('Maarrat an Numan','Idlib','SYR','معرة النعمان');
INSERT INTO city_local_name VALUES ('Kiffa','Assaba','RIM','كيفه');
INSERT INTO city_local_name VALUES ('Kitakyushu','Fukuoka','J','北九州市');
INSERT INTO city_local_name VALUES ('Shenyang','Liaoning','CN','沈阳市');
INSERT INTO city_local_name VALUES ('Kanazawa','Ishikawa','J','金沢市');
INSERT INTO city_local_name VALUES ('Magnitogorsk','Chelyabinskaya','R','Магнитогорск');
INSERT INTO city_local_name VALUES ('Vladivostok','Primorskiy','R','Владивосток');
INSERT INTO city_local_name VALUES ('Dnipro','Dnipropetrovska','UA','Дніпропетровськ');
INSERT INTO city_local_name VALUES ('Laghouat','Algeria','DZ','الأغواط');
INSERT INTO city_local_name VALUES ('Tripoli','Libya','LAR','طرابلس');
INSERT INTO city_local_name VALUES ('Gifu','Gifu','J','岐阜市');
INSERT INTO city_local_name VALUES ('Nyala','Janūb Dārfūr','SUD','نيالا');
INSERT INTO city_local_name VALUES ('Nakhon Si Thammarat','Thailand','THA','นนทบุรี');
INSERT INTO city_local_name VALUES ('Shymkent','South-Kazakhstan','KZ','Шымкент');
INSERT INTO city_local_name VALUES ('Al Jizah','Egypt','ET','الجيزة');
INSERT INTO city_local_name VALUES ('Luhansk','Luhanska','UA','Луганськ');
INSERT INTO city_local_name VALUES ('Jhongli','Taiwan','RC','中壢市');
INSERT INTO city_local_name VALUES ('Nagasaki','Nagasaki','J','長崎市');
INSERT INTO city_local_name VALUES ('Kryvyi Rih','Dnipropetrovska','UA','Кривий Ріг');
INSERT INTO city_local_name VALUES ('Tyumen','Tyumenskaya','R','Тюмень');
INSERT INTO city_local_name VALUES ('Hachioji','Tokyo','J','八王子市');
INSERT INTO city_local_name VALUES ('Salé','Rabat Sale Zemmour Zaer','MA','سلا');
INSERT INTO city_local_name VALUES ('Murmansk','Murmanskaya','R','Мурманск');
INSERT INTO city_local_name VALUES ('Melitopol','Zaporizka','UA','Мелітополь');
INSERT INTO city_local_name VALUES ('Penza','Penzenskaya','R','Пенза');
INSERT INTO city_local_name VALUES ('Nishinomiya','Hyogo','J','西宮市');
INSERT INTO city_local_name VALUES ('Toyota','Aichi','J','豊田市');
INSERT INTO city_local_name VALUES ('Bur Said','Egypt','ET','بورسعيد');
INSERT INTO city_local_name VALUES ('Khmelnytskyi','Khmelnytska','UA','Хмельницький');
INSERT INTO city_local_name VALUES ('Yongin','South Korea','ROK','용인시');
INSERT INTO city_local_name VALUES ('Ardebil','Ardebil','IR','اردبيل');
INSERT INTO city_local_name VALUES ('Nagoya','Aichi','J','名古屋市');
INSERT INTO city_local_name VALUES ('Qom','Qom','IR','قم');
INSERT INTO city_local_name VALUES ('Sabzevar','Khorasan-e-Razavi','IR','سبزوار');
INSERT INTO city_local_name VALUES ('Kaohsiung','Taiwan','RC','高雄市');
INSERT INTO city_local_name VALUES ('Dashhowuz','Dashhowuz','TM','Daşoguz');
INSERT INTO city_local_name VALUES ('Ashdod','HaDarom','IL','אשדוד');
INSERT INTO city_local_name VALUES ('Sterlitamak','Bashkortostan','R','Стерлитамак');
INSERT INTO city_local_name VALUES ('Simferopol','Krym','UA','Сімферополь');
INSERT INTO city_local_name VALUES ('Orel','Orlovskaya','R','Орел');
INSERT INTO city_local_name VALUES ('Rabat','Rabat Sale Zemmour Zaer','MA','الرباط');
INSERT INTO city_local_name VALUES ('Burgas','Bulgaria','BG','Бургас');
INSERT INTO city_local_name VALUES ('Ryazan','Ryazanskaya','R','Рязань');
INSERT INTO city_local_name VALUES ('Bandar Abbas','Hormozgan','IR','بندرعباس');
INSERT INTO city_local_name VALUES ('Ho Chi Minh City','Southeast','VN','Hồ Chí Minh');
INSERT INTO city_local_name VALUES ('Ramla','HaMerkaz','IL','רמלה');
INSERT INTO city_local_name VALUES ('Sittwe','Rakhine','MYA','စစ်တွေမြို့');
INSERT INTO city_local_name VALUES ('Rosso','Trarza','RIM','روصو');
INSERT INTO city_local_name VALUES ('Kyzylorda','Kyzylorda','KZ','Қызылорда');
INSERT INTO city_local_name VALUES ('Ganja','Azerbaijan','AZ','Gəncə');
INSERT INTO city_local_name VALUES ('Chiayi','Taiwan','RC','嘉義市');
INSERT INTO city_local_name VALUES ('As Suways','Egypt','ET','السويس');
INSERT INTO city_local_name VALUES ('Pavlodar','Pavlodar','KZ','Павлодар');
INSERT INTO city_local_name VALUES ('Hualien','Taiwan','RC','花蓮市');
INSERT INTO city_local_name VALUES ('Manbij','Halab','SYR','منبج');
INSERT INTO city_local_name VALUES ('Shibin al Kum','Egypt','ET','شبين الكوم');
INSERT INTO city_local_name VALUES ('Lefkosia','Cyprus','CY','Λευκωσία');
INSERT INTO city_local_name VALUES ('Ioannina','Ipeiroy','GR','Ιωαννιτών');
INSERT INTO city_local_name VALUES ('Muscat','Oman','OM','مسقط');
INSERT INTO city_local_name VALUES ('Gomel','Gomel','BY','Гомель');
INSERT INTO city_local_name VALUES ('Gonbad-e-Kavus','Golestan','IR','گنبدكاووس');
INSERT INTO city_local_name VALUES ('Khujand','Sughd','TJ','Хуҷанд');
INSERT INTO city_local_name VALUES ('Wulumuqi','Xinjiang','CN','乌鲁木齐市');
INSERT INTO city_local_name VALUES ('Zaozhuang','Shandong','CN','枣庄市');
INSERT INTO city_local_name VALUES ('Kawaguchi','Saitama','J','川口市');
INSERT INTO city_local_name VALUES ('Shijiazhuang','Hebei','CN','石家庄市');
INSERT INTO city_local_name VALUES ('Almaty','Almaty City','KZ','Алматы');
INSERT INTO city_local_name VALUES ('Kulyab','Khatlon','TJ','Кӯлоб');
INSERT INTO city_local_name VALUES ('Bila Tserkva','Kyïv','UA','Біла Церква');
INSERT INTO city_local_name VALUES ('Chongqing','Chongqing','CN','重庆巿');
INSERT INTO city_local_name VALUES ('Meknès','Meknes Tafilalet','MA','مكناس');
INSERT INTO city_local_name VALUES ('Dammam','Ash Sharqiyah','SA','الدمام');
INSERT INTO city_local_name VALUES ('Larnaka','Cyprus','CY','Λάρνακα');
INSERT INTO city_local_name VALUES ('Fujisawa','Kanagawa','J','藤沢市');
INSERT INTO city_local_name VALUES ('Phnom Penh','Cambodia','K','ភ្នំពេញ');
INSERT INTO city_local_name VALUES ('Huizhou','Guangdong','CN','惠州市');
INSERT INTO city_local_name VALUES ('Turkmenabat','Lebap','TM','Türkmenabat');
INSERT INTO city_local_name VALUES ('Kūstī','An-Nīl al-Abyaḍ','SUD','كوستي');
INSERT INTO city_local_name VALUES ('Kashiwa','Chiba','J','柏市');
INSERT INTO city_local_name VALUES ('Al Uqsur','Egypt','ET','الاقص');
INSERT INTO city_local_name VALUES ('Marrakech','Marrakech Tensift Al Haouz','MA','مراكش');
INSERT INTO city_local_name VALUES ('Dniprodzerzhynsk','Dnipropetrovska','UA','Дніпродзержинськ');
INSERT INTO city_local_name VALUES ('Kutaisi','Georgia','GE','ქუთაისი');
INSERT INTO city_local_name VALUES ('Aḍ-Ḍuayn','Sharq Dārfūr','SUD','الضعين');
INSERT INTO city_local_name VALUES ('Weifang','Shandong','CN','潍坊市');
INSERT INTO city_local_name VALUES ('Zhytomyr','Zhytomyrska','UA','Житомир');
INSERT INTO city_local_name VALUES ('Siem Reap','Cambodia','K','ក្រុងសៀមរាប');
INSERT INTO city_local_name VALUES ('Lanzhou','Gansu','CN','兰州市');
INSERT INTO city_local_name VALUES ('Kharkiv','Kharkivska','UA','Харків');
INSERT INTO city_local_name VALUES ('Yangon','Yangon','MYA','ရန်ကုန်');
INSERT INTO city_local_name VALUES ('Busan','South Korea','ROK','부산광역시');
INSERT INTO city_local_name VALUES ('Larissa','Thessalias','GR','Λάρισα');
INSERT INTO city_local_name VALUES ('Nanjing','Jiangsu','CN','南京市');
INSERT INTO city_local_name VALUES ('Shahr-e-Kord','Chaharmahal and Bakhtiyari','IR','شهركرد');
INSERT INTO city_local_name VALUES ('Yantai','Shandong','CN','烟台市');
INSERT INTO city_local_name VALUES ('Izhevsk','Udmurtskaya','R','Ижевск');
INSERT INTO city_local_name VALUES ('El Djelfa','Algeria','DZ','الجلفة');
INSERT INTO city_local_name VALUES ('Al Hasakah','Al Hasakah','SYR','الحسكة');
INSERT INTO city_local_name VALUES ('Shubra al Khimah','Egypt','ET','شبرا الخيمة');
INSERT INTO city_local_name VALUES ('Aktau','Mangistau','KZ','Ақтау');
INSERT INTO city_local_name VALUES ('Huaian','Jiangsu','CN','淮安市');
INSERT INTO city_local_name VALUES ('Ad-Dāmir','Nahr an-Nīl','SUD','الدامر');
INSERT INTO city_local_name VALUES ('El Aaiun','Western Sahara','WSA','العيون');
INSERT INTO city_local_name VALUES ('Jeonju','South Korea','ROK','전주시');
INSERT INTO city_local_name VALUES ('Lemesos','Cyprus','CY','Λεμεσός');
INSERT INTO city_local_name VALUES ('Bayrūt','Lebanon','RL','بيروت');
INSERT INTO city_local_name VALUES ('Neyshabur','Khorasan-e-Razavi','IR','نيشابور');
INSERT INTO city_local_name VALUES ('Tomsk','Tomskaya','R','Томск');
INSERT INTO city_local_name VALUES ('Atyrau','Atyrau','KZ','Атырау');
INSERT INTO city_local_name VALUES ('Khorramshahr','Khuzestan','IR','خرمشهر');
INSERT INTO city_local_name VALUES ('Gunsan','South Korea','ROK','군산시');
INSERT INTO city_local_name VALUES ('Ichikawa','Chiba','J','市川市');
INSERT INTO city_local_name VALUES ('Moskva','Moscow','R','Москва');
INSERT INTO city_local_name VALUES ('Incheon','South Korea','ROK','인천광역시');
INSERT INTO city_local_name VALUES ('Dayr az Zawr','Dayr az Zawr','SYR','دير الزور');
INSERT INTO city_local_name VALUES ('Mohammedia','Grand Casablanca','MA','محمدية');
INSERT INTO city_local_name VALUES ('Novokuznetsk','Kemerovskaya','R','Новокузнецк');
INSERT INTO city_local_name VALUES ('Chelyabinsk','Chelyabinskaya','R','Челябинск');
INSERT INTO city_local_name VALUES ('Kyoto','Kyoto','J','京都市');
INSERT INTO city_local_name VALUES ('Miyazaki','Miyazaki','J','宮崎市');
INSERT INTO city_local_name VALUES ('Grozny','Chechenskaya','R','Грозный');
INSERT INTO city_local_name VALUES ('Taraz','Zhambyl','KZ','Тараз');
INSERT INTO city_local_name VALUES ('Tlemcen','Algeria','DZ','تلمسان');
INSERT INTO city_local_name VALUES ('Sari','Mazandaran','IR','سارئ');
INSERT INTO city_local_name VALUES ('Sétif','Algeria','DZ','سطيف');
INSERT INTO city_local_name VALUES ('Bucheon','South Korea','ROK','부천시');
INSERT INTO city_local_name VALUES ('Sumy','Sumska','UA','Суми');
INSERT INTO city_local_name VALUES ('Borujerd','Lorestan','IR','بروجرد');
INSERT INTO city_local_name VALUES ('Baotou','Nei Mongol','CN','包头市');
INSERT INTO city_local_name VALUES ('Tébessa','Algeria','DZ','تبسة');
INSERT INTO city_local_name VALUES ('Patra','Dytikis Elladas','GR','Πάτρα');
INSERT INTO city_local_name VALUES ('Daejeon','South Korea','ROK','대전광역시');
INSERT INTO city_local_name VALUES ('Stavropol','Stavropolskiy','R','Ставрополь');
INSERT INTO city_local_name VALUES ('New Taipei','Taiwan','RC','新北市');
INSERT INTO city_local_name VALUES ('Petropavlovsk','North-Kazakhstan','KZ','Петропавл');
INSERT INTO city_local_name VALUES ('Kramatorsk','Donetska','UA','Краматорськ');
INSERT INTO city_local_name VALUES ('Thessaloniki','Kentrikis Makedonias','GR','Θεσσαλονίκη');
INSERT INTO city_local_name VALUES ('Dushanbe','Dushanbe','TJ','Душанбе');
INSERT INTO city_local_name VALUES ('Taoyuan','Taiwan','RC','桃園市');
INSERT INTO city_local_name VALUES ('Daraa','Daraa','SYR','مركز درعا');
INSERT INTO city_local_name VALUES ('Doha','Qatar','Q','الدوحة');
INSERT INTO city_local_name VALUES ('Poltava','Poltavska','UA','Полтава');
INSERT INTO city_local_name VALUES ('Bien Hoa','Southeast','VN','Biên Hoà');
INSERT INTO city_local_name VALUES ('Al Ubayyiḑ','Shamāl Kurdufān','SUD','الأبيض');
INSERT INTO city_local_name VALUES ('Grodno','Grodno','BY','Гродно');
INSERT INTO city_local_name VALUES ('Sanaa','Yemen','YE','صنعاء');
INSERT INTO city_local_name VALUES ('Semnan','Semnan','IR','سمنان');
INSERT INTO city_local_name VALUES ('Chuncheon','South Korea','ROK','춘천시');
INSERT INTO city_local_name VALUES ('Aden','Yemen','YE','عدن');
INSERT INTO city_local_name VALUES ('Tangshan','Hebei','CN','唐山市');
INSERT INTO city_local_name VALUES ('Rishon LeZiyyon','HaMerkaz','IL','ראשון לציון');
INSERT INTO city_local_name VALUES ('Zibo','Shandong','CN','淄博市');
INSERT INTO city_local_name VALUES ('Ulsan','South Korea','ROK','울산광역시');
INSERT INTO city_local_name VALUES ('Takamatsu','Kagawa','J','高松市');
INSERT INTO city_local_name VALUES ('Vladimir','Vladimirskaya','R','Владимир');
INSERT INTO city_local_name VALUES ('Sanandaj','Kurdestan','IR','سنندج');
INSERT INTO city_local_name VALUES ('Tianjin','Tianjin','CN','天津巿');
INSERT INTO city_local_name VALUES ('Cheongju','South Korea','ROK','청주시');
INSERT INTO city_local_name VALUES ('Sochi','Krasnodarskiy','R','Сочи');
INSERT INTO city_local_name VALUES ('Al Qahirah','Egypt','ET','القاهرة');
INSERT INTO city_local_name VALUES ('Taipei','Taiwan','RC','臺北市');
INSERT INTO city_local_name VALUES ('Maragheh','West Azarbayejan','IR','مراغه');
INSERT INTO city_local_name VALUES ('Xiamen','Fujian','CN','厦门市');
INSERT INTO city_local_name VALUES ('Ternopil','Ternopilska','UA','Тернопіль');
INSERT INTO city_local_name VALUES ('Tabriz','East Azarbayejan','IR','تبريز');
INSERT INTO city_local_name VALUES ('Kobe','Hyogo','J','神戸市');
INSERT INTO city_local_name VALUES ('Battambang','Cambodia','K','ក្រុងបាត់ដំបង');
INSERT INTO city_local_name VALUES ('Chernihiv','Chernihivska','UA','Чернігів');
INSERT INTO city_local_name VALUES ('Sagamihara','Kanagawa','J','相模原市');
INSERT INTO city_local_name VALUES ('Kermanshah','Kermanshah','IR','کرمانشاه');
INSERT INTO city_local_name VALUES ('Nouakchott','Nouakchott','RIM','نواكشوط');
INSERT INTO city_local_name VALUES ('Taichung','Taiwan','RC','臺中市');
INSERT INTO city_local_name VALUES ('Rach Gia','Mekong River Delta','VN','Rạch Giá');
INSERT INTO city_local_name VALUES ('Mawlamyine','Mon','MYA','မော်လမြိုင်မြို့');
INSERT INTO city_local_name VALUES ('Tainan','Taiwan','RC','臺南市');
INSERT INTO city_local_name VALUES ('Kafr ad Dawwar','Egypt','ET','كفر الدوار');
INSERT INTO city_local_name VALUES ('Aswan','Egypt','ET','أسوان');
INSERT INTO city_local_name VALUES ('Linyi','Shandong','CN','临沂市');
INSERT INTO city_local_name VALUES ('Mostaganem','Algeria','DZ','مستغانم');
INSERT INTO city_local_name VALUES ('Long Xuyen','Mekong River Delta','VN','Long Xuyên');
INSERT INTO city_local_name VALUES ('Balkhash','Karaganda','KZ','Балқаш');
INSERT INTO city_local_name VALUES ('Damanhur','Egypt','ET','دمنهور');
INSERT INTO city_local_name VALUES ('Novorossiysk','Krasnodarskiy','R','Новороссийск');
INSERT INTO city_local_name VALUES ('Samut Prakan','Thailand','THA','สมุทรปราการ');
INSERT INTO city_local_name VALUES ('Vladikavkaz','North Ossetia-Alania','R','Владикавказ');
INSERT INTO city_local_name VALUES ('Bejaïa','Algeria','DZ','بجاية');
INSERT INTO city_local_name VALUES ('Béchar','Algeria','DZ','بشار');
INSERT INTO city_local_name VALUES ('Osaka','Osaka','J','大阪市');
INSERT INTO city_local_name VALUES ('Peristeri','Attikis','GR','Περιστέρι');
INSERT INTO city_local_name VALUES ('Seoul','South Korea','ROK','서울특별시');
INSERT INTO city_local_name VALUES ('Fukuyama','Hiroshima','J','福山市');
INSERT INTO city_local_name VALUES ('Sfax','Tunisia','TN','صفاقس');
INSERT INTO city_local_name VALUES ('Taunggyi','Shan','MYA','တောင်ကြီးမြို့');
INSERT INTO city_local_name VALUES ('Stara Zagora','Bulgaria','BG','Стара Загора');
INSERT INTO city_local_name VALUES ('Duma','Rif Dimashq','SYR','دوما');
INSERT INTO city_local_name VALUES ('Da Nang','North and South Central Coast','VN','Đà Nẵng');
INSERT INTO city_local_name VALUES ('Öskemen','East-Kazakhstan','KZ','Өскемен');
INSERT INTO city_local_name VALUES ('Atbara','Nahr an-Nīl','SUD','عطبرة');
INSERT INTO city_local_name VALUES ('Ningbo','Zhejiang','CN','宁波市');
INSERT INTO city_local_name VALUES ('Khartoum North','Al-Kharṭūm','SUD','الخرطوم بحري');
INSERT INTO city_local_name VALUES ('Az Zaqaziq','Egypt','ET','الزقازيق');
INSERT INTO city_local_name VALUES ('Skikda','Algeria','DZ','سكيكدة');
INSERT INTO city_local_name VALUES ('Arkhangelsk','Arkhangelskaya','R','Архангельск');
INSERT INTO city_local_name VALUES ('Iraklio','Kritis','GR','Ηράκλειο');
INSERT INTO city_local_name VALUES ('Songkhla','Thailand','THA','สงขลา');
INSERT INTO city_local_name VALUES ('Qina','Egypt','ET','قنــــا');
INSERT INTO city_local_name VALUES ('Yazd','Yazd','IR','يزد');
INSERT INTO city_local_name VALUES ('Nur-Sultan','Astana','KZ','Астана');
INSERT INTO city_local_name VALUES ('Kostroma','Kostromskaya','R','Кострома');
INSERT INTO city_local_name VALUES ('Makhachkala','Dagestan','R','Махачкала');
INSERT INTO city_local_name VALUES ('Al-Junaynah','Gharb al-Dārfūr','SUD','الجنينة');
INSERT INTO city_local_name VALUES ('Herat','Afghanistan','AFG','هرات');
INSERT INTO city_local_name VALUES ('Zahedan','Sistan and Baluchestan','IR','زاهدان');
INSERT INTO city_local_name VALUES ('Athina','Attikis','GR','Αθήνα');
INSERT INTO city_local_name VALUES ('Jinju','South Korea','ROK','진주시');
INSERT INTO city_local_name VALUES ('Hefei','Anhui','CN','合肥市');
INSERT INTO city_local_name VALUES ('Rivne','Rivnenska','UA','Рівне');
INSERT INTO city_local_name VALUES ('Minsk','Minsk City','BY','Мінск');
INSERT INTO city_local_name VALUES ('Guangzhou','Guangdong','CN','广州市');
INSERT INTO city_local_name VALUES ('Nantong','Jiangsu','CN','南通市');
INSERT INTO city_local_name VALUES ('Kherson','Khersonska','UA','Херсон');
INSERT INTO city_local_name VALUES ('Baghdad','Baghdad','IRQ','بغداد');
INSERT INTO city_local_name VALUES ('Ivano-Frankivsk','Ivano-Frankivska','UA','Івано-Франківськ');
INSERT INTO city_local_name VALUES ('Yerevan','Armenia','ARM','Երևան');
INSERT INTO city_local_name VALUES ('Tel Aviv-Yafo','Tel Aviv','IL','תל אביב -יפו');
INSERT INTO city_local_name VALUES ('Al Fayyum','Egypt','ET','الفيوم');
INSERT INTO city_local_name VALUES ('As Suwayda','As Suwayda','SYR','السويداء');
INSERT INTO city_local_name VALUES ('Mary','Mary','TM','Mary');
INSERT INTO city_local_name VALUES ('Nanning','Guangxi','CN','南宁市');
INSERT INTO city_local_name VALUES ('Acharnes','Attikis','GR','Αχαρνές');
INSERT INTO city_local_name VALUES ('Qazvin','Qazvin','IR','قزوين');
INSERT INTO city_local_name VALUES ('Idlib','Idlib','SYR','ادلب');
INSERT INTO city_local_name VALUES ('Beograd','Serbia','SRB','Београд');
INSERT INTO city_local_name VALUES ('Kyïv','Kyïv','UA','Київ');
INSERT INTO city_local_name VALUES ('Beer Sheva','HaDarom','IL','באר שבע');
INSERT INTO city_local_name VALUES ('Kumamoto','Kumamoto','J','熊本市');
INSERT INTO city_local_name VALUES ('Kashan','Tehran','IR','كاشان');
INSERT INTO city_local_name VALUES ('Kawasaki','Kanagawa','J','川崎市');
INSERT INTO city_local_name VALUES ('Mandalay','Mandalay','MYA','မန္တလေး');
INSERT INTO city_local_name VALUES ('Annaba','Algeria','DZ','عنابة');
INSERT INTO city_local_name VALUES ('Taitung','Taiwan','RC','臺東市');
INSERT INTO city_local_name VALUES ('Krasnodar','Krasnodarskiy','R','Краснодар');
INSERT INTO city_local_name VALUES ('Anyang','South Korea','ROK','안양시');
INSERT INTO city_local_name VALUES ('Nouadhibou','Dakhlet Nouadhibou','RIM','انواذيبو');
INSERT INTO city_local_name VALUES ('Oran','Algeria','DZ','وهران');
INSERT INTO city_local_name VALUES ('Bryansk','Bryanskaya','R','Брянск');
INSERT INTO city_local_name VALUES ('Tbilisi','Georgia','GE','თბილისი');
INSERT INTO city_local_name VALUES ('Port Sudan','Al-Baḥr al-Aḥmar','SUD','بورتسودان');
INSERT INTO city_local_name VALUES ('Haiphong','Red River Delta','VN','Hải Phòng');
INSERT INTO city_local_name VALUES ('Irbid','Jordan','JOR','اربد');
INSERT INTO city_local_name VALUES ('Karaganda','Karaganda','KZ','Қарағанды');
INSERT INTO city_local_name VALUES ('Benghazi','Libya','LAR','بنغازي');
INSERT INTO city_local_name VALUES ('Jeddah','Makkah Al-Mokarramah','SA','جدة');
INSERT INTO city_local_name VALUES ('Irkutsk','Irkutskaya','R','Иркутск');
INSERT INTO city_local_name VALUES ('Zanjan','Zanjan','IR','زنجان');
INSERT INTO city_local_name VALUES ('Bushehr','Bushehr','IR','بوشهر');
INSERT INTO city_local_name VALUES ('Zaporizhzhia','Zaporizka','UA','Запоріжжя');
INSERT INTO city_local_name VALUES ('Al Qamishl','Al Hasakah','SYR','القامشلي');
INSERT INTO city_local_name VALUES ('Surgut','Khanty Mansi ao','R','Сургут');
INSERT INTO city_local_name VALUES ('Sousse','Tunisia','TN','سوسة');
INSERT INTO city_local_name VALUES ('Makkah','Makkah Al-Mokarramah','SA','مكة');
INSERT INTO city_local_name VALUES ('Sannār','Sannār','SUD','سنار');
INSERT INTO city_local_name VALUES ('Yerushalayim','Yerushalayim','IL','ירושלים');
INSERT INTO city_local_name VALUES ('Esfahan','Esfahan','IR','اصفهان');
INSERT INTO city_local_name VALUES ('Goyang','South Korea','ROK','고양시');
INSERT INTO city_local_name VALUES ('Eslam Shahr','Tehran','IR','اسلام شهر');
INSERT INTO city_local_name VALUES ('Changhua','Taiwan','RC','彰化市');
INSERT INTO city_local_name VALUES ('Bago','Bago','MYA','ပဲခူးမြို့');
INSERT INTO city_local_name VALUES ('Can Tho','Mekong River Delta','VN','Cần Thơ');
INSERT INTO city_local_name VALUES ('Peiraias','Attikis','GR','Πειραιάς');
INSERT INTO city_local_name VALUES ('Sirjan','Kerman','IR','سيرجان');
INSERT INTO city_local_name VALUES ('Lipetsk','Lipetskaya','R','Липецк');
INSERT INTO city_local_name VALUES ('Kénitra','Gharb Chrarda Beni Hssen','MA','القنيطرة');
INSERT INTO city_local_name VALUES ('Tehran','Tehran','IR','تهران');
INSERT INTO city_local_name VALUES ('Al Sharjah','United Arab Emirates','UAE','الشارقة');
INSERT INTO city_local_name VALUES ('Batumi','Georgia','GE','ბათუმი');
INSERT INTO city_local_name VALUES ('Vinnytsia','Vinnytska','UA','Вінниця');
INSERT INTO city_local_name VALUES ('Mogilev','Mogilev','BY','Могилев');
INSERT INTO city_local_name VALUES ('Xuzhou','Jiangsu','CN','徐州市');
INSERT INTO city_local_name VALUES ('Nizhnii Novgorod','Nizhnii Novgorodskaya','R','Нижний Новгород');
INSERT INTO city_local_name VALUES ('Hue','North and South Central Coast','VN','Huế');
INSERT INTO city_local_name VALUES ('Kabul','Afghanistan','AFG','کابل');
INSERT INTO city_local_name VALUES ('Kandahar','Afghanistan','AFG','کندهار');
INSERT INTO city_local_name VALUES ('Samara','Samarskaya','R','Самара');
INSERT INTO city_local_name VALUES ('Reykjavik','Iceland','IS','Reykjavík');
INSERT INTO city_local_name VALUES ('Algiers','Algeria','DZ','الجزائر');
INSERT INTO city_local_name VALUES ('Khabarovsk','Khabarovskiy','R','Хабаровск');
INSERT INTO city_local_name VALUES ('Amman','Jordan','JOR','العاصمة');
INSERT INTO city_local_name VALUES ('Riyadh','Al-Riyadh','SA','الرياض');
INSERT INTO city_local_name VALUES ('Yeosu','South Korea','ROK','여수시');
INSERT INTO city_local_name VALUES ('Kassala','Kassalā','SUD','كسلا');
INSERT INTO city_local_name VALUES ('Zhezkazgan','Karaganda','KZ','Жезқазған');
INSERT INTO city_local_name VALUES ('Shiraz','Fars','IR','شيراز');
INSERT INTO city_local_name VALUES ('Hsinchu','Taiwan','RC','新竹市');
INSERT INTO city_local_name VALUES ('Utsunomiya','Tochigi','J','宇都宮市');
INSERT INTO city_local_name VALUES ('Monywa','Sagaing','MYA','မုံရွာမြို့');
INSERT INTO city_local_name VALUES ('Toyama','Toyama','J','富山市');
INSERT INTO city_local_name VALUES ('Saransk','Mordoviya','R','Саранск');
INSERT INTO city_local_name VALUES ('Ashgabat','Ashgabat','TM','Aşgabat');
INSERT INTO city_local_name VALUES ('Voronezh','Voronezhskaya','R','Воронеж');
INSERT INTO city_local_name VALUES ('Hirakata','Osaka','J','枚方市');
INSERT INTO city_local_name VALUES ('Kagoshima','Kagoshima','J','鹿児島市');
INSERT INTO city_local_name VALUES ('Nikopol','Dnipropetrovska','UA','Нікополь');
INSERT INTO city_local_name VALUES ('Nizhny Tagil','Sverdlovskaya','R','Нижний Тагил');
INSERT INTO city_local_name VALUES ('At Taif','Makkah Al-Mokarramah','SA','الطائف');
INSERT INTO city_local_name VALUES ('Lviv','Lvivska','UA','Львів');
INSERT INTO city_local_name VALUES ('Al Gedaref','Al-Qaḍārif','SUD','القضارف');
INSERT INTO city_local_name VALUES ('Tartus','Tartus','SYR','طرطوس');
INSERT INTO city_local_name VALUES ('Foshan','Guangdong','CN','佛山市');
INSERT INTO city_local_name VALUES ('Horlivka','Donetska','UA','Горлівка');
INSERT INTO city_local_name VALUES ('Fès','Fes Boulemane','MA','فاس');
INSERT INTO city_local_name VALUES ('Petah Tiqwa','HaMerkaz','IL','פתח תקווה');
INSERT INTO city_local_name VALUES ('Zhengzhou','Henan','CN','郑州市');
INSERT INTO city_local_name VALUES ('Ulan-Ude','Buryatiya','R','Улан-Удэ');
INSERT INTO city_local_name VALUES ('Dezful','Khuzestan','IR','دزفول');
INSERT INTO city_local_name VALUES ('Oral','West Kazakhstan','KZ','Орал');
INSERT INTO city_local_name VALUES ('Zhongshan','Guangdong','CN','珠海市');
INSERT INTO city_local_name VALUES ('Mazar-i-Sharif','Afghanistan','AFG','مزار شریف');
INSERT INTO city_local_name VALUES ('Balkanabat','Balkan','TM','Balkanabat');
INSERT INTO city_local_name VALUES ('Krasnoyarsk','Krasnoyarsk','R','Красноярск');
INSERT INTO city_local_name VALUES ('Shenzhen','Guangdong','CN','深圳市');
INSERT INTO city_local_name VALUES ('Keflavik','Iceland','IS','Keflavík og Njarðvíkurþéttbýli');
INSERT INTO city_local_name VALUES ('Mariupol','Donetska','UA','Маріуполь');
INSERT INTO city_local_name VALUES ('Tougourt','Algeria','DZ','توغرة');
INSERT INTO city_local_name VALUES ('Pathein','Ayeyarwady','MYA','ပုသိမ်မြို့');
INSERT INTO city_local_name VALUES ('Kirovohrad','Kirovohradska','UA','Кіровоград');
INSERT INTO city_local_name VALUES ('Koksetau','Akmola','KZ','Көкшетау');
INSERT INTO city_local_name VALUES ('Kazan','Tatarstan','R','Казань');
INSERT INTO city_local_name VALUES ('Vologda','Vologodskaya','R','Вологда');
INSERT INTO city_local_name VALUES ('Thai Nguyen','Northern Midlands and Mountains','VN','Thái Nguyên');
INSERT INTO city_local_name VALUES ('Dongguan','Guangdong','CN','东莞市');
INSERT INTO city_local_name VALUES ('Omsk','Omskaya','R','Омск');
INSERT INTO city_local_name VALUES ('Volgograd','Volgogradskaya','R','Волгоград');
INSERT INTO city_local_name VALUES ('Changwon','South Korea','ROK','창원시');
INSERT INTO city_local_name VALUES ('Al Minya','Egypt','ET','المنيا');
INSERT INTO city_local_name VALUES ('Misratah','Libya','LAR','مصراتة');
INSERT INTO city_local_name VALUES ('Tambov','Tambovskaya','R','Тамбов');
INSERT INTO city_local_name VALUES ('Ar Raqqah','Ar Raqqah','SYR','الرقة');
INSERT INTO city_local_name VALUES ('Changzhou','Jiangsu','CN','常州市');
INSERT INTO city_local_name VALUES ('Yekaterinburg','Sverdlovskaya','R','Екатеринбург');
INSERT INTO city_local_name VALUES ('Sankt Peterburg','Sankt-Peterburg','R','Санкт-Петербург');
INSERT INTO city_local_name VALUES ('Karaj','Alborz','IR','كرج');
INSERT INTO city_local_name VALUES ('Naberezhnye Tchelny','Tatarstan','R','Набережные Челны');
INSERT INTO city_local_name VALUES ('Nakhon Ratchasima','Thailand','THA','นครราชสีมา');
INSERT INTO city_local_name VALUES ('Kumanovo','North Macedonia','MK','Град Куманово');
INSERT INTO city_local_name VALUES ('Buon Ma Thuot','Central Highlands','VN','Buôn Ma Thuột');
INSERT INTO city_local_name VALUES ('Suzhou','Jiangsu','CN','苏州市');
INSERT INTO city_local_name VALUES ('Ulaanbaatar','Mongolia','MNG','Улаанбаатар');
INSERT INTO city_local_name VALUES ('Nay Pyi Taw','Nay Pyi Taw','MYA','နေပြည်တော်');
INSERT INTO city_local_name VALUES ('Bani Suwayf','Egypt','ET','بني سويف');
INSERT INTO city_local_name VALUES ('Nador','Oriental','MA','النادور');
INSERT INTO city_local_name VALUES ('Ha Long','Northern Midlands and Mountains','VN','Hạ Long');
INSERT INTO city_local_name VALUES ('Yakutsk','Sakha','R','Якутск');
INSERT INTO city_local_name VALUES ('Saitama','Saitama','J','さいたま市');
INSERT INTO city_local_name VALUES ('Nakhon Sawan','Thailand','THA','นครสวรรค์');
INSERT INTO city_local_name VALUES ('Hanoi','Red River Delta','VN','Hà Nội');
INSERT INTO city_local_name VALUES ('Kursk','Kurskaya','R','Курск');
INSERT INTO city_local_name VALUES ('Changchun','Jilin','CN','长春市');
INSERT INTO city_local_name VALUES ('Yoshkar-Ola','Mariy-El','R','Йошкар-Ола');
INSERT INTO city_local_name VALUES ('Nizhnevartovsk','Khanty Mansi ao','R','Нижневартовск');
INSERT INTO city_local_name VALUES ('Agadir','Souss Massa Daraa','MA','أكادير');
INSERT INTO city_local_name VALUES ('Donetsk','Donetska','UA','Донецьк');
INSERT INTO city_local_name VALUES ('Khomeinishahr','Esfahan','IR','خميني شهر');
INSERT INTO city_local_name VALUES ('Birjand','South Khorasan','IR','بيرجند');
INSERT INTO city_local_name VALUES ('Ruse','Bulgaria','BG','Русе');
INSERT INTO city_local_name VALUES ('Al Madinah','Al-Madinah Al-Monawarah','SA','المدينة');
INSERT INTO city_local_name VALUES ('Shanghai','Shanghai','CN','上海巿');
INSERT INTO city_local_name VALUES ('Oujda','Oriental','MA','وجدة');
INSERT INTO city_local_name VALUES ('Ghardaïa','Algeria','DZ','غرداية');
INSERT INTO city_local_name VALUES ('Ilam','Ilam','IR','ايلام');
INSERT INTO city_local_name VALUES ('Bishkek','Kyrgyzstan','KG','Бишкек');
INSERT INTO city_local_name VALUES ('Chiba','Chiba','J','千葉市');
INSERT INTO city_local_name VALUES ('Kerch','Krym','UA','Керч');
INSERT INTO city_local_name VALUES ('Qaemshahr','Mazandaran','IR','قائم شهر');
INSERT INTO city_local_name VALUES ('Khartoum','Al-Kharṭūm','SUD','الخرطوم');
INSERT INTO city_local_name VALUES ('Beijing','Beijing','CN','北京巿');
INSERT INTO city_local_name VALUES ('Himeji','Hyogo','J','姫路市');
INSERT INTO city_local_name VALUES ('Tanger','Tanger Tetouan','MA','طنجة');
INSERT INTO city_local_name VALUES ('Volos','Thessalias','GR','Βόλος');
INSERT INTO city_local_name VALUES ('Babol','Mazandaran','IR','بابل');
INSERT INTO city_local_name VALUES ('Yasuj','Kohgiluyeh and Boyer-Ahmad','IR','ياسوج');
INSERT INTO city_local_name VALUES ('Shantou','Guangdong','CN','汕头市');
INSERT INTO city_local_name VALUES ('Al Fashir','Shamāl Dārfūr','SUD','الفاشر');
INSERT INTO city_local_name VALUES ('Aqtobe','Aktobe','KZ','Ақтөбе');
INSERT INTO city_local_name VALUES ('Phuket','Thailand','THA','ภูเก็ต');
INSERT INTO city_local_name VALUES ('Baku','Azerbaijan','AZ','Bakı');
INSERT INTO city_local_name VALUES ('Hafnarfjordur','Iceland','IS','Hafnarfjörður');
INSERT INTO city_local_name VALUES ('Amagasaki','Hyogo','J','尼崎市');
INSERT INTO city_local_name VALUES ('Tver','Tverskaya','R','Тверь');
INSERT INTO city_local_name VALUES ('Petrozavodsk','Karelia','R','Петрозаводск');
INSERT INTO city_local_name VALUES ('Oita','Oita','J','大分市');
INSERT INTO city_local_name VALUES ('Batna','Algeria','DZ','باتنة');
INSERT INTO city_local_name VALUES ('Komsomolsk-na-Amure','Khabarovskiy','R','Комсомольск-на-Амуре');
INSERT INTO city_local_name VALUES ('Odesa','Odeska','UA','Одеса');
INSERT INTO city_local_name VALUES ('Haifa','Hefa','IL','חיפה');
INSERT INTO city_local_name VALUES ('Al Rayyan','Qatar','Q','الريان');
INSERT INTO city_local_name VALUES ('Novi Sad','Serbia','SRB','Нови Сад');
INSERT INTO city_local_name VALUES ('Sendai','Miyagi','J','仙台市');
INSERT INTO city_local_name VALUES ('Shizuoka','Shizuoka','J','静岡市');
INSERT INTO city_local_name VALUES ('Smolensk','Smolenskaya','R','Смоленск');
INSERT INTO city_local_name VALUES ('Plovdiv','Bulgaria','BG','Пловдив');
INSERT INTO city_local_name VALUES ('Matsuyama','Ehime','J','松山市');
INSERT INTO city_local_name VALUES ('Settat','Chaouia Ouardigha','MA','سطات');
INSERT INTO city_local_name VALUES ('Harbin','Heilongjiang','CN','哈尔滨市');
INSERT INTO city_local_name VALUES ('Amol','Mazandaran','IR','آمل');
INSERT INTO city_local_name VALUES ('Ufa','Bashkortostan','R','Уфа');
INSERT INTO city_local_name VALUES ('Chengdu','Sichuan','CN','成都市');
INSERT INTO city_local_name VALUES ('Kurgan','Kurganskaya','R','Курган');
INSERT INTO city_local_name VALUES ('Dalian','Liaoning','CN','大连市');
INSERT INTO city_local_name VALUES ('Saratov','Saratovskaya','R','Саратов');
INSERT INTO city_local_name VALUES ('Al Gazira','Al-Jazīrah','SUD','الجزيرة');
INSERT INTO city_local_name VALUES ('Tétouan','Tanger Tetouan','MA','تطوان');
INSERT INTO city_local_name VALUES ('Suwon','South Korea','ROK','수원시');
INSERT INTO city_local_name VALUES ('Hamedan','Hamedan','IR','همدان');
INSERT INTO city_local_name VALUES ('Constantine','Algeria','DZ','قسنطينة');
