INSERT INTO city_other_name VALUES ('Nacala Porto','Maputo','MOC','Nacala');
INSERT INTO city_other_name VALUES ('Navi Mumbai','Maharashtra','IND','New Bombay');
INSERT INTO city_other_name VALUES ('Jhongli','Taiwan','RC','Zhongli');
INSERT INTO city_other_name VALUES ('Sri Jayawardhanapura','Sri Lanka','CL','Kotte');
INSERT INTO city_other_name VALUES ('Coyhaique','Aysén','RCH','Coihaique');
INSERT INTO city_other_name VALUES ('Yaroslavl','Yaroslavskaya','R','Jaroslavl');
INSERT INTO city_other_name VALUES ('Saint Catharines','Ontario','CDN','St. Catharines');
INSERT INTO city_other_name VALUES ('Tidjikja','Tagant','RIM','Tidjikdja');
INSERT INTO city_other_name VALUES ('Qo‘qon','Fargʻona','UZ','Kokand');
INSERT INTO city_other_name VALUES ('Lefkosia','Cyprus','CY','Nicosia');
INSERT INTO city_other_name VALUES ('Daman','Daman and Diu','IND','Diu');
INSERT INTO city_other_name VALUES ('Dzeržinsk','Nizhnii Novgorodskaya','R','Dzerzhinsk');
INSERT INTO city_other_name VALUES ('Athina','Attikis','GR','Athens');
INSERT INTO city_other_name VALUES ('La Habana','La Habana','C','Habana');
INSERT INTO city_other_name VALUES ('Ahvaz','Khuzestan','IR','Ahwaz');
INSERT INTO city_other_name VALUES ('Sheikhupura','Punjab','PK','Sheikhūpura');
INSERT INTO city_other_name VALUES ('Gauhati','Assam','IND','Guwahati');
INSERT INTO city_other_name VALUES ('Gent','Oost-Vlaanderen','B','Gand');
INSERT INTO city_other_name VALUES ('As Sulaymaniyah','As Sulaymaniyah','IRQ','Sulaymaniyah');
INSERT INTO city_other_name VALUES ('Funchal','Madeira','P','Madeira');
INSERT INTO city_other_name VALUES ('Tirgu Jiu','Gorj','RO','Târgu Jiu');
INSERT INTO city_other_name VALUES ('Al Fayyum','Egypt','ET','Faiyum');
INSERT INTO city_other_name VALUES ('Makkah','Makkah Al-Mokarramah','SA','Mecca');
INSERT INTO city_other_name VALUES ('Helsingør','Hovedstaden','DK','Elsinore');
INSERT INTO city_other_name VALUES ('Milano','Lombardia','I','Milan');
INSERT INTO city_other_name VALUES ('Kim Chaek','North Korea','KP','Songjin');
INSERT INTO city_other_name VALUES ('Nápoli','Campania','I','Naples');
INSERT INTO city_other_name VALUES ('Ho Chi Minh City','Southeast','VN','Ho Chi Minh');
INSERT INTO city_other_name VALUES ('Poza Rica de Hidalgo','Veracruz','MEX','Poza Rica');
INSERT INTO city_other_name VALUES ('Embu','São Paulo','BR','Embu das Artes');
INSERT INTO city_other_name VALUES ('Turkmenabat','Lebap','TM','Charjew');
INSERT INTO city_other_name VALUES ('Sialkot','Punjab','PK','Siālkot');
INSERT INTO city_other_name VALUES ('Hamhung-Hungnam','North Korea','KP','Hamhung');
INSERT INTO city_other_name VALUES ('Karachi','Sindh','PK','Karāchi');
INSERT INTO city_other_name VALUES ('Nizhnevartovsk','Khanty Mansi ao','R','Nižnevartovsk');
INSERT INTO city_other_name VALUES ('Al Amarah','Maysan','IRQ','Amarah');
INSERT INTO city_other_name VALUES ('Kerkyra','Ionion Nison','GR','Korfu');
INSERT INTO city_other_name VALUES ('Ekurhuleni - Germiston','Gauteng','RSA','Ekurhuleni');
INSERT INTO city_other_name VALUES ('Mersin','Mersin','TR','Icel');
INSERT INTO city_other_name VALUES ('Sahiwal','Punjab','PK','Sāhīwal');
INSERT INTO city_other_name VALUES ('Voronezh','Voronezhskaya','R','Voronež');
INSERT INTO city_other_name VALUES ('Chelyabinsk','Chelyabinskaya','R','Čelabinsk');
INSERT INTO city_other_name VALUES ('Bahawalpur','Punjab','PK','Bahāwalpur');
INSERT INTO city_other_name VALUES ('Mirpur Khas','Sindh','PK','Mīrpur Khās');
INSERT INTO city_other_name VALUES ('Bodø','Nordland','N','Bodoe');
INSERT INTO city_other_name VALUES ('Chasavjurt','Dagestan','R','Khasavyurt');
INSERT INTO city_other_name VALUES ('Yoshkar-Ola','Mariy-El','R','Joškar-Ola');
INSERT INTO city_other_name VALUES ('Petropavlovsk-Kamčatskij','Kamchatka','R','Petropavlovsk Kamchatsky');
INSERT INTO city_other_name VALUES ('Las Palmas de Gran Canaria','Canarias','E','Las Palmas');
INSERT INTO city_other_name VALUES ('Zouerate','Tiris Zemmour','RIM','Zouérat');
INSERT INTO city_other_name VALUES ('A Coruña','Galicia','E','La Coruna');
INSERT INTO city_other_name VALUES ('Arkhangelsk','Arkhangelskaya','R','Archangelsk');
INSERT INTO city_other_name VALUES ('Reggio nell''Emilia','Emilia-Romagna','I','Reggio Emilia');
INSERT INTO city_other_name VALUES ('Omdurman','Al-Kharṭūm','SUD','Umm Durman');
INSERT INTO city_other_name VALUES ('Shibin al Kum','Egypt','ET','Shibin El Kom');
INSERT INTO city_other_name VALUES ('Ciudad Santa Catarina','Nuevo Léon','MEX','Santa Catarina');
INSERT INTO city_other_name VALUES ('Bokaro Steel City','Jharkhand','IND','Bokara Steel City');
INSERT INTO city_other_name VALUES ('Tavoy','Tanintharyi','MYA','Dawei');
INSERT INTO city_other_name VALUES ('Peshawar','Khyber Pakhtunkhwa','PK','Peshāwar');
INSERT INTO city_other_name VALUES ('Ahmadabad','Gujarat','IND','Ahmedabad');
INSERT INTO city_other_name VALUES ('Eslam Shahr','Tehran','IR','Islamshahr');
INSERT INTO city_other_name VALUES ('Kerkyra','Ionion Nison','GR','Corfu');
INSERT INTO city_other_name VALUES ('Santa Ana de Coro','Falcón','YV','Coro');
INSERT INTO city_other_name VALUES ('Sergijev Posad','Moskovskaya','R','Zagorsk');
INSERT INTO city_other_name VALUES ('Genève','Genève','CH','Geneva');
INSERT INTO city_other_name VALUES ('Diwaniyah','al-Qadisiya','IRQ','Al Diwaniyah');
INSERT INTO city_other_name VALUES ('Xalapa-Enríquez','Veracruz','MEX','Jalapa');
INSERT INTO city_other_name VALUES ('Tel Aviv-Yafo','Tel Aviv','IL','Tel Aviv');
INSERT INTO city_other_name VALUES ('Novočerkassk','Rostovskaya','R','Novocherkassk');
INSERT INTO city_other_name VALUES ('Rhodes','Notioy Aigaioy','GR','Rhodos');
INSERT INTO city_other_name VALUES ('Fargona','Fargʻona','UZ','Fergana');
INSERT INTO city_other_name VALUES ('Batajsk','Rostovskaya','R','Bataysk');
INSERT INTO city_other_name VALUES ('El Aaiun','Western Sahara','WSA','Laâyoune');
INSERT INTO city_other_name VALUES ('Wah Cantonment','Punjab','PK','Wāh Cantonment');
INSERT INTO city_other_name VALUES ('Effon-Alaiye','Ekiti','NGR','Efon-Alaaye');
INSERT INTO city_other_name VALUES ('Lubercy','Moskovskaya','R','Lyubertsy');
INSERT INTO city_other_name VALUES ('Aioun','Hodh El Gharbi','RIM','Ayoûn el-Atroûs');
INSERT INTO city_other_name VALUES ('Nashville-Davidson','Tennessee','USA','Nashville');
INSERT INTO city_other_name VALUES ('Pamplona','Navarra','E','Iruña');
INSERT INTO city_other_name VALUES ('Dimashq','Dimashq','SYR','Damascus');
INSERT INTO city_other_name VALUES ('San Andres de Tumaco','Nariño','CO','Tumaco');
INSERT INTO city_other_name VALUES ('Afyonkarahisar','Afyonkarahisar','TR','Afyon');
INSERT INTO city_other_name VALUES ('Khanty Mansijsk','Khanty Mansi ao','R','Khanty Mansiysk');
INSERT INTO city_other_name VALUES ('Al Qunaytirah','Al Qunaytirah','SYR','Quneitra');
INSERT INTO city_other_name VALUES ('Rahimyar Khan','Punjab','PK','Rahim Yar Khan');
INSERT INTO city_other_name VALUES ('Kim Chaek','North Korea','KP','Kimchaek');
INSERT INTO city_other_name VALUES ('Kustanay','Kostanai','KZ','Kostanay');
INSERT INTO city_other_name VALUES ('Offenbach am Main','Hessen','D','Offenbach');
INSERT INTO city_other_name VALUES ('Novočeboksarsk','Chuvashia','R','Novocheboksarsk');
INSERT INTO city_other_name VALUES ('Al Basrah','Basrah','IRQ','Basra');
INSERT INTO city_other_name VALUES ('Kota Bahru','Kelantan','MAL','Kota Bharu');
INSERT INTO city_other_name VALUES ('Chimki','Moskovskaya','R','Khimki');
INSERT INTO city_other_name VALUES ('Nampho','North Korea','KP','Nampo');
INSERT INTO city_other_name VALUES ('Ngiva','Cunene','ANG','Ondjiva');
INSERT INTO city_other_name VALUES ('Copenhagen','Hovedstaden','DK','Kopenhagen');
INSERT INTO city_other_name VALUES ('Odincovo','Moskovskaya','R','Odintsovo');
INSERT INTO city_other_name VALUES ('Al Kut','Wasit','IRQ','Kut');
INSERT INTO city_other_name VALUES ('Mamoutzou','Mayotte','MAYO','Mamoudzou');
INSERT INTO city_other_name VALUES ('Wulumuqi','Xinjiang','CN','Urumqi');
INSERT INTO city_other_name VALUES ('Sankt Peterburg','Sankt-Peterburg','R','St. Peterburg');
INSERT INTO city_other_name VALUES ('Ho Chi Minh City','Southeast','VN','Saigon');
INSERT INTO city_other_name VALUES ('Khartoum North','Al-Kharṭūm','SUD','Chartum Bahri');
INSERT INTO city_other_name VALUES ('Tyumen','Tyumenskaya','R','Tumen');
INSERT INTO city_other_name VALUES ('Gujrat','Punjab','PK','Gujrāt');
INSERT INTO city_other_name VALUES ('Novokujbyševsk','Samarskaya','R','Novokuybyshevsk');
INSERT INTO city_other_name VALUES ('Oporto','Porto','P','Porto');
INSERT INTO city_other_name VALUES ('Kochi','Kerala','IND','Cochin');
INSERT INTO city_other_name VALUES ('Sankt Gallen','Sankt Gallen','CH','St. Gallen');
INSERT INTO city_other_name VALUES ('Al Jizah','Egypt','ET','Gizeh');
INSERT INTO city_other_name VALUES ('Prokopjevsk','Kemerovskaya','R','Prokopyevsk');
INSERT INTO city_other_name VALUES ('Nogales','Sonora','MEX','Heroica Nogales');
INSERT INTO city_other_name VALUES ('Grozny','Chechenskaya','R','Groznyj');
INSERT INTO city_other_name VALUES ('Bur Said','Egypt','ET','Port Said');
INSERT INTO city_other_name VALUES ('Dehra Dun','Uttarakhand','IND','Dehradun');
INSERT INTO city_other_name VALUES ('Novyj Urengoj','Yamalo Nenets ao','R','Novy Urengoy');
INSERT INTO city_other_name VALUES ('Al Baha','Al-Baha','SA','Al Bahah');
INSERT INTO city_other_name VALUES ('Tabouk','Tabouk','SA','Tabuk');
INSERT INTO city_other_name VALUES ('Yasuj','Kohgiluyeh and Boyer-Ahmad','IR','Yasouj');
INSERT INTO city_other_name VALUES ('Nelson Mandela Bay','Eastern Cape','RSA','Port Elizabeth');
INSERT INTO city_other_name VALUES ('Yakutsk','Sakha','R','Jakutsk');
INSERT INTO city_other_name VALUES ('Sakarya','Sakarya','TR','Adapazari');
INSERT INTO city_other_name VALUES ('Luzern','Luzern','CH','Lucerne');
INSERT INTO city_other_name VALUES ('Misratah','Libya','LAR','Misrata');
INSERT INTO city_other_name VALUES ('Kafr ad Dawwar','Egypt','ET','Kafr el-Dawwar');
INSERT INTO city_other_name VALUES ('Petropavlovsk','North-Kazakhstan','KZ','Petropavl');
INSERT INTO city_other_name VALUES ('Klang','Selangor','MAL','Kelang');
INSERT INTO city_other_name VALUES ('Cherepovets','Vologodskaya','R','Čerepovec');
INSERT INTO city_other_name VALUES ('Al Kuwayt','Kuwait','KWT','Kuwait');
INSERT INTO city_other_name VALUES ('Al Madinah','Al-Madinah Al-Monawarah','SA','Madinah');
INSERT INTO city_other_name VALUES ('Mbombela','Mpumalanga','RSA','Nelspruit');
INSERT INTO city_other_name VALUES ('Peiraias','Attikis','GR','Piraeus');
INSERT INTO city_other_name VALUES ('Simla','Himachal Pradesh','IND','Shimla');
INSERT INTO city_other_name VALUES ('Prishtine','Kosovo','KOS','Pristina');
INSERT INTO city_other_name VALUES ('Ussurijsk','Primorskiy','R','Ussuriysk');
INSERT INTO city_other_name VALUES ('Benin','Edo','NGR','Benin City');
INSERT INTO city_other_name VALUES ('Lemesos','Cyprus','CY','Limassol');
INSERT INTO city_other_name VALUES ('Adama','Oromia','ETH','Nazret');
INSERT INTO city_other_name VALUES ('Kashgar','Xinjiang','CN','Kashi');
INSERT INTO city_other_name VALUES ('Lalitpur','Nepal','NEP','Patan');
INSERT INTO city_other_name VALUES ('Nižnekamsk','Tatarstan','R','Nizhnekamsk');
INSERT INTO city_other_name VALUES ('Bandjarmasin','Kalimantan Selatan','RI','Banjarmasin');
INSERT INTO city_other_name VALUES ('Mingaora','Khyber Pakhtunkhwa','PK','Mingawara');
INSERT INTO city_other_name VALUES ('Bolzano','Trentino-Alto Adige','I','Bozen');
INSERT INTO city_other_name VALUES ('Soledad Díez Gutiérrez','San Luis Potosí','MEX','Soledad de Graciano Sanchez');
INSERT INTO city_other_name VALUES ('Hims','Hims','SYR','Homs');
INSERT INTO city_other_name VALUES ('Kustanay','Kostanai','KZ','Kostanai');
INSERT INTO city_other_name VALUES ('Hami','Xinjiang','CN','Kumul');
INSERT INTO city_other_name VALUES ('Izhevsk','Udmurtskaya','R','Iževsk');
INSERT INTO city_other_name VALUES ('Jiaozhou','Shandong','CN','Jiaoxian');
INSERT INTO city_other_name VALUES ('Almetjevsk','Tatarstan','R','Almetyevsk');
INSERT INTO city_other_name VALUES ('Prypjat','Kyïvska','UA','Pripyat');
INSERT INTO city_other_name VALUES ('Bruxelles','Bruxelles','B','Brussels');
INSERT INTO city_other_name VALUES ('Leuven','Vlaams-Brabant','B','Louvain');
INSERT INTO city_other_name VALUES ('San Cristóbal de La Laguna','Canarias','E','La Laguna');
INSERT INTO city_other_name VALUES ('Msunduzi','KwaZulu-Natal','RSA','Pietermaritzburg');
INSERT INTO city_other_name VALUES ('Nay Pyi Taw','Nay Pyi Taw','MYA','Naypyidaw');
INSERT INTO city_other_name VALUES ('Al Sharjah','United Arab Emirates','UAE','Sharjah');
INSERT INTO city_other_name VALUES ('Jessentuki','Stavropolskiy','R','Yessentuki');
INSERT INTO city_other_name VALUES ('Olmaliq','Toshkent','UZ','Almalyk');
INSERT INTO city_other_name VALUES ('Castellón de la Plana','Valenciana','E','Castelló de la Plana');
INSERT INTO city_other_name VALUES ('Cheboksary','Chuvashia','R','Čeboksary');
INSERT INTO city_other_name VALUES ('Şanlıurfa','Şanlıurfa','TR','Urfa');
INSERT INTO city_other_name VALUES ('Xalapa-Enríquez','Veracruz','MEX','Xalapa');
INSERT INTO city_other_name VALUES ('Nelson Mandela Bay','Eastern Cape','RSA','Gqeberha');
INSERT INTO city_other_name VALUES ('Oshogbo','Osun','NGR','Osogbo');
INSERT INTO city_other_name VALUES ('Antwerpen','Antwerpen','B','Antwerp');
INSERT INTO city_other_name VALUES ('La Habana','La Habana','C','Havana');
INSERT INTO city_other_name VALUES ('Nalčik','Kabardino-Balkarskaya','R','Nalchik');
INSERT INTO city_other_name VALUES ('Boise City','Idaho','USA','Boise');
INSERT INTO city_other_name VALUES ('Namur','Namur','B','Namen');
INSERT INTO city_other_name VALUES ('Magwe','Magwe','MYA','Magway');
INSERT INTO city_other_name VALUES ('Lubuk Linggau','Sumatera Selatan','RI','Lubuklinggau');
INSERT INTO city_other_name VALUES ('Bishoftu','Oromia','ETH','Debre Zeyit');
INSERT INTO city_other_name VALUES ('Uzhhorod','Zakarpatska','UA','Uzhgorod');
INSERT INTO city_other_name VALUES ('Donostia','Euskadi','E','Donostia-San Sebastián');
INSERT INTO city_other_name VALUES ('Iraklio','Kritis','GR','Iraklion');
INSERT INTO city_other_name VALUES ('Neftejugansk','Khanty Mansi ao','R','Nefteyugansk');
INSERT INTO city_other_name VALUES ('Santarem','Santarem','P','Santarém');
INSERT INTO city_other_name VALUES ('Panaji','Goa','IND','Goa');
INSERT INTO city_other_name VALUES ('Moskva','Moscow','R','Moscow');
INSERT INTO city_other_name VALUES ('Ulyanovsk','Ulyanovskaya','R','Uljanovsk');
INSERT INTO city_other_name VALUES ('Victoria de las Tunas','Las Tunas','C','Las Tunas');
INSERT INTO city_other_name VALUES ('Nizhnii Novgorod','Nizhnii Novgorodskaya','R','Nižnij Novgorod');
INSERT INTO city_other_name VALUES ('Ciudad de Guatemala','Guatemala','GCA','Guatemala City');
INSERT INTO city_other_name VALUES ('Bani Suwayf','Egypt','ET','Beni Suef');
INSERT INTO city_other_name VALUES ('Bayrūt','Lebanon','RL','Beirut');
INSERT INTO city_other_name VALUES ('Rivne','Rivnenska','UA','Rovno');
INSERT INTO city_other_name VALUES ('Nay Pyi Taw','Nay Pyi Taw','MYA','Naypyitaw');
INSERT INTO city_other_name VALUES ('Kaspijsk','Dagestan','R','Kaspiysk');
INSERT INTO city_other_name VALUES ('Bucureşti','Bucureşti','RO','Bucarest');
INSERT INTO city_other_name VALUES ('Göteborg','Västra Götaland','S','Göteborg');
INSERT INTO city_other_name VALUES ('Serpuchov','Moskovskaya','R','Serpukhov');
INSERT INTO city_other_name VALUES ('Panshan','Liaoning','CN','Panjin');
INSERT INTO city_other_name VALUES ('Molenbeek-Saint-Jean','Bruxelles','B','Sint-Jans-Molenbeek');
INSERT INTO city_other_name VALUES ('Trivandrum','Kerala','IND','Thiruvananthapuram');
INSERT INTO city_other_name VALUES ('Pétion-Ville','Haiti','RH','Pétionville');
INSERT INTO city_other_name VALUES ('Karaganda','Karaganda','KZ','Karagandy');
INSERT INTO city_other_name VALUES ('al Hudaydah','Yemen','YE','Hodeidah');
INSERT INTO city_other_name VALUES ('Šachty','Rostovskaya','R','Shakhty');
INSERT INTO city_other_name VALUES ('Ciudad de México','Distrito Federal','MEX','Mexico City');
INSERT INTO city_other_name VALUES ('Mingaora','Khyber Pakhtunkhwa','PK','Mingora');
INSERT INTO city_other_name VALUES ('Hatay','Hatay','TR','Antakya');
INSERT INTO city_other_name VALUES ('Vientiane','Laos','LAO','Viangchan');
INSERT INTO city_other_name VALUES ('Rishon LeZiyyon','HaMerkaz','IL','Rishon LeZion');
INSERT INTO city_other_name VALUES ('Beograd','Serbia','SRB','Belgrade');
INSERT INTO city_other_name VALUES ('Khujand','Sughd','TJ','Khudzhand');
INSERT INTO city_other_name VALUES ('Žukovskij','Moskovskaya','R','Zhukovsky');
INSERT INTO city_other_name VALUES ('Mülheim','Nordrhein-Westfalen','D','Mülheim an der Ruhr');
INSERT INTO city_other_name VALUES ('Nur-Sultan','Astana','KZ','Akmolinsk');
INSERT INTO city_other_name VALUES ('Dimashq','Dimashq','SYR','Damaskus');
INSERT INTO city_other_name VALUES ('Mawlamyine','Mon','MYA','Moulmein');
INSERT INTO city_other_name VALUES ('Dera Ghazi Khan','Punjab','PK','Dera Ghāzi Khān');
INSERT INTO city_other_name VALUES ('Majkop','Adygeya','R','Maykop');
INSERT INTO city_other_name VALUES ('Tangerang Selatan','Banten','RI','South Tangerang');
INSERT INTO city_other_name VALUES ('Al Jizah','Egypt','ET','Giza');
INSERT INTO city_other_name VALUES ('Sakaka','Al-Jouf','SA','Sakakah');
INSERT INTO city_other_name VALUES ('Mingaora','Khyber Pakhtunkhwa','PK','Mingāora');
INSERT INTO city_other_name VALUES ('Daegu','South Korea','ROK','Taegu');
INSERT INTO city_other_name VALUES ('Réggio di Calabria','Calabria','I','Reggio Calabria');
INSERT INTO city_other_name VALUES ('Ekurhuleni - Germiston','Gauteng','RSA','East Rand');
INSERT INTO city_other_name VALUES ('Tshwane','Gauteng','RSA','Pretoria');
INSERT INTO city_other_name VALUES ('Sankt Peterburg','Sankt-Peterburg','R','Sankt-Peterburg');
INSERT INTO city_other_name VALUES ('Liège','Liège','B','Luik');
INSERT INTO city_other_name VALUES ('Kolkata','West Bengal','IND','Calcutta');
INSERT INTO city_other_name VALUES ('Nur-Sultan','Astana','KZ','Zelinograd');
INSERT INTO city_other_name VALUES ('Multan','Punjab','PK','Multān');
INSERT INTO city_other_name VALUES ('Bharuch','Gujarat','IND','Broach');
INSERT INTO city_other_name VALUES ('Siracusa','Sicilia','I','Syracuse');
INSERT INTO city_other_name VALUES ('Mogi Guaçu','São Paulo','BR','Moji Guacu');
INSERT INTO city_other_name VALUES ('Bhilai','Chhattisgarh','IND','Bhilai Nagar');
INSERT INTO city_other_name VALUES ('Rubcovsk','Altayskiy','R','Rubtsovsk');
INSERT INTO city_other_name VALUES ('San Juan','Guárico','YV','San Juan de Los Morros');
INSERT INTO city_other_name VALUES ('Sumgayit','Azerbaijan','AZ','Sumqayit');
INSERT INTO city_other_name VALUES ('Tombouctou','Tombouctou','RMM','Timbuktu');
INSERT INTO city_other_name VALUES ('Ecatepec','México, Estado de','MEX','Ecatepec de Morelos');
INSERT INTO city_other_name VALUES ('Praha','Praha','CZ','Prague');
INSERT INTO city_other_name VALUES ('Bangkok','Thailand','THA','Khrung Thep');
INSERT INTO city_other_name VALUES ('Maarrat an Numan','Idlib','SYR','Maarat al-Numaan');
INSERT INTO city_other_name VALUES ('Nojabrsk','Yamalo Nenets ao','R','Noyabrsk');
INSERT INTO city_other_name VALUES ('Kazan','Tatarstan','R','Kazan');
INSERT INTO city_other_name VALUES ('Novorossiysk','Krasnodarskiy','R','Novorossijsk');
INSERT INTO city_other_name VALUES ('Al Minya','Egypt','ET','Minya');
INSERT INTO city_other_name VALUES ('Sankt Peterburg','Sankt-Peterburg','R','Saint Petersburg');
INSERT INTO city_other_name VALUES ('Ålborg','Nordjylland','DK','Aalborg');
INSERT INTO city_other_name VALUES ('Melaka','Melaka','MAL','Malacca');
INSERT INTO city_other_name VALUES ('Beer Sheva','HaDarom','IL','Beersheba');
INSERT INTO city_other_name VALUES ('Iraklio','Kritis','GR','Irakleio');
INSERT INTO city_other_name VALUES ('Bijsk','Altayskiy','R','Biysk');
INSERT INTO city_other_name VALUES ('Emfuleni','Gauteng','RSA','Vanderbijlpark');
INSERT INTO city_other_name VALUES ('Brugge','West-Vlaanderen','B','Bruges');
INSERT INTO city_other_name VALUES ('Århus','Midtjylland','DK','Aarhus');
INSERT INTO city_other_name VALUES ('Al Ladhiqiyah','Al Ladhiqiyah','SYR','Latakia');
INSERT INTO city_other_name VALUES ('San Salvador de Jujuy','Jujuy','RA','Jujuy');
INSERT INTO city_other_name VALUES ('Semei','East-Kazakhstan','KZ','Semey');
INSERT INTO city_other_name VALUES ('Kozhikode','Kerala','IND','Calicut');
INSERT INTO city_other_name VALUES ('Taldykurgan','Almaty','KZ','Taldykorgan');
INSERT INTO city_other_name VALUES ('Rawalpindi','Punjab','PK','Rāwalpindi');
INSERT INTO city_other_name VALUES ('Južno-Sachalinsk','Sakhalin','R','Yuzhno Sakhalinsk');
INSERT INTO city_other_name VALUES ('Siguatepeque','Francisco Morazán','HN','Siquatepeque');
INSERT INTO city_other_name VALUES ('Tanjung Pinang','Kepulauan Riau','RI','Tanjungpinang');
INSERT INTO city_other_name VALUES ('al Hudaydah','Yemen','YE','Al Hudaydah');
INSERT INTO city_other_name VALUES ('Hyderabad','Sindh','PK','Hyderābād');
INSERT INTO city_other_name VALUES ('Khartoum North','Al-Kharṭūm','SUD','Al Chartum Bahri');
INSERT INTO city_other_name VALUES ('Makhachkala','Dagestan','R','Machačkala');
INSERT INTO city_other_name VALUES ('Al Mansurah','Egypt','ET','Mansoura');
INSERT INTO city_other_name VALUES ('Al Ismailiyah','Egypt','ET','Ismaïlia');
INSERT INTO city_other_name VALUES ('Den Haag','Zuid-Holland','NL','''s-Gravenhage');
INSERT INTO city_other_name VALUES ('Xiamen','Fujian','CN','Amoy');
INSERT INTO city_other_name VALUES ('Khujand','Sughd','TJ','Chudschand');
INSERT INTO city_other_name VALUES ('Newcastle upon Tyne','North East','GB','Newcastle');
INSERT INTO city_other_name VALUES ('Hubli','Karnataka','IND','Hubballi');
INSERT INTO city_other_name VALUES ('Santiago','Dominican Republic','DOM','Santiago de los Caballeros');
INSERT INTO city_other_name VALUES ('Ilesha','Osun','NGR','Ilesa');
INSERT INTO city_other_name VALUES ('Aqtobe','Aktobe','KZ','Aktobe');
INSERT INTO city_other_name VALUES ('Sfintu Gheorghe','Covasna','RO','Sfântu Gheorghe');
INSERT INTO city_other_name VALUES ('Nachodka','Primorskiy','R','Nakhodka');
INSERT INTO city_other_name VALUES ('Kalemi','Tanganyika','CGO','Kalemie');
INSERT INTO city_other_name VALUES ('Cuautla Morelos','Morelos','MEX','Cuautla');
INSERT INTO city_other_name VALUES ('Velikij Novgorod','Novgorodskaya','R','Veliky Novgorod');
INSERT INTO city_other_name VALUES ('Muscat','Oman','OM','Maskat');
INSERT INTO city_other_name VALUES ('Lexington','Kentucky','USA','Lexington Fayette');
INSERT INTO city_other_name VALUES ('Duma','Rif Dimashq','SYR','Douma');
INSERT INTO city_other_name VALUES ('Sion','Valais','CH','Sitten');
INSERT INTO city_other_name VALUES ('Urganch','Xorazm','UZ','Urgench');
INSERT INTO city_other_name VALUES ('Qina','Egypt','ET','Qena');
INSERT INTO city_other_name VALUES ('Busan','South Korea','ROK','Pusan');
INSERT INTO city_other_name VALUES ('Sergijev Posad','Moskovskaya','R','Sergiyev Posad');
INSERT INTO city_other_name VALUES ('Bucureşti','Bucureşti','RO','Bucharest');
INSERT INTO city_other_name VALUES ('Khabarovsk','Khabarovskiy','R','Chabarovsk');
INSERT INTO city_other_name VALUES ('Pasto','Nariño','CO','San Juan de Pasto');
INSERT INTO city_other_name VALUES ('Tel Aviv-Yafo','Tel Aviv','IL','Jaffa');
INSERT INTO city_other_name VALUES ('General Santos','Soccsksargen','RP','Dadiangas');
INSERT INTO city_other_name VALUES ('Génova','Liguria','I','Genoa');
INSERT INTO city_other_name VALUES ('Kulyab','Khatlon','TJ','Kulob');
INSERT INTO city_other_name VALUES ('Orechovo-Zujevo','Moskovskaya','R','Orekhovo Zuyevo');
INSERT INTO city_other_name VALUES ('Marsa Matruh','Egypt','ET','Mersa Matruh');
INSERT INTO city_other_name VALUES ('Kingston upon Hull','Yorkshire and the Humber','GB','Hull');
INSERT INTO city_other_name VALUES ('Halab','Halab','SYR','Aleppo');
INSERT INTO city_other_name VALUES ('Sittwe','Rakhine','MYA','Akyab');
INSERT INTO city_other_name VALUES ('Halab','Halab','SYR','Haleb');
INSERT INTO city_other_name VALUES ('Nürnberg','Bayern','D','Nuremberg');
INSERT INTO city_other_name VALUES ('Al Mahallah al Kubra','Egypt','ET','El-Mahalla El-Kubra');
INSERT INTO city_other_name VALUES ('Samarqand','Samarqand','UZ','Samarkand');
INSERT INTO city_other_name VALUES ('Batajsk','Rostovskaya','R','Bataisk');
INSERT INTO city_other_name VALUES ('Odesa','Odeska','UA','Odessa');
INSERT INTO city_other_name VALUES ('Wien','Wien','A','Vienna');
INSERT INTO city_other_name VALUES ('Hohhot','Nei Mongol','CN','Huhhot');
INSERT INTO city_other_name VALUES ('Fribourg','Fribourg','CH','Freiburg');
INSERT INTO city_other_name VALUES ('Mytilini','Boreioy Aigaioy','GR','Mytilene');
INSERT INTO city_other_name VALUES ('Buffalo City','Eastern Cape','RSA','East London');
INSERT INTO city_other_name VALUES ('Qui Nhon','North and South Central Coast','VN','Quy Nhơn');
INSERT INTO city_other_name VALUES ('Mytišči','Moskovskaya','R','Mytishchi');
INSERT INTO city_other_name VALUES ('Petah Tiqwa','HaMerkaz','IL','Petah Tikwa');
INSERT INTO city_other_name VALUES ('An Najaf','al-Najaf','IRQ','Najaf');
INSERT INTO city_other_name VALUES ('Rodriguez','Calabarzon','RP','Montalban');
INSERT INTO city_other_name VALUES ('Ha Long','Northern Midlands and Mountains','VN','Hong Gai');
INSERT INTO city_other_name VALUES ('Chita','Zabaykalskiy','R','Čita');
INSERT INTO city_other_name VALUES ('Hospitalet de Llobregat','Catalunya','E','L''Hospitalet de Llobregat');
INSERT INTO city_other_name VALUES ('Al Gedaref','Al-Qaḍārif','SUD','Al Qadarif');
INSERT INTO city_other_name VALUES ('Cusco','Cusco','PE','Cuzco');
INSERT INTO city_other_name VALUES ('Venézia','Veneto','I','Venice');
INSERT INTO city_other_name VALUES ('Al Qamishl','Al Hasakah','SYR','Qamishli');
INSERT INTO city_other_name VALUES ('Biel','Bern','CH','Bienne');
INSERT INTO city_other_name VALUES ('Ačinsk','Krasnoyarsk','R','Achinsk');
INSERT INTO city_other_name VALUES ('Santiago','Veraguas','PA','Santiago de Veraguas');
INSERT INTO city_other_name VALUES ('Korolëv','Moskovskaya','R','Korolyov');
INSERT INTO city_other_name VALUES ('Hannover','Niedersachsen','D','Hanover');
INSERT INTO city_other_name VALUES ('Tolyatti','Samarskaya','R','Toljatti');
INSERT INTO city_other_name VALUES ('Kocaeli','Kocaeli','TR','Izmit');
INSERT INTO city_other_name VALUES ('Bojnurd','North Khorasan','IR','Bojnourd');
INSERT INTO city_other_name VALUES ('Sutton Coldfield','West Midlands','GB','Sutton');
INSERT INTO city_other_name VALUES ('Sri Jayawardhanapura','Sri Lanka','CL','Sri Jayewardenepura');
INSERT INTO city_other_name VALUES ('Polokwane','Limpopo','RSA','Pietersburg');
INSERT INTO city_other_name VALUES ('Al Qahirah','Egypt','ET','Cairo');
INSERT INTO city_other_name VALUES ('Toshkent','Toshkent City','UZ','Tashkent');
INSERT INTO city_other_name VALUES ('Balkanabat','Balkan','TM','Nebitdag');
INSERT INTO city_other_name VALUES ('As Samawah','al-Muthanna','IRQ','Samawah');
INSERT INTO city_other_name VALUES ('Az Zaqaziq','Egypt','ET','Zagazig');
INSERT INTO city_other_name VALUES ('Kopejsk','Chelyabinskaya','R','Kopeysk');
INSERT INTO city_other_name VALUES ('San Jose Del Monte','Central Luzon','RP','San Jose del Monte');
INSERT INTO city_other_name VALUES ('Dnipro','Dnipropetrovska','UA','Dnipropetrovsk');
INSERT INTO city_other_name VALUES ('Yerushalayim','Yerushalayim','IL','Jerusalem');
INSERT INTO city_other_name VALUES ('Kamensk-Uralskij','Sverdlovskaya','R','Kamensk Uralsky');
INSERT INTO city_other_name VALUES ('Marg‘ilon','Fargʻona','UZ','Margilan');
INSERT INTO city_other_name VALUES ('Kharkiv','Kharkivska','UA','Kharkov');
INSERT INTO city_other_name VALUES ('Hamedan','Hamedan','IR','Hamadan');
INSERT INTO city_other_name VALUES ('eThekwini','KwaZulu-Natal','RSA','Durban');
INSERT INTO city_other_name VALUES ('Zamora de Hidalgo','Michoacán','MEX','Zamora');
INSERT INTO city_other_name VALUES ('Žukovskij','Moskovskaya','R','Zhukovskij');
INSERT INTO city_other_name VALUES ('Mardan','Khyber Pakhtunkhwa','PK','Mardān');
INSERT INTO city_other_name VALUES ('Genève','Genève','CH','Genf');
INSERT INTO city_other_name VALUES ('Ardebil','Ardebil','IR','Ardabil');
INSERT INTO city_other_name VALUES ('Gwangju','South Korea','ROK','Kwangju');
INSERT INTO city_other_name VALUES ('Astrakhan','Astrakhanskaya','R','Astrachan');
INSERT INTO city_other_name VALUES ('Kamyšin','Volgogradskaya','R','Kamyshin');
INSERT INTO city_other_name VALUES ('Balkhash','Karaganda','KZ','Balqash');
INSERT INTO city_other_name VALUES ('Buxoro','Buxoro','UZ','Bukhara');
INSERT INTO city_other_name VALUES ('Tougourt','Algeria','DZ','Touggourt');
INSERT INTO city_other_name VALUES ('Pachuca','Hidalgo','MEX','Pachuca de Soto');
INSERT INTO city_other_name VALUES ('Lapu-Lapu','Central Visayas','RP','Opon');
INSERT INTO city_other_name VALUES ('Basseterre','Saint Kitts and Nevis','KN','Basse Terre');
INSERT INTO city_other_name VALUES ('Alicante','Valenciana','E','Alacant');
INSERT INTO city_other_name VALUES ('Freiburg','Baden-Württemberg','D','Freiburg im Breisgau');
INSERT INTO city_other_name VALUES ('Yekaterinburg','Sverdlovskaya','R','Jekaterinburg');
INSERT INTO city_other_name VALUES ('Ogbomosho','Oyo','NGR','Ogbomoso');
INSERT INTO city_other_name VALUES ('Naucalpan','México, Estado de','MEX','Naucalpan de Juarez');
INSERT INTO city_other_name VALUES ('Nizhny Tagil','Sverdlovskaya','R','Nižnij Tagil');
INSERT INTO city_other_name VALUES ('Torino','Piemonte','I','Turin');
INSERT INTO city_other_name VALUES ('Gujranwala','Punjab','PK','Gujrānwāla');
INSERT INTO city_other_name VALUES ('Jerez de la Frontera','Andalucía','E','Jerez');
INSERT INTO city_other_name VALUES ('Göteborg','Västra Götaland','S','Gothenburg');
INSERT INTO city_other_name VALUES ('An Nasiriyah','Thi Qar','IRQ','Nasiriyah');
INSERT INTO city_other_name VALUES ('Vadsø','Finnmark','N','Vadsoe');
INSERT INTO city_other_name VALUES ('Mons','Hainaut','B','Bergen');
INSERT INTO city_other_name VALUES ('Sevilla','Andalucía','E','Seville');
INSERT INTO city_other_name VALUES ('Nur-Sultan','Astana','KZ','Astana');
INSERT INTO city_other_name VALUES ('Ščëlkovo','Moskovskaya','R','Shchyolkovo');
INSERT INTO city_other_name VALUES ('Daejeon','South Korea','ROK','Taejon');
INSERT INTO city_other_name VALUES ('Frankfurt','Hessen','D','Frankfurt am Main');
INSERT INTO city_other_name VALUES ('Hagåtña','Guam','GUAM','Agana');
INSERT INTO city_other_name VALUES ('Rostov-na-Donu','Rostovskaya','R','Rostov');
INSERT INTO city_other_name VALUES ('Esfahan','Esfahan','IR','Isfahan');
INSERT INTO city_other_name VALUES ('N''Zérékoré','Guinea','RG','Nzérékoré');
INSERT INTO city_other_name VALUES ('Ulaanbaatar','Mongolia','MNG','Ulan Bator');
INSERT INTO city_other_name VALUES ('Köln','Nordrhein-Westfalen','D','Cologne');
INSERT INTO city_other_name VALUES ('Larnaka','Cyprus','CY','Larnaca');
INSERT INTO city_other_name VALUES ('Makassar','Sulawesi Selatan','RI','Ujung Pandang');
INSERT INTO city_other_name VALUES ('El Djelfa','Algeria','DZ','Djelfa');
INSERT INTO city_other_name VALUES ('Nur-Sultan','Astana','KZ','Aqmola');
INSERT INTO city_other_name VALUES ('Čerkessk','Karachayevo-Cherkesskaya','R','Cherkessk');
INSERT INTO city_other_name VALUES ('Krasnoyarsk','Krasnoyarsk','R','Krasnojarsk');
INSERT INTO city_other_name VALUES ('Patra','Dytikis Elladas','GR','Patras');
INSERT INTO city_other_name VALUES ('Roma','Lazio','I','Rome');
INSERT INTO city_other_name VALUES ('Velikij Novgorod','Novgorodskaya','R','Novgorod');
INSERT INTO city_other_name VALUES ('Al Kuwayt','Kuwait','KWT','Kuwait City');
INSERT INTO city_other_name VALUES ('Larkana','Sindh','PK','Lārkāna');
INSERT INTO city_other_name VALUES ('Jeju','South Korea','ROK','Cheju');
INSERT INTO city_other_name VALUES ('Biñan','Calabarzon','RP','Biniang');
INSERT INTO city_other_name VALUES ('Copenhagen','Hovedstaden','DK','København');
INSERT INTO city_other_name VALUES ('Rahimyar Khan','Punjab','PK','Rahīmyār Khān');
INSERT INTO city_other_name VALUES ('Evora','Evora','P','Évora');
INSERT INTO city_other_name VALUES ('Nawabshah','Sindh','PK','Nawābshāh');
INSERT INTO city_other_name VALUES ('Al Khalil','West Bank','WB','Hebron');
INSERT INTO city_other_name VALUES ('Al Gazira','Al-Jazīrah','SUD','Wad Madani');
INSERT INTO city_other_name VALUES ('Tlalnepantla','México, Estado de','MEX','Tlalnepantla de Baz');
INSERT INTO city_other_name VALUES ('Suhaj','Egypt','ET','Sohag');
INSERT INTO city_other_name VALUES ('Puškino','Moskovskaya','R','Pushkino');
INSERT INTO city_other_name VALUES ('Termiz','Surkhandarya','UZ','Termez');
INSERT INTO city_other_name VALUES ('Nizhnii Novgorod','Nizhnii Novgorodskaya','R','Nizhny Novgorod');
INSERT INTO city_other_name VALUES ('Yangon','Yangon','MYA','Rangoon');
INSERT INTO city_other_name VALUES ('Islamabad','FCT Islamabad','PK','Islāmābād');
INSERT INTO city_other_name VALUES ('Balašicha','Moskovskaya','R','Balashikha');
INSERT INTO city_other_name VALUES ('Schaerbeek','Bruxelles','B','Schaarbeek');
INSERT INTO city_other_name VALUES ('Kasur','Punjab','PK','Kasūr');
INSERT INTO city_other_name VALUES ('Khoy','West Azarbayejan','IR','Khvoy');
INSERT INTO city_other_name VALUES ('Mawlamyine','Mon','MYA','Mawlamyaing');
INSERT INTO city_other_name VALUES ('Orel','Orlovskaya','R','Orël');
INSERT INTO city_other_name VALUES ('Bien Hoa','Southeast','VN','Bien Hoa City');
INSERT INTO city_other_name VALUES ('Xuzhou','Jiangsu','CN','Jiangsu');
INSERT INTO city_other_name VALUES ('Öskemen','East-Kazakhstan','KZ','Ust-Kamenogorsk');
INSERT INTO city_other_name VALUES ('Gonbad-e-Kavus','Golestan','IR','Gonbad e Kavous');
INSERT INTO city_other_name VALUES ('Santa Cruz de la Sierra','Santa Cruz','BOL','Santa Cruz');
INSERT INTO city_other_name VALUES ('Sholapur','Maharashtra','IND','Solapur');
INSERT INTO city_other_name VALUES ('Duhouk','Duhouk','IRQ','Dahuk');
INSERT INTO city_other_name VALUES ('Sochi','Krasnodarskiy','R','Soči');
INSERT INTO city_other_name VALUES ('Sinpho','North Korea','KP','Sinpo');
INSERT INTO city_other_name VALUES ('As Seeb','Oman','OM','As Sib');
INSERT INTO city_other_name VALUES ('Železnodorožnyj','Moskovskaya','R','Zheleznodorozhny');
INSERT INTO city_other_name VALUES ('Georgetown','Pulau Pinang','MAL','Penang');
INSERT INTO city_other_name VALUES ('Roatan','Islas de la Bahía','HN','Coxen Hole');
INSERT INTO city_other_name VALUES ('Chalkida','Stereas Elladas','GR','Chalcis');
INSERT INTO city_other_name VALUES ('Rostov-na-Donu','Rostovskaya','R','Rostov on Don');
INSERT INTO city_other_name VALUES ('Ludwigshafen','Rheinland-Pfalz','D','Ludwigshafen am Rhein');
INSERT INTO city_other_name VALUES ('Pádova','Veneto','I','Padua');
INSERT INTO city_other_name VALUES ('Massaua','Eritrea','ER','Mitsiwa');
INSERT INTO city_other_name VALUES ('Ryazan','Ryazanskaya','R','Rjazan');
INSERT INTO city_other_name VALUES ('Bhisho','Eastern Cape','RSA','Bisho');
INSERT INTO city_other_name VALUES ('Inirida','Guainía','CO','Puerto Inirida');
INSERT INTO city_other_name VALUES ('Orel','Orlovskaya','R','Oryol');
INSERT INTO city_other_name VALUES ('Mangaung','Free State','RSA','Bloemfontein');
INSERT INTO city_other_name VALUES ('Shubra al Khimah','Egypt','ET','Shubra El-Kheima');
INSERT INTO city_other_name VALUES ('Novošachtinsk','Rostovskaya','R','Novoshakhtinsk');
INSERT INTO city_other_name VALUES ('Al Basrah','Basrah','IRQ','Basrah');
INSERT INTO city_other_name VALUES ('Kuching Utara','Sarawak','MAL','Kuching');
INSERT INTO city_other_name VALUES ('Taizz','Yemen','YE','Taiz');
INSERT INTO city_other_name VALUES ('Al Manāmah','Bahrain','BRN','Manama');
INSERT INTO city_other_name VALUES ('Kashgar','Xinjiang','CN','Kaxgar');
INSERT INTO city_other_name VALUES ('Neuchatel','Neuchâtel','CH','Neuenburg');
INSERT INTO city_other_name VALUES ('Peiraias','Attikis','GR','Piräus');
INSERT INTO city_other_name VALUES ('Veracruz','Veracruz','MEX','Veracruz Llave');
INSERT INTO city_other_name VALUES ('As Suways','Egypt','ET','Suez');
INSERT INTO city_other_name VALUES ('Aḍ-Ḍuayn','Sharq Dārfūr','SUD','Ad Duain');
INSERT INTO city_other_name VALUES ('Zaporizhzhia','Zaporizka','UA','Zaporizhia');
INSERT INTO city_other_name VALUES ('Okara','Punjab','PK','Okāra');
INSERT INTO city_other_name VALUES ('Fès','Fes Boulemane','MA','Fez');
INSERT INTO city_other_name VALUES ('Blagoveščensk','Amurskaya','R','Blagoveshchensk');
INSERT INTO city_other_name VALUES ('At Taif','Makkah Al-Mokarramah','SA','Taif');
INSERT INTO city_other_name VALUES ('Dayr az Zawr','Dayr az Zawr','SYR','Deir ez-Zor');
INSERT INTO city_other_name VALUES ('San Fernando','Apure','YV','San Fernando de Apure');
INSERT INTO city_other_name VALUES ('Staryj Oskol','Belgorodskaya','R','Stary Oskol');
INSERT INTO city_other_name VALUES ('Dashhowuz','Dashhowuz','TM','Tashauz');
INSERT INTO city_other_name VALUES ('Kūstī','An-Nīl al-Abyaḍ','SUD','Kosti');
INSERT INTO city_other_name VALUES ('Antwerpen','Antwerpen','B','Anvers');
INSERT INTO city_other_name VALUES ('Majunga','Madagascar','RM','Mahajanga');
INSERT INTO city_other_name VALUES ('Xiangyang','Hubei','CN','Xiangfan');
INSERT INTO city_other_name VALUES ('Jelec','Lipetskaya','R','Yelets');
INSERT INTO city_other_name VALUES ('Bangalore','Karnataka','IND','Bengaluru');
INSERT INTO city_other_name VALUES ('San Pablo','México, Estado de','MEX','San Pablo de las Salinas');
INSERT INTO city_other_name VALUES ('Elche','Valenciana','E','Elx');
INSERT INTO city_other_name VALUES ('Naberezhnye Tchelny','Tatarstan','R','Naberezhnye Chelny');
INSERT INTO city_other_name VALUES ('Girón','Santander','CO','San Juan de Girón');
INSERT INTO city_other_name VALUES ('Saint George''s','Grenada','WG','St. George''s');
INSERT INTO city_other_name VALUES ('Hamah','Hamah','SYR','Hama');
INSERT INTO city_other_name VALUES ('Neyshabur','Khorasan-e-Razavi','IR','Nishapur');
INSERT INTO city_other_name VALUES ('Koksetau','Akmola','KZ','Kokshetau');
INSERT INTO city_other_name VALUES ('Al Mawsil','Nineveh','IRQ','Mosul');
INSERT INTO city_other_name VALUES ('Kigoma-Ujiji','Kigoma','EAT','Kigoma');
INSERT INTO city_other_name VALUES ('Kerbela','Kerbela','IRQ','Karbala');
INSERT INTO city_other_name VALUES ('Firenze','Toscana','I','Florence');
INSERT INTO city_other_name VALUES ('Lipetsk','Lipetskaya','R','Lipeck');
INSERT INTO city_other_name VALUES ('Bojnurd','North Khorasan','IR','Bojnord');
INSERT INTO city_other_name VALUES ('Al Uqsur','Egypt','ET','Luxor');
INSERT INTO city_other_name VALUES ('Helsingør','Hovedstaden','DK','Helsingör');
INSERT INTO city_other_name VALUES ('Tamatave','Madagascar','RM','Toamasina');
INSERT INTO city_other_name VALUES ('Ar Ramadi','al-Anbar','IRQ','Ramadi');
INSERT INTO city_other_name VALUES ('Bruxelles','Bruxelles','B','Brussel');
INSERT INTO city_other_name VALUES ('Petah Tiqwa','HaMerkaz','IL','Petah Tikva');
INSERT INTO city_other_name VALUES ('Ciudad Juárez','Chihuahua','MEX','Juárez');
INSERT INTO city_other_name VALUES ('Chalkida','Stereas Elladas','GR','Chalkis');
INSERT INTO city_other_name VALUES ('Gent','Oost-Vlaanderen','B','Ghent');
INSERT INTO city_other_name VALUES ('Aysaita','Afar','ETH','Asaita');
INSERT INTO city_other_name VALUES ('Tromsø','Troms','N','Tromsoe');
INSERT INTO city_other_name VALUES ('Jazan','Jazan','SA','Jizan');
INSERT INTO city_other_name VALUES ('Ronne','Hovedstaden','DK','Rønne');
INSERT INTO city_other_name VALUES ('Volzhsky','Volgogradskaya','R','Volžskij');
INSERT INTO city_other_name VALUES ('Donostia','Euskadi','E','San Sebastián');
INSERT INTO city_other_name VALUES ('Bryansk','Bryanskaya','R','Brjansk');
INSERT INTO city_other_name VALUES ('Khomeinishahr','Esfahan','IR','Khomeynishahr');
INSERT INTO city_other_name VALUES ('Roatan','Islas de la Bahía','HN','Coxen Hole (Roatan)');
INSERT INTO city_other_name VALUES ('Oktjabrskij','Bashkortostan','R','Oktyabrsky');
INSERT INTO city_other_name VALUES ('Ech Chelif','Algeria','DZ','Chlef');
INSERT INTO city_other_name VALUES ('San Nicolás de los Garzas','Nuevo Léon','MEX','San Nicolas de los Garza');
INSERT INTO city_other_name VALUES ('Kalookan','Metro Manila','RP','Caloocan');
INSERT INTO city_other_name VALUES ('Warszawa','Mazowieckie','PL','Warsaw');
INSERT INTO city_other_name VALUES ('Jaboatão','Pernambuco','BR','Jaboatao dos Guararapes');
INSERT INTO city_other_name VALUES ('Gambella','Gambella','ETH','Gambela');
INSERT INTO city_other_name VALUES ('München','Bayern','D','Munich');
INSERT INTO city_other_name VALUES ('Aijal','Mizoram','IND','Aizawl');
INSERT INTO city_other_name VALUES ('Dashhowuz','Dashhowuz','TM','Daşoguz');
INSERT INTO city_other_name VALUES ('Dunqulā','Ash-Shamālīyah','SUD','Dongola');
INSERT INTO city_other_name VALUES ('Guigang','Guangxi','CN','Guixian');
INSERT INTO city_other_name VALUES ('Kyïv','Kyïv','UA','Kiev');
INSERT INTO city_other_name VALUES ('Den Haag','Zuid-Holland','NL','The Hague');
INSERT INTO city_other_name VALUES ('Burewala','Punjab','PK','Būrewāla');
INSERT INTO city_other_name VALUES ('Kamoke','Punjab','PK','Kāmoke');
INSERT INTO city_other_name VALUES ('Cagayan De Oro','Northern Mindanao','RP','Cagayan de Oro');
INSERT INTO city_other_name VALUES ('Al Iskandariyah','Egypt','ET','Alexandria');
INSERT INTO city_other_name VALUES ('Sankt Peterburg','Sankt-Peterburg','R','Sankt Petersburg');
INSERT INTO city_other_name VALUES ('Tirana','Albania','AL','Tirane');
INSERT INTO city_other_name VALUES ('Rudniy','Kostanai','KZ','Rudny');
INSERT INTO city_other_name VALUES ('Palma de Mallorca','Illes Balears','E','Palma');
INSERT INTO city_other_name VALUES ('Novokuznetsk','Kemerovskaya','R','Novokuzneck');
INSERT INTO city_other_name VALUES ('Grodno','Grodno','BY','Hrodna');
INSERT INTO city_other_name VALUES ('Khorramabad','Lorestan','IR','Khoram Abad');
INSERT INTO city_other_name VALUES ('Naberezhnye Tchelny','Tatarstan','R','Naberežnyje Čelny');
INSERT INTO city_other_name VALUES ('Tanger','Tanger Tetouan','MA','Tangier');
INSERT INTO city_other_name VALUES ('San Miguel de Tucumán','Tucumán','RA','Tucuman');
INSERT INTO city_other_name VALUES ('Haora','West Bengal','IND','Howrah');
INSERT INTO city_other_name VALUES ('Ostende','West-Vlaanderen','B','Oostende');
INSERT INTO city_other_name VALUES ('Monaco','Monaco','MC','Monaco-Ville');
INSERT INTO city_other_name VALUES ('Komsomolsk-na-Amure','Khabarovskiy','R','Komsomolsk on Amur');
