INSERT INTO country_other_local_name VALUES ('SMAR','Collectivité de Saint-Martin','');
INSERT INTO country_other_local_name VALUES ('MC','la Principauté de Monaco','');
INSERT INTO country_other_local_name VALUES ('PAL','Beluu er a Belau','');
INSERT INTO country_other_local_name VALUES ('PE','Piruw Suyu','');
INSERT INTO country_other_local_name VALUES ('TCH','جمهورية تشاد','');
INSERT INTO country_other_local_name VALUES ('SME','Republiek Suriname (de)','');
INSERT INTO country_other_local_name VALUES ('GH','the Republic of Ghana','');
INSERT INTO country_other_local_name VALUES ('MYA','ပြည်ထောင်စု သမ္မတ မြန်မာနိုင်ငံတော်','Burma');
INSERT INTO country_other_local_name VALUES ('P','República Portuguesa (a)','');
INSERT INTO country_other_local_name VALUES ('BRU','Brunei Darussalam','');
INSERT INTO country_other_local_name VALUES ('RIM','الجمهورية الإسلامية الموريتانية','');
INSERT INTO country_other_local_name VALUES ('CR','la República de Costa Rica','');
INSERT INTO country_other_local_name VALUES ('GQ','la République de Guinée équatoriale','');
INSERT INTO country_other_local_name VALUES ('NMIS','Sankattan Siha Na Islas Mariånas','');
INSERT INTO country_other_local_name VALUES ('A','Republik Österreich (die)','');
INSERT INTO country_other_local_name VALUES ('GUY','the Republic of Guyana','');
INSERT INTO country_other_local_name VALUES ('COM','اتحاد جزر القمر','');
INSERT INTO country_other_local_name VALUES ('N','Norge','');
INSERT INTO country_other_local_name VALUES ('BHT','འབྲུག་གྷལ་ཁབ','');
INSERT INTO country_other_local_name VALUES ('NGR','the Federal Republic of Nigeria','');
INSERT INTO country_other_local_name VALUES ('PY','Paraguay Retãn','');
INSERT INTO country_other_local_name VALUES ('V','Status Civitatis Vaticanae','');
INSERT INTO country_other_local_name VALUES ('YE','الجمهورية اليمنية','');
INSERT INTO country_other_local_name VALUES ('TT','the Republic of Trinidad and Tobago','');
INSERT INTO country_other_local_name VALUES ('ET','جمهورية مصر العربية','');
INSERT INTO country_other_local_name VALUES ('GB','the United Kingdom of Great Britain and Northern Ireland','');
INSERT INTO country_other_local_name VALUES ('RN','la République du Niger','');
INSERT INTO country_other_local_name VALUES ('CI','la République de Côte d''Ivoire','');
INSERT INTO country_other_local_name VALUES ('SOL','Solomon Islands','');
INSERT INTO country_other_local_name VALUES ('WS','Malo Saʻoloto Tutoʻatasi o Sāmoa','');
INSERT INTO country_other_local_name VALUES ('AFG','جُمْهُورِئ إِسْلامِئ أَفْغَانِسْتَان','');
INSERT INTO country_other_local_name VALUES ('AG','Antigua and Barbuda','');
INSERT INTO country_other_local_name VALUES ('MOC','República de Moçambique (a)','');
INSERT INTO country_other_local_name VALUES ('BEN','la République du Bénin','');
INSERT INTO country_other_local_name VALUES ('KN','Saint Kitts and Nevis','');
INSERT INTO country_other_local_name VALUES ('Q','دولة قطر','');
INSERT INTO country_other_local_name VALUES ('LT','Lietuvos Respublika','');
INSERT INTO country_other_local_name VALUES ('CO','la República de Colombia','');
INSERT INTO country_other_local_name VALUES ('GBG','the Bailiwick of Guernsey','');
INSERT INTO country_other_local_name VALUES ('MH','The Republic of the Marshall Islands','');
INSERT INTO country_other_local_name VALUES ('NIUE','Niuē','');
INSERT INTO country_other_local_name VALUES ('BF','le Burkina Faso','');
INSERT INTO country_other_local_name VALUES ('CAM','the Republic of Cameroon','');
INSERT INTO country_other_local_name VALUES ('HR','Republika Hrvatska','');
INSERT INTO country_other_local_name VALUES ('IRL','Ireland','');
INSERT INTO country_other_local_name VALUES ('SGP','新加坡共和国','');
INSERT INTO country_other_local_name VALUES ('MAL','Malaysia','');
INSERT INTO country_other_local_name VALUES ('RMM','la République du Mali','');
INSERT INTO country_other_local_name VALUES ('BD','গণপ্রজাতন্ত্রী বাংলাদেশ','');
INSERT INTO country_other_local_name VALUES ('HN','la República de Honduras','');
INSERT INTO country_other_local_name VALUES ('RB','the Republic of Botswana','');
INSERT INTO country_other_local_name VALUES ('DK','Kongeriget Danmark','');
INSERT INTO country_other_local_name VALUES ('RH','la République d'' Haïti','');
INSERT INTO country_other_local_name VALUES ('WB','الضفة الغربية','');
INSERT INTO country_other_local_name VALUES ('D','Bundesrepublik Deutschland (die)','');
INSERT INTO country_other_local_name VALUES ('CL','ශ්‍රී ලංකා ප්‍රජාතාන්ත්‍රික සමාජවාදී ජනරජය','');
INSERT INTO country_other_local_name VALUES ('SA','المملكةة','');
INSERT INTO country_other_local_name VALUES ('MA','المملكة المغربية','');
INSERT INTO country_other_local_name VALUES ('TR','Türkiye Cumhuriyeti','');
INSERT INTO country_other_local_name VALUES ('ROK','대한 민국','');
INSERT INTO country_other_local_name VALUES ('TM','Türkmenistan','');
INSERT INTO country_other_local_name VALUES ('SF','Suomen tasavalta','');
INSERT INTO country_other_local_name VALUES ('SUD','جمهورية السودان','');
INSERT INTO country_other_local_name VALUES ('MW','Dziko la Malaŵi','');
INSERT INTO country_other_local_name VALUES ('AL','Shqipëri','');
INSERT INTO country_other_local_name VALUES ('EAK','the Republic of Kenya','');
INSERT INTO country_other_local_name VALUES ('KIR','the Republic of Kiribati','');
INSERT INTO country_other_local_name VALUES ('SK','Slovensko','');
INSERT INTO country_other_local_name VALUES ('EAT','Jamhuri ya Muungano wa Tanzania','');
INSERT INTO country_other_local_name VALUES ('I','Repubblica Italiana (la)','');
INSERT INTO country_other_local_name VALUES ('KP','조선 민주주의 인민 공화국','');
INSERT INTO country_other_local_name VALUES ('SY','Repiblik Sesel','');
INSERT INTO country_other_local_name VALUES ('CZ','Česko','Czechia');
INSERT INTO country_other_local_name VALUES ('BY','Рэспубліка Беларусь','');
INSERT INTO country_other_local_name VALUES ('HK','香港','');
INSERT INTO country_other_local_name VALUES ('WG','Grenada','');
INSERT INTO country_other_local_name VALUES ('CV','República de Cabo Verde (a)','');
INSERT INTO country_other_local_name VALUES ('UZ','Oʻzbekiston','');
INSERT INTO country_other_local_name VALUES ('LAR','لِيبِيَا','');
INSERT INTO country_other_local_name VALUES ('J','日本','');
INSERT INTO country_other_local_name VALUES ('NL','Koninkrijk der Nederlanden (het)','');
INSERT INTO country_other_local_name VALUES ('AUS','Australia','');
INSERT INTO country_other_local_name VALUES ('WL','Saint Lucia','');
INSERT INTO country_other_local_name VALUES ('BIH','Bosna i Hercegovina','');
INSERT INTO country_other_local_name VALUES ('NZ','New Zealand','');
INSERT INTO country_other_local_name VALUES ('GBM','the Isle of Man','');
INSERT INTO country_other_local_name VALUES ('SLE','the Republic of Sierra Leone','');
INSERT INTO country_other_local_name VALUES ('RO','România','');
INSERT INTO country_other_local_name VALUES ('SRB','Република Србија','');
INSERT INTO country_other_local_name VALUES ('WSA','الصحراء الغربية','');
INSERT INTO country_other_local_name VALUES ('BI','la République du Burundi','');
INSERT INTO country_other_local_name VALUES ('R','Россия','');
INSERT INTO country_other_local_name VALUES ('AZ','Azǝrbaycan Respublikası','');
INSERT INTO country_other_local_name VALUES ('THA','ราชอาณาจักรไทย','');
INSERT INTO country_other_local_name VALUES ('TO','the Kingdom of Tonga','');
INSERT INTO country_other_local_name VALUES ('BG','Република България','');
INSERT INTO country_other_local_name VALUES ('FO','Føroyar','');
INSERT INTO country_other_local_name VALUES ('WV','Saint Vincent and the Grenadines','');
INSERT INTO country_other_local_name VALUES ('KZ','Қазақстан Республикасы','');
INSERT INTO country_other_local_name VALUES ('SX','Sint Maarten','');
INSERT INTO country_other_local_name VALUES ('RCB','la République du Congo','');
INSERT INTO country_other_local_name VALUES ('MACX','澳門','');
INSERT INTO country_other_local_name VALUES ('CUR','Land Curaçao','');
INSERT INTO country_other_local_name VALUES ('SSD','the Republic of South Sudan','');
INSERT INTO country_other_local_name VALUES ('RL','الجمهورية','');
INSERT INTO country_other_local_name VALUES ('GL','Kalaallit Nunaat','');
INSERT INTO country_other_local_name VALUES ('SLO','Republika Slovenija','');
INSERT INTO country_other_local_name VALUES ('WD','the Commonwealth of Dominica','');
INSERT INTO country_other_local_name VALUES ('IND','the Republic of India','');
INSERT INTO country_other_local_name VALUES ('BDS','Barbados','');
INSERT INTO country_other_local_name VALUES ('RM','la République de Madagascar','');
INSERT INTO country_other_local_name VALUES ('MD','Republica Moldova','');
INSERT INTO country_other_local_name VALUES ('IR','جُمْهُورِئ إِسْلامِئ إِيرَان','');
INSERT INTO country_other_local_name VALUES ('GR','Ελληνική Δημοκρατία','');
INSERT INTO country_other_local_name VALUES ('KOS','Republika e Kosovës','');
INSERT INTO country_other_local_name VALUES ('UAE','الإمارات العربية المتحدة','');
INSERT INTO country_other_local_name VALUES ('GBJ','the Bailiwick of Jersey','');
INSERT INTO country_other_local_name VALUES ('FPOL','Pōrīnetia Farāni','');
INSERT INTO country_other_local_name VALUES ('E','el Reino de España','');
INSERT INTO country_other_local_name VALUES ('MK','Република Cеверна Македонија','');
INSERT INTO country_other_local_name VALUES ('VN','Việt Nam','');
INSERT INTO country_other_local_name VALUES ('DJI','جمهورية جيبوتي','');
INSERT INTO country_other_local_name VALUES ('LS','the Kingdom of Lesotho','');
INSERT INTO country_other_local_name VALUES ('H','Magyar Köztársaság (a)','');
INSERT INTO country_other_local_name VALUES ('IRQ','جمهورية العراق','');
INSERT INTO country_other_local_name VALUES ('GUB','República da Guiné-Bissau (a)','');
INSERT INTO country_other_local_name VALUES ('PL','Rzeczpospolita Polska','');
INSERT INTO country_other_local_name VALUES ('TN','الجمهورية التونسية','');
INSERT INTO country_other_local_name VALUES ('UA','Украïна','');
INSERT INTO country_other_local_name VALUES ('ARM','Հայաստանի Հանրապետություն','');
INSERT INTO country_other_local_name VALUES ('MS','The Republic of Mauritius','');
INSERT INTO country_other_local_name VALUES ('IL','دولة إسرائيل','');
INSERT INTO country_other_local_name VALUES ('RSA','Republiek van Suid-Afrika','');
INSERT INTO country_other_local_name VALUES ('EST','Eesti Vabariik','');
INSERT INTO country_other_local_name VALUES ('G','la République Gabonaise','');
INSERT INTO country_other_local_name VALUES ('CGO','la République démocratique du Congo','');
INSERT INTO country_other_local_name VALUES ('CY','Κυπριακή Δημοκρατία','');
INSERT INTO country_other_local_name VALUES ('L','le Grand-Duché de Luxembourg','');
INSERT INTO country_other_local_name VALUES ('KG','Кыргыз Республикасы','');
INSERT INTO country_other_local_name VALUES ('MV','ދިވެހިރާއްޖޭގެ ޖުމުހޫރިއްޔާ','');
INSERT INTO country_other_local_name VALUES ('TOK','Tokelau','');
INSERT INTO country_other_local_name VALUES ('KWT','دولة الكويت','');
INSERT INTO country_other_local_name VALUES ('SYR','الجمهورية العربية السورية','');
INSERT INTO country_other_local_name VALUES ('GE','საქართველო','');
INSERT INTO country_other_local_name VALUES ('GAZA','قطاع غزّة','');
INSERT INTO country_other_local_name VALUES ('TUV','Tuvalu','');
INSERT INTO country_other_local_name VALUES ('FL','Fürstentum Liechtenstein (das)','');
INSERT INTO country_other_local_name VALUES ('JA','Jamaica','');
INSERT INTO country_other_local_name VALUES ('STP','República Democrática de São Tomé e Príncipe (a)','');
INSERT INTO country_other_local_name VALUES ('M','the Republic of Malta','');
INSERT INTO country_other_local_name VALUES ('TL','República Democrática de Timor-Leste','');
INSERT INTO country_other_local_name VALUES ('NAM','the Republic of Namibia','');
INSERT INTO country_other_local_name VALUES ('CDN','Canada','');
INSERT INTO country_other_local_name VALUES ('JOR','المملكة الأردنية الهاشمية','');
INSERT INTO country_other_local_name VALUES ('AND','Principat d''Andorra','');
INSERT INTO country_other_local_name VALUES ('NAU','the Republic of Nauru','');
INSERT INTO country_other_local_name VALUES ('SVA','Svalbard','');
INSERT INTO country_other_local_name VALUES ('BOL','Estado Plurinacional de Bolivia (el)','');
INSERT INTO country_other_local_name VALUES ('RG','la République de Guinée','');
INSERT INTO country_other_local_name VALUES ('WAG','The Republic of the Gambia','');
INSERT INTO country_other_local_name VALUES ('SD','Kingdom of Eswatini','Swaziland');
INSERT INTO country_other_local_name VALUES ('SO','جُمْهُورِيَّة الصُّومَال','');
INSERT INTO country_other_local_name VALUES ('LAO','ສາທາລະນະລັດປະຊາທິປະໄຕປະຊາຊົນລາວ','');
INSERT INTO country_other_local_name VALUES ('LV','Latvijas Republika','');
INSERT INTO country_other_local_name VALUES ('ROU','la República Oriental del Uruguay','');
INSERT INTO country_other_local_name VALUES ('RWA','the Republic of Rwanda','');
INSERT INTO country_other_local_name VALUES ('RCA','la République centrafricaine','');
INSERT INTO country_other_local_name VALUES ('WF','Uvea mo Futuna','');
INSERT INTO country_other_local_name VALUES ('RSM','Repubblica di San Marino (la)','');
INSERT INTO country_other_local_name VALUES ('GCA','República de Guatemala (la)','');
INSERT INTO country_other_local_name VALUES ('LB','the Republic of Liberia','');
INSERT INTO country_other_local_name VALUES ('NEP','संघीय लोकतान्त्रिक गणतन्त्र नेपाल','');
INSERT INTO country_other_local_name VALUES ('DZ','الجزائر','');
INSERT INTO country_other_local_name VALUES ('RI','Republik Indonesia','');
INSERT INTO country_other_local_name VALUES ('FJI','the Republic of the Fiji Islands','');
INSERT INTO country_other_local_name VALUES ('ER','إريتريا','');
INSERT INTO country_other_local_name VALUES ('MNE','Црна Гора','');
INSERT INTO country_other_local_name VALUES ('ES','la República de El Salvador','');
INSERT INTO country_other_local_name VALUES ('B','Koninkrijk België (het)','');
INSERT INTO country_other_local_name VALUES ('PK','the Islamic Republic of Pakistan','');
INSERT INTO country_other_local_name VALUES ('COOK','Cook Islands','');
INSERT INTO country_other_local_name VALUES ('MNG','Монгол улс','');
INSERT INTO country_other_local_name VALUES ('RP','the Republic of the Philippines','');
INSERT INTO country_other_local_name VALUES ('RC','中華民國','');
INSERT INTO country_other_local_name VALUES ('BRN','البحرين','');
INSERT INTO country_other_local_name VALUES ('CN','中國','');
INSERT INTO country_other_local_name VALUES ('IS','Lýðveldið Ísland','');
INSERT INTO country_other_local_name VALUES ('FSM','the Federated States of Micronesia','');
INSERT INTO country_other_local_name VALUES ('ARU','Aruba','');
INSERT INTO country_other_local_name VALUES ('PNG','Papua New Guinea','');
INSERT INTO country_other_local_name VALUES ('ETH','የኢትዮጵያ ፈደራላዊ ዲሞክራሲያዊ ሪፐብሊክ','');
INSERT INTO country_other_local_name VALUES ('F','la République française','');
INSERT INTO country_other_local_name VALUES ('K','ព្រះរាជាណាចក្រ កម្ពុជា','');
INSERT INTO country_other_local_name VALUES ('SBAR','Collectivité de Saint-Barthélemy','');
INSERT INTO country_other_local_name VALUES ('TJ','Љумњурии Тољикистон','');
INSERT INTO country_other_local_name VALUES ('PA','la República de Panamá','');
INSERT INTO country_other_local_name VALUES ('NIC','la República de Nicaragua','');
INSERT INTO country_other_local_name VALUES ('OM','سلطنة عمان','');
INSERT INTO country_other_local_name VALUES ('BS','the Commonwealth of the Bahamas','');
