INSERT INTO country_continent VALUES ('STP','Africa','100');
INSERT INTO country_continent VALUES ('TT','North America','100');
INSERT INTO country_continent VALUES ('R','Europe','23.15');
INSERT INTO country_continent VALUES ('BI','Africa','100');
INSERT INTO country_continent VALUES ('Z','Africa','100');
INSERT INTO country_continent VALUES ('C','North America','100');
INSERT INTO country_continent VALUES ('MNG','Asia','100');
INSERT INTO country_continent VALUES ('WV','North America','100');
INSERT INTO country_continent VALUES ('H','Europe','100');
INSERT INTO country_continent VALUES ('SLE','Africa','100');
INSERT INTO country_continent VALUES ('AZ','Asia','100');
INSERT INTO country_continent VALUES ('BZ','North America','100');
INSERT INTO country_continent VALUES ('RI','Asia','78');
INSERT INTO country_continent VALUES ('BR','South America','100');
INSERT INTO country_continent VALUES ('S','Europe','100');
INSERT INTO country_continent VALUES ('MAYO','Africa','100');
INSERT INTO country_continent VALUES ('SBAR','North America','100');
INSERT INTO country_continent VALUES ('AMSA','Australia/Oceania','100');
INSERT INTO country_continent VALUES ('V','Europe','100');
INSERT INTO country_continent VALUES ('IRQ','Asia','100');
INSERT INTO country_continent VALUES ('RC','Asia','100');
INSERT INTO country_continent VALUES ('COOK','Australia/Oceania','100');
INSERT INTO country_continent VALUES ('MACX','Asia','100');
INSERT INTO country_continent VALUES ('XMAS','Australia/Oceania','100');
INSERT INTO country_continent VALUES ('RIM','Africa','100');
INSERT INTO country_continent VALUES ('CAM','Africa','100');
INSERT INTO country_continent VALUES ('SSD','Africa','100');
INSERT INTO country_continent VALUES ('THA','Asia','100');
INSERT INTO country_continent VALUES ('WD','North America','100');
INSERT INTO country_continent VALUES ('GBJ','Europe','100');
INSERT INTO country_continent VALUES ('IRL','Europe','100');
INSERT INTO country_continent VALUES ('BF','Africa','100');
INSERT INTO country_continent VALUES ('BOL','South America','100');
INSERT INTO country_continent VALUES ('PE','South America','100');
INSERT INTO country_continent VALUES ('MOC','Africa','100');
INSERT INTO country_continent VALUES ('UZ','Asia','100');
INSERT INTO country_continent VALUES ('MNE','Europe','100');
INSERT INTO country_continent VALUES ('VU','Australia/Oceania','100');
INSERT INTO country_continent VALUES ('LS','Africa','100');
INSERT INTO country_continent VALUES ('MYA','Asia','100');
INSERT INTO country_continent VALUES ('PR','North America','100');
INSERT INTO country_continent VALUES ('RA','South America','100');
INSERT INTO country_continent VALUES ('TO','Australia/Oceania','100');
INSERT INTO country_continent VALUES ('SRB','Europe','100');
INSERT INTO country_continent VALUES ('TR','Europe','3');
INSERT INTO country_continent VALUES ('MC','Europe','100');
INSERT INTO country_continent VALUES ('LAO','Asia','100');
INSERT INTO country_continent VALUES ('K','Asia','100');
INSERT INTO country_continent VALUES ('LV','Europe','100');
INSERT INTO country_continent VALUES ('SX','North America','100');
INSERT INTO country_continent VALUES ('FSM','Australia/Oceania','100');
INSERT INTO country_continent VALUES ('RT','Africa','100');
INSERT INTO country_continent VALUES ('KZ','Europe','5.4');
INSERT INTO country_continent VALUES ('BHT','Asia','100');
INSERT INTO country_continent VALUES ('NGR','Africa','100');
INSERT INTO country_continent VALUES ('DJI','Africa','100');
INSERT INTO country_continent VALUES ('NZ','Australia/Oceania','100');
INSERT INTO country_continent VALUES ('WS','Australia/Oceania','100');
INSERT INTO country_continent VALUES ('SD','Africa','100');
INSERT INTO country_continent VALUES ('MS','Africa','100');
INSERT INTO country_continent VALUES ('RG','Africa','100');
INSERT INTO country_continent VALUES ('PA','North America','100');
INSERT INTO country_continent VALUES ('KN','North America','100');
INSERT INTO country_continent VALUES ('ROU','South America','100');
INSERT INTO country_continent VALUES ('FALK','South America','100');
INSERT INTO country_continent VALUES ('AFG','Asia','100');
INSERT INTO country_continent VALUES ('MEL','Africa','100');
INSERT INTO country_continent VALUES ('ARM','Asia','100');
INSERT INTO country_continent VALUES ('KP','Asia','100');
INSERT INTO country_continent VALUES ('SN','Africa','100');
INSERT INTO country_continent VALUES ('TJ','Asia','100');
INSERT INTO country_continent VALUES ('EAT','Africa','100');
INSERT INTO country_continent VALUES ('IR','Asia','100');
INSERT INTO country_continent VALUES ('GAZA','Asia','100');
INSERT INTO country_continent VALUES ('MH','Australia/Oceania','100');
INSERT INTO country_continent VALUES ('FPOL','Australia/Oceania','100');
INSERT INTO country_continent VALUES ('EC','South America','100');
INSERT INTO country_continent VALUES ('CV','Africa','100');
INSERT INTO country_continent VALUES ('AXA','North America','100');
INSERT INTO country_continent VALUES ('HK','Asia','100');
INSERT INTO country_continent VALUES ('GH','Africa','100');
INSERT INTO country_continent VALUES ('TUCA','North America','100');
INSERT INTO country_continent VALUES ('ET','Africa','92.7');
INSERT INTO country_continent VALUES ('A','Europe','100');
INSERT INTO country_continent VALUES ('P','Europe','100');
INSERT INTO country_continent VALUES ('Q','Asia','100');
INSERT INTO country_continent VALUES ('TUV','Australia/Oceania','100');
INSERT INTO country_continent VALUES ('AL','Europe','100');
INSERT INTO country_continent VALUES ('VN','Asia','100');
INSERT INTO country_continent VALUES ('NIUE','Australia/Oceania','100');
INSERT INTO country_continent VALUES ('SMAR','North America','100');
INSERT INTO country_continent VALUES ('PY','South America','100');
INSERT INTO country_continent VALUES ('GUB','Africa','100');
INSERT INTO country_continent VALUES ('CGO','Africa','100');
INSERT INTO country_continent VALUES ('CEU','Africa','100');
INSERT INTO country_continent VALUES ('CL','Asia','100');
INSERT INTO country_continent VALUES ('BD','Asia','100');
INSERT INTO country_continent VALUES ('BRU','Asia','100');
INSERT INTO country_continent VALUES ('GUY','South America','100');
INSERT INTO country_continent VALUES ('CDN','North America','100');
INSERT INTO country_continent VALUES ('ET','Asia','7.3');
INSERT INTO country_continent VALUES ('KG','Asia','100');
INSERT INTO country_continent VALUES ('BVI','North America','100');
INSERT INTO country_continent VALUES ('ROK','Asia','100');
INSERT INTO country_continent VALUES ('ANG','Africa','100');
INSERT INTO country_continent VALUES ('AG','North America','100');
INSERT INTO country_continent VALUES ('SO','Africa','100');
INSERT INTO country_continent VALUES ('COM','Africa','100');
INSERT INTO country_continent VALUES ('LAR','Africa','100');
INSERT INTO country_continent VALUES ('GL','North America','100');
INSERT INTO country_continent VALUES ('GUAD','North America','100');
INSERT INTO country_continent VALUES ('BG','Europe','100');
INSERT INTO country_continent VALUES ('YE','Asia','100');
INSERT INTO country_continent VALUES ('YV','South America','100');
INSERT INTO country_continent VALUES ('FGU','South America','100');
INSERT INTO country_continent VALUES ('E','Europe','100');
INSERT INTO country_continent VALUES ('KIR','Australia/Oceania','100');
INSERT INTO country_continent VALUES ('CH','Europe','100');
INSERT INTO country_continent VALUES ('SYR','Asia','100');
INSERT INTO country_continent VALUES ('MV','Asia','100');
INSERT INTO country_continent VALUES ('WL','North America','100');
INSERT INTO country_continent VALUES ('GR','Europe','100');
INSERT INTO country_continent VALUES ('L','Europe','100');
INSERT INTO country_continent VALUES ('B','Europe','100');
INSERT INTO country_continent VALUES ('GCA','North America','100');
INSERT INTO country_continent VALUES ('PNG','Australia/Oceania','100');
INSERT INTO country_continent VALUES ('RN','Africa','100');
INSERT INTO country_continent VALUES ('RH','North America','100');
INSERT INTO country_continent VALUES ('CUR','South America','100');
INSERT INTO country_continent VALUES ('KOS','Europe','100');
INSERT INTO country_continent VALUES ('I','Europe','100');
INSERT INTO country_continent VALUES ('IND','Asia','100');
INSERT INTO country_continent VALUES ('BERM','North America','100');
INSERT INTO country_continent VALUES ('SME','South America','100');
INSERT INTO country_continent VALUES ('MEX','North America','100');
INSERT INTO country_continent VALUES ('GBM','Europe','100');
INSERT INTO country_continent VALUES ('CZ','Europe','100');
INSERT INTO country_continent VALUES ('USA','North America','100');
INSERT INTO country_continent VALUES ('R','Asia','76.85');
INSERT INTO country_continent VALUES ('NORF','Australia/Oceania','100');
INSERT INTO country_continent VALUES ('SLO','Europe','100');
INSERT INTO country_continent VALUES ('GBZ','Europe','100');
INSERT INTO country_continent VALUES ('WB','Asia','100');
INSERT INTO country_continent VALUES ('TOK','Australia/Oceania','100');
INSERT INTO country_continent VALUES ('CAYM','North America','100');
INSERT INTO country_continent VALUES ('WG','North America','100');
INSERT INTO country_continent VALUES ('PK','Asia','100');
INSERT INTO country_continent VALUES ('CR','North America','100');
INSERT INTO country_continent VALUES ('TCH','Africa','100');
INSERT INTO country_continent VALUES ('BY','Europe','100');
INSERT INTO country_continent VALUES ('COCO','Australia/Oceania','100');
INSERT INTO country_continent VALUES ('G','Africa','100');
INSERT INTO country_continent VALUES ('SY','Africa','100');
INSERT INTO country_continent VALUES ('MW','Africa','100');
INSERT INTO country_continent VALUES ('REUN','Africa','100');
INSERT INTO country_continent VALUES ('RM','Africa','100');
INSERT INTO country_continent VALUES ('BRN','Asia','100');
INSERT INTO country_continent VALUES ('MART','North America','100');
INSERT INTO country_continent VALUES ('FO','Europe','100');
INSERT INTO country_continent VALUES ('CY','Europe','100');
INSERT INTO country_continent VALUES ('IS','Europe','100');
INSERT INTO country_continent VALUES ('DK','Europe','100');
INSERT INTO country_continent VALUES ('CI','Africa','100');
INSERT INTO country_continent VALUES ('HN','North America','100');
INSERT INTO country_continent VALUES ('TR','Asia','97');
INSERT INTO country_continent VALUES ('DZ','Africa','100');
INSERT INTO country_continent VALUES ('NCL','Australia/Oceania','100');
INSERT INTO country_continent VALUES ('SGP','Asia','100');
INSERT INTO country_continent VALUES ('NMIS','Australia/Oceania','100');
INSERT INTO country_continent VALUES ('LT','Europe','100');
INSERT INTO country_continent VALUES ('F','Europe','100');
INSERT INTO country_continent VALUES ('ES','North America','100');
INSERT INTO country_continent VALUES ('SUD','Africa','100');
INSERT INTO country_continent VALUES ('RCA','Africa','100');
INSERT INTO country_continent VALUES ('RO','Europe','100');
INSERT INTO country_continent VALUES ('EST','Europe','100');
INSERT INTO country_continent VALUES ('CO','South America','100');
INSERT INTO country_continent VALUES ('SVA','Europe','100');
INSERT INTO country_continent VALUES ('J','Asia','100');
INSERT INTO country_continent VALUES ('RCH','South America','100');
INSERT INTO country_continent VALUES ('BIH','Europe','100');
INSERT INTO country_continent VALUES ('RSM','Europe','100');
INSERT INTO country_continent VALUES ('KWT','Asia','100');
INSERT INTO country_continent VALUES ('WSA','Africa','100');
INSERT INTO country_continent VALUES ('RB','Africa','100');
INSERT INTO country_continent VALUES ('RL','Asia','100');
INSERT INTO country_continent VALUES ('D','Europe','100');
INSERT INTO country_continent VALUES ('OM','Asia','100');
INSERT INTO country_continent VALUES ('UAE','Asia','100');
INSERT INTO country_continent VALUES ('EAK','Africa','100');
INSERT INTO country_continent VALUES ('WAG','Africa','100');
INSERT INTO country_continent VALUES ('LB','Africa','100');
INSERT INTO country_continent VALUES ('N','Europe','100');
INSERT INTO country_continent VALUES ('TL','Asia','100');
INSERT INTO country_continent VALUES ('NAU','Australia/Oceania','100');
INSERT INTO country_continent VALUES ('WF','Australia/Oceania','100');
INSERT INTO country_continent VALUES ('UA','Europe','100');
INSERT INTO country_continent VALUES ('BEN','Africa','100');
INSERT INTO country_continent VALUES ('RWA','Africa','100');
INSERT INTO country_continent VALUES ('AND','Europe','100');
INSERT INTO country_continent VALUES ('IL','Asia','100');
INSERT INTO country_continent VALUES ('PITC','Australia/Oceania','100');
INSERT INTO country_continent VALUES ('MNTS','North America','100');
INSERT INTO country_continent VALUES ('NEP','Asia','100');
INSERT INTO country_continent VALUES ('NAM','Africa','100');
INSERT INTO country_continent VALUES ('HELX','Africa','100');
INSERT INTO country_continent VALUES ('GBG','Europe','100');
INSERT INTO country_continent VALUES ('GUAM','Australia/Oceania','100');
INSERT INTO country_continent VALUES ('CN','Asia','100');
INSERT INTO country_continent VALUES ('GB','Europe','100');
INSERT INTO country_continent VALUES ('FL','Europe','100');
INSERT INTO country_continent VALUES ('EAU','Africa','100');
INSERT INTO country_continent VALUES ('ARU','South America','100');
INSERT INTO country_continent VALUES ('RCB','Africa','100');
INSERT INTO country_continent VALUES ('NIC','North America','100');
INSERT INTO country_continent VALUES ('NLB','South America','100');
INSERT INTO country_continent VALUES ('PAL','Australia/Oceania','100');
INSERT INTO country_continent VALUES ('VIRG','North America','100');
INSERT INTO country_continent VALUES ('RMM','Africa','100');
INSERT INTO country_continent VALUES ('FJI','Australia/Oceania','100');
INSERT INTO country_continent VALUES ('SK','Europe','100');
INSERT INTO country_continent VALUES ('NL','Europe','100');
INSERT INTO country_continent VALUES ('MD','Europe','100');
INSERT INTO country_continent VALUES ('GE','Asia','100');
INSERT INTO country_continent VALUES ('ZW','Africa','100');
INSERT INTO country_continent VALUES ('AUS','Australia/Oceania','100');
INSERT INTO country_continent VALUES ('ETH','Africa','100');
INSERT INTO country_continent VALUES ('SA','Asia','100');
INSERT INTO country_continent VALUES ('RI','Australia/Oceania','22');
INSERT INTO country_continent VALUES ('HR','Europe','100');
INSERT INTO country_continent VALUES ('TN','Africa','100');
INSERT INTO country_continent VALUES ('ER','Africa','100');
INSERT INTO country_continent VALUES ('SPMI','North America','100');
INSERT INTO country_continent VALUES ('BS','North America','100');
INSERT INTO country_continent VALUES ('KZ','Asia','94.6');
INSERT INTO country_continent VALUES ('TM','Asia','100');
INSERT INTO country_continent VALUES ('M','Europe','100');
INSERT INTO country_continent VALUES ('MK','Europe','100');
INSERT INTO country_continent VALUES ('BDS','North America','100');
INSERT INTO country_continent VALUES ('GQ','Africa','100');
INSERT INTO country_continent VALUES ('JA','North America','100');
INSERT INTO country_continent VALUES ('RP','Asia','100');
INSERT INTO country_continent VALUES ('DOM','North America','100');
INSERT INTO country_continent VALUES ('JOR','Asia','100');
INSERT INTO country_continent VALUES ('MAL','Asia','100');
INSERT INTO country_continent VALUES ('SOL','Australia/Oceania','100');
INSERT INTO country_continent VALUES ('SF','Europe','100');
INSERT INTO country_continent VALUES ('PL','Europe','100');
INSERT INTO country_continent VALUES ('MA','Africa','100');
INSERT INTO country_continent VALUES ('RSA','Africa','100');
