INSERT INTO located_on VALUES ('Balikpapan','Kalimantan Timur','RI','Borneo');
INSERT INTO located_on VALUES ('Makati','Metro Manila','RP','Luzon');
INSERT INTO located_on VALUES ('Liverpool','North West','GB','Great Britain');
INSERT INTO located_on VALUES ('Colombo','Sri Lanka','CL','Sri Lanka');
INSERT INTO located_on VALUES ('Medan','Sumatera Utara','RI','Sumatra');
INSERT INTO located_on VALUES ('São Tomé','Sao Tome and Principe','STP','Sao Tome');
INSERT INTO located_on VALUES ('Calapan','Mimaropa','RP','Mindoro');
INSERT INTO located_on VALUES ('Toyama','Toyama','J','Honshu');
INSERT INTO located_on VALUES ('Edinburgh','Scotland','GB','Great Britain');
INSERT INTO located_on VALUES ('Funafuti','Tuvalu','TUV','Fongafale');
INSERT INTO located_on VALUES ('Marawi','Muslim Mindanao','RP','Mindanao');
INSERT INTO located_on VALUES ('Blackburn','North West','GB','Great Britain');
INSERT INTO located_on VALUES ('Cimahi','Jawa Barat','RI','Java');
INSERT INTO located_on VALUES ('Stockport','North West','GB','Great Britain');
INSERT INTO located_on VALUES ('Serang','Banten','RI','Java');
INSERT INTO located_on VALUES ('Yamagata','Yamagata','J','Honshu');
INSERT INTO located_on VALUES ('Otsu','Shiga','J','Honshu');
INSERT INTO located_on VALUES ('Akureyri','Iceland','IS','Iceland');
INSERT INTO located_on VALUES ('Worthing','South East','GB','Great Britain');
INSERT INTO located_on VALUES ('Kavaratti','Lakshadweep','IND','Kavaratti');
INSERT INTO located_on VALUES ('Kawaguchi','Saitama','J','Honshu');
INSERT INTO located_on VALUES ('San Cristóbal de La Laguna','Canarias','E','Teneriffa');
INSERT INTO located_on VALUES ('Tacloban','Eastern Visayas','RP','Leyte');
INSERT INTO located_on VALUES ('Santa Cruz de Tenerife','Canarias','E','Teneriffa');
INSERT INTO located_on VALUES ('Santo Domingo','Dominican Republic','DOM','Hispaniola');
INSERT INTO located_on VALUES ('Tasikmalaya','Jawa Barat','RI','Java');
INSERT INTO located_on VALUES ('Port-au-Prince','Haiti','RH','Hispaniola');
INSERT INTO located_on VALUES ('Antsiranana','Madagascar','RM','Madagaskar');
INSERT INTO located_on VALUES ('Delmas','Haiti','RH','Hispaniola');
INSERT INTO located_on VALUES ('Bradford','Yorkshire and the Humber','GB','Great Britain');
INSERT INTO located_on VALUES ('Worcester','West Midlands','GB','Great Britain');
INSERT INTO located_on VALUES ('Maebashi','Gumma','J','Honshu');
INSERT INTO located_on VALUES ('Montréal','Quebec','CDN','Île de Montréal');
INSERT INTO located_on VALUES ('Osaka','Osaka','J','Honshu');
INSERT INTO located_on VALUES ('Valenzuela','Metro Manila','RP','Luzon');
INSERT INTO located_on VALUES ('Haikou','Hainan','CN','Hainan');
INSERT INTO located_on VALUES ('Exeter','South West','GB','Great Britain');
INSERT INTO located_on VALUES ('Swindon','South West','GB','Great Britain');
INSERT INTO located_on VALUES ('Artemisa','Artemisa','C','Cuba');
INSERT INTO located_on VALUES ('Probolinggo','Jawa Timur','RI','Java');
INSERT INTO located_on VALUES ('Blackpool','North West','GB','Great Britain');
INSERT INTO located_on VALUES ('Fukuoka','Fukuoka','J','Kyushu');
INSERT INTO located_on VALUES ('Pekanbaru','Riau','RI','Sumatra');
INSERT INTO located_on VALUES ('Swansea','Wales','GB','Great Britain');
INSERT INTO located_on VALUES ('Kushiro','Hokkaido','J','Hokkaido');
INSERT INTO located_on VALUES ('Tamatave','Madagascar','RM','Madagaskar');
INSERT INTO located_on VALUES ('Iqaluit','Nunavut','CDN','Baffin Island');
INSERT INTO located_on VALUES ('Saint-Pierre','Saint Pierre and Miquelon','SPMI','Saint Pierre');
INSERT INTO located_on VALUES ('Alofi','Niue','NIUE','Niue');
INSERT INTO located_on VALUES ('Dededo','Guam','GUAM','Guam');
INSERT INTO located_on VALUES ('Cambridge','East of England','GB','Great Britain');
INSERT INTO located_on VALUES ('Bolton','North West','GB','Great Britain');
INSERT INTO located_on VALUES ('Bandjarmasin','Kalimantan Selatan','RI','Borneo');
INSERT INTO located_on VALUES ('Watford','East of England','GB','Great Britain');
INSERT INTO located_on VALUES ('Sakai','Osaka','J','Honshu');
INSERT INTO located_on VALUES ('San Fernando','Ilocos','RP','Luzon');
INSERT INTO located_on VALUES ('Laval','Quebec','CDN','Île Jésus');
INSERT INTO located_on VALUES ('Mataram','Nusa Tenggara Barat','RI','Lombok');
INSERT INTO located_on VALUES ('Manokwari','Papua Barat','RI','New Guinea');
INSERT INTO located_on VALUES ('Auckland','New Zealand','NZ','Te Ika-a-Maui (North Island)');
INSERT INTO located_on VALUES ('Zamboanga','Zamboanga Peninsula','RP','Mindanao');
INSERT INTO located_on VALUES ('Tarawa','Kiribati','KIR','Tarawa');
INSERT INTO located_on VALUES ('Sendai','Miyagi','J','Honshu');
INSERT INTO located_on VALUES ('Willemstad','Curacao','CUR','Curacao');
INSERT INTO located_on VALUES ('Basingstoke','South East','GB','Great Britain');
INSERT INTO located_on VALUES ('Jayapura','Papua','RI','New Guinea');
INSERT INTO located_on VALUES ('La Asuncion','Nueva Esparta','YV','Isla Margarita');
INSERT INTO located_on VALUES ('New York','New York','USA','Manhattan');
INSERT INTO located_on VALUES ('Cap-Haïtien','Haiti','RH','Hispaniola');
INSERT INTO located_on VALUES ('Butuan','Caraga','RP','Mindanao');
INSERT INTO located_on VALUES ('Semarang','Jawa Tengah','RI','Java');
INSERT INTO located_on VALUES ('Marigot','Saint Martin','SMAR','St. Martin');
INSERT INTO located_on VALUES ('York','Yorkshire and the Humber','GB','Great Britain');
INSERT INTO located_on VALUES ('Cork','Ireland','IRL','Ireland');
INSERT INTO located_on VALUES ('Tagum','Davao','RP','Mindanao');
INSERT INTO located_on VALUES ('Kendari','Sulawesi Tenggara','RI','Sulawesi');
INSERT INTO located_on VALUES ('Koror','Palau','PAL','Koror');
INSERT INTO located_on VALUES ('Kediri','Jawa Timur','RI','Java');
INSERT INTO located_on VALUES ('Tórshavn','Faroe Islands','FO','Streymoy');
INSERT INTO located_on VALUES ('Honiara','Solomon Islands','SOL','Guadalcanal');
INSERT INTO located_on VALUES ('New York','New York','USA','Staten Island');
INSERT INTO located_on VALUES ('San José de las Lajas','Mayabeque','C','Cuba');
INSERT INTO located_on VALUES ('Messina','Sicilia','I','Sicilia');
INSERT INTO located_on VALUES ('Kanazawa','Ishikawa','J','Honshu');
INSERT INTO located_on VALUES ('Palermo','Sicilia','I','Sicilia');
INSERT INTO located_on VALUES ('Ipswich','East of England','GB','Great Britain');
INSERT INTO located_on VALUES ('Praia','Cape Verde','CV','Santiago');
INSERT INTO located_on VALUES ('Majuro','Marshall Islands','MH','Majuro');
INSERT INTO located_on VALUES ('Machida','Tokyo','J','Honshu');
INSERT INTO located_on VALUES ('Dumai','Riau','RI','Sumatra');
INSERT INTO located_on VALUES ('Okayama','Okayama','J','Honshu');
INSERT INTO located_on VALUES ('Lerwick','Scotland','GB','Shetland Mainland');
INSERT INTO located_on VALUES ('Keelung','Taiwan','RC','Taiwan');
INSERT INTO located_on VALUES ('Bogor','Jawa Barat','RI','Java');
INSERT INTO located_on VALUES ('Rotherham','Yorkshire and the Humber','GB','Great Britain');
INSERT INTO located_on VALUES ('Ciego de Ávila','Ciego de Ávila','C','Cuba');
INSERT INTO located_on VALUES ('Lubuk Linggau','Sumatera Selatan','RI','Sumatra');
INSERT INTO located_on VALUES ('Port Blair','Andaman and Nicobar Islands','IND','South Andaman Island');
INSERT INTO located_on VALUES ('Funchal','Madeira','P','Madeira');
INSERT INTO located_on VALUES ('Kyoto','Kyoto','J','Honshu');
INSERT INTO located_on VALUES ('Yamaguchi','Yamaguchi','J','Honshu');
INSERT INTO located_on VALUES ('Singapore','Singapore','SGP','Ujong');
INSERT INTO located_on VALUES ('Dublin','Ireland','IRL','Ireland');
INSERT INTO located_on VALUES ('Iligan','Northern Mindanao','RP','Mindanao');
INSERT INTO located_on VALUES ('Malabon','Metro Manila','RP','Luzon');
INSERT INTO located_on VALUES ('Mamuju','Sulawesi Barat','RI','Sulawesi');
INSERT INTO located_on VALUES ('Mata-Utu','Wallis and Futuna','WF','Uvea');
INSERT INTO located_on VALUES ('Bengkulu','Bengkulu','RI','Sumatra');
INSERT INTO located_on VALUES ('Denpasar','Bali','RI','Bali');
INSERT INTO located_on VALUES ('San Juan','Puerto Rico','PR','Puerto Rico');
INSERT INTO located_on VALUES ('Bridgetown','Barbados','BDS','Barbados');
INSERT INTO located_on VALUES ('Southampton','South East','GB','Great Britain');
INSERT INTO located_on VALUES ('Mandaluyong','Metro Manila','RP','Luzon');
INSERT INTO located_on VALUES ('Shizuoka','Shizuoka','J','Honshu');
INSERT INTO located_on VALUES ('Cilegon','Banten','RI','Java');
INSERT INTO located_on VALUES ('Palu','Sulawesi Tengah','RI','Sulawesi');
INSERT INTO located_on VALUES ('Taipei','Taiwan','RC','Taiwan');
INSERT INTO located_on VALUES ('Makassar','Sulawesi Selatan','RI','Sulawesi');
INSERT INTO located_on VALUES ('Sunderland','North East','GB','Great Britain');
INSERT INTO located_on VALUES ('Binjai','Sumatera Utara','RI','Sumatra');
INSERT INTO located_on VALUES ('Cardiff','Wales','GB','Great Britain');
INSERT INTO located_on VALUES ('Peterborough','East of England','GB','Great Britain');
INSERT INTO located_on VALUES ('Bandung','Jawa Barat','RI','Java');
INSERT INTO located_on VALUES ('Hobart','Tasmania','AUS','Tasmania');
INSERT INTO located_on VALUES ('Sanya','Hainan','CN','Hainan');
INSERT INTO located_on VALUES ('Maidstone','South East','GB','Great Britain');
INSERT INTO located_on VALUES ('Manzanillo','Granma','C','Cuba');
INSERT INTO located_on VALUES ('Sri Jayawardhanapura','Sri Lanka','CL','Sri Lanka');
INSERT INTO located_on VALUES ('Baguio','Cordillera','RP','Luzon');
INSERT INTO located_on VALUES ('Muntinlupa','Metro Manila','RP','Luzon');
INSERT INTO located_on VALUES ('Tangerang Selatan','Banten','RI','Java');
INSERT INTO located_on VALUES ('Nottingham','East Midlands','GB','Great Britain');
INSERT INTO located_on VALUES ('Ronne','Hovedstaden','DK','Bornholm');
INSERT INTO located_on VALUES ('Glasgow','Scotland','GB','Great Britain');
INSERT INTO located_on VALUES ('Davao','Davao','RP','Mindanao');
INSERT INTO located_on VALUES ('Sandakan','Sabah','MAL','Borneo');
INSERT INTO located_on VALUES ('Kingston','Norfolk Island','NORF','Norfolk Island');
INSERT INTO located_on VALUES ('Woking','South East','GB','Great Britain');
INSERT INTO located_on VALUES ('Lae','North','PNG','New Guinea');
INSERT INTO located_on VALUES ('Saint Peter Port','Guernsey','GBG','Guernsey');
INSERT INTO located_on VALUES ('Tsu','Mie','J','Honshu');
INSERT INTO located_on VALUES ('Florianópolis','Santa Catarina','BR','Ilha de Santa Catarina');
INSERT INTO located_on VALUES ('Surakarta','Jawa Tengah','RI','Java');
INSERT INTO located_on VALUES ('Naha','Okinawa','J','Okinawa');
INSERT INTO located_on VALUES ('Koronadal','Soccsksargen','RP','Mindanao');
INSERT INTO located_on VALUES ('Bekasi','Jawa Barat','RI','Java');
INSERT INTO located_on VALUES ('Morioka','Iwate','J','Honshu');
INSERT INTO located_on VALUES ('Brades','Montserrat','MNTS','Montserrat');
INSERT INTO located_on VALUES ('Leeds','Yorkshire and the Humber','GB','Great Britain');
INSERT INTO located_on VALUES ('Pontianak','Kalimantan Barat','RI','Borneo');
INSERT INTO located_on VALUES ('Pingtung','Taiwan','RC','Taiwan');
INSERT INTO located_on VALUES ('Al Manāmah','Bahrain','BRN','Bahrain');
INSERT INTO located_on VALUES ('Reykjavik','Iceland','IS','Iceland');
INSERT INTO located_on VALUES ('Basildon','East of England','GB','Great Britain');
INSERT INTO located_on VALUES ('Nagoya','Aichi','J','Honshu');
INSERT INTO located_on VALUES ('General Trias','Calabarzon','RP','Luzon');
INSERT INTO located_on VALUES ('Port Vila','Vanuatu','VU','Efate');
INSERT INTO located_on VALUES ('Moroni','Comoros','COM','Grand Comoro');
INSERT INTO located_on VALUES ('Warrington','North West','GB','Great Britain');
INSERT INTO located_on VALUES ('Castries','Saint Lucia','WL','Saint Lucia');
INSERT INTO located_on VALUES ('Akita','Akita','J','Honshu');
INSERT INTO located_on VALUES ('Lemesos','Cyprus','CY','Cyprus');
INSERT INTO located_on VALUES ('Palangkaraya','Kalimantan Tengah','RI','Borneo');
INSERT INTO located_on VALUES ('Toyota','Aichi','J','Honshu');
INSERT INTO located_on VALUES ('Aberdeen','Scotland','GB','Great Britain');
INSERT INTO located_on VALUES ('Sancti Spíritus','Sancti Spíritus','C','Cuba');
INSERT INTO located_on VALUES ('Chake Chake','Kusini Pemba','EAT','Pemba');
INSERT INTO located_on VALUES ('Hualien','Taiwan','RC','Taiwan');
INSERT INTO located_on VALUES ('Palma de Mallorca','Illes Balears','E','Mallorca');
INSERT INTO located_on VALUES ('Porlamar','Nueva Esparta','YV','Isla Margarita');
INSERT INTO located_on VALUES ('Pematang Siantar','Sumatera Utara','RI','Sumatra');
INSERT INTO located_on VALUES ('Tegal','Jawa Tengah','RI','Java');
INSERT INTO located_on VALUES ('Hakodate','Hokkaido','J','Hokkaido');
INSERT INTO located_on VALUES ('Holguín','Holguín','C','Cuba');
INSERT INTO located_on VALUES ('Pago Pago','American Samoa','AMSA','Tutuila');
INSERT INTO located_on VALUES ('Las Palmas de Gran Canaria','Canarias','E','Gran Canaria');
INSERT INTO located_on VALUES ('Fukui','Fukui','J','Honshu');
INSERT INTO located_on VALUES ('Cagayan De Oro','Northern Mindanao','RP','Mindanao');
INSERT INTO located_on VALUES ('Koani','Kusini Unguja','EAT','Sansibar');
INSERT INTO located_on VALUES ('Saint Helier','Jersey','GBJ','Jersey');
INSERT INTO located_on VALUES ('Port Moresby','South','PNG','New Guinea');
INSERT INTO located_on VALUES ('Buka','Bougainville','PNG','Buka');
INSERT INTO located_on VALUES ('Pagadian','Zamboanga Peninsula','RP','Mindanao');
INSERT INTO located_on VALUES ('Zanzibar','Mjini Magharibi Unguja','EAT','Sansibar');
INSERT INTO located_on VALUES ('Male','Maldives','MV','Male');
INSERT INTO located_on VALUES ('Tagbilaran','Central Visayas','RP','Bohol');
INSERT INTO located_on VALUES ('St. John''s','Newfoundland and Labrador','CDN','Newfoundland');
INSERT INTO located_on VALUES ('Lincoln','East Midlands','GB','Great Britain');
INSERT INTO located_on VALUES ('Basse-Terre','Guadeloupe','GUAD','Basse-Terre');
INSERT INTO located_on VALUES ('Catánia','Sicilia','I','Sicilia');
INSERT INTO located_on VALUES ('London','London','GB','Great Britain');
INSERT INTO located_on VALUES ('Pekalongan','Jawa Tengah','RI','Java');
INSERT INTO located_on VALUES ('Santiago de Cuba','Santiago de Cuba','C','Cuba');
INSERT INTO located_on VALUES ('Kurashiki','Okayama','J','Honshu');
INSERT INTO located_on VALUES ('Victoria de las Tunas','Las Tunas','C','Cuba');
INSERT INTO located_on VALUES ('Sapporo','Hokkaido','J','Hokkaido');
INSERT INTO located_on VALUES ('Iloilo','Western Visayas','RP','Panay');
INSERT INTO located_on VALUES ('Hafnarfjordur','Iceland','IS','Iceland');
INSERT INTO located_on VALUES ('Kuching Utara','Sarawak','MAL','Borneo');
INSERT INTO located_on VALUES ('Newcastle upon Tyne','North East','GB','Great Britain');
INSERT INTO located_on VALUES ('Bayamón','Puerto Rico','PR','Puerto Rico');
INSERT INTO located_on VALUES ('Kitakyushu','Fukuoka','J','Kyushu');
INSERT INTO located_on VALUES ('Quezon City','Metro Manila','RP','Luzon');
INSERT INTO located_on VALUES ('Poole','South West','GB','Great Britain');
INSERT INTO located_on VALUES ('Lapu-Lapu','Central Visayas','RP','Cebu');
INSERT INTO located_on VALUES ('Mytilini','Boreioy Aigaioy','GR','Lesbos');
INSERT INTO located_on VALUES ('Cotabato','Muslim Mindanao','RP','Mindanao');
INSERT INTO located_on VALUES ('Luton','East of England','GB','Great Britain');
INSERT INTO located_on VALUES ('Tottori','Tottori','J','Honshu');
INSERT INTO located_on VALUES ('Telford','West Midlands','GB','Great Britain');
INSERT INTO located_on VALUES ('Mabalacat','Central Luzon','RP','Luzon');
INSERT INTO located_on VALUES ('San Pablo','Calabarzon','RP','Luzon');
INSERT INTO located_on VALUES ('Hilo','Hawaii','USA','Hawaii');
INSERT INTO located_on VALUES ('Carrefour','Haiti','RH','Hispaniola');
INSERT INTO located_on VALUES ('Wakefield','Yorkshire and the Humber','GB','Great Britain');
INSERT INTO located_on VALUES ('Colchester','East of England','GB','Great Britain');
INSERT INTO located_on VALUES ('Fakaofo','Tokelau','TOK','Fakaofo');
INSERT INTO located_on VALUES ('Himeji','Hyogo','J','Honshu');
INSERT INTO located_on VALUES ('Depok','Jawa Barat','RI','Java');
INSERT INTO located_on VALUES ('Flying Fish Cove','Christmas Island','XMAS','Christmas Island');
INSERT INTO located_on VALUES ('Gifu','Gifu','J','Honshu');
INSERT INTO located_on VALUES ('Keflavik','Iceland','IS','Iceland');
INSERT INTO located_on VALUES ('Sagamihara','Kanagawa','J','Honshu');
INSERT INTO located_on VALUES ('Tuguegarao','Cagayan Valley','RP','Luzon');
INSERT INTO located_on VALUES ('Tanjung Selor','Kalimantan Utara','RI','Borneo');
INSERT INTO located_on VALUES ('Wakayama','Wakayama','J','Honshu');
INSERT INTO located_on VALUES ('Chiayi','Taiwan','RC','Taiwan');
INSERT INTO located_on VALUES ('Birkenhead','North West','GB','Great Britain');
INSERT INTO located_on VALUES ('Taipa-Coloane','Macao','MACX','Taipa');
INSERT INTO located_on VALUES ('Sássari','Sardegna','I','Sardegna');
INSERT INTO located_on VALUES ('Cienfuegos','Cienfuegos','C','Cuba');
INSERT INTO located_on VALUES ('Nagano','Nagano','J','Honshu');
INSERT INTO located_on VALUES ('Pinar del Río','Pinar del Río','C','Cuba');
INSERT INTO located_on VALUES ('Merauke','Papua','RI','New Guinea');
INSERT INTO located_on VALUES ('Valletta','Malta','M','Malta');
INSERT INTO located_on VALUES ('Nishinomiya','Hyogo','J','Honshu');
INSERT INTO located_on VALUES ('Saint-Paul','Reunion','REUN','Reunion');
INSERT INTO located_on VALUES ('Ajaccio','Corse','F','Corse');
INSERT INTO located_on VALUES ('Middlesbrough','North East','GB','Great Britain');
INSERT INTO located_on VALUES ('Wete','Kaskazini Pemba','EAT','Pemba');
INSERT INTO located_on VALUES ('Hirakata','Osaka','J','Honshu');
INSERT INTO located_on VALUES ('Miyazaki','Miyazaki','J','Kyushu');
INSERT INTO located_on VALUES ('Cágliari','Sardegna','I','Sardegna');
INSERT INTO located_on VALUES ('Telde','Canarias','E','Gran Canaria');
INSERT INTO located_on VALUES ('Wigan','North West','GB','Great Britain');
INSERT INTO located_on VALUES ('Malang','Jawa Timur','RI','Java');
INSERT INTO located_on VALUES ('Northampton','East Midlands','GB','Great Britain');
INSERT INTO located_on VALUES ('Hiroshima','Hiroshima','J','Honshu');
INSERT INTO located_on VALUES ('Parañaque','Metro Manila','RP','Luzon');
INSERT INTO located_on VALUES ('Funabashi','Chiba','J','Honshu');
INSERT INTO located_on VALUES ('Preston','North West','GB','Great Britain');
INSERT INTO located_on VALUES ('Kashiwa','Chiba','J','Honshu');
INSERT INTO located_on VALUES ('Road Town','British Virgin Islands','BVI','Tortola');
INSERT INTO located_on VALUES ('Plymouth','Montserrat','MNTS','Montserrat');
INSERT INTO located_on VALUES ('Ponta Delgada','Azores','P','Sao Miguel');
INSERT INTO located_on VALUES ('Nukualofa','Tonga','TO','Tongatapu');
INSERT INTO located_on VALUES ('Aomori','Aomori','J','Honshu');
INSERT INTO located_on VALUES ('Mumbai','Maharashtra','IND','Salsette');
INSERT INTO located_on VALUES ('Newport','Wales','GB','Great Britain');
INSERT INTO located_on VALUES ('Kota Kinabalu','Sabah','MAL','Borneo');
INSERT INTO located_on VALUES ('Ambon','Maluku','RI','Ambon');
INSERT INTO located_on VALUES ('The Valley','Anguilla','AXA','Anguilla');
INSERT INTO located_on VALUES ('Kingstown','Saint Vincent and the Grenadines','WV','Saint Vincent');
INSERT INTO located_on VALUES ('Cabanatuan','Central Luzon','RP','Luzon');
INSERT INTO located_on VALUES ('Rochdale','North West','GB','Great Britain');
INSERT INTO located_on VALUES ('Cabuyao','Calabarzon','RP','Luzon');
INSERT INTO located_on VALUES ('Palikir','Micronesia','FSM','Pohnpei');
INSERT INTO located_on VALUES ('Salford','North West','GB','Great Britain');
INSERT INTO located_on VALUES ('Malolos','Central Luzon','RP','Luzon');
INSERT INTO located_on VALUES ('Guantánamo','Guantánamo','C','Cuba');
INSERT INTO located_on VALUES ('Labuan','Labuan','MAL','Labuan');
INSERT INTO located_on VALUES ('Manado','Sulawesi Utara','RI','Sulawesi');
INSERT INTO located_on VALUES ('Angeles','Central Luzon','RP','Luzon');
INSERT INTO located_on VALUES ('Chelmsford','East of England','GB','Great Britain');
INSERT INTO located_on VALUES ('Dunedin','New Zealand','NZ','Te Waka-a-Maui (South Island)');
INSERT INTO located_on VALUES ('Ternate','Maluku Utara','RI','Ternate');
INSERT INTO located_on VALUES ('Batam','Kepulauan Riau','RI','Batam');
INSERT INTO located_on VALUES ('Antananarivo','Madagascar','RM','Madagaskar');
INSERT INTO located_on VALUES ('Utsunomiya','Tochigi','J','Honshu');
INSERT INTO located_on VALUES ('Doncaster','Yorkshire and the Humber','GB','Great Britain');
INSERT INTO located_on VALUES ('São Luís','Maranhão','BR','Ilha de São Luís');
INSERT INTO located_on VALUES ('Hachioji','Tokyo','J','Honshu');
INSERT INTO located_on VALUES ('Hsinchu','Taiwan','RC','Taiwan');
INSERT INTO located_on VALUES ('Kawasaki','Kanagawa','J','Honshu');
INSERT INTO located_on VALUES ('Chania','Kritis','GR','Crete');
INSERT INTO located_on VALUES ('Gillingham','South East','GB','Great Britain');
INSERT INTO located_on VALUES ('Philipsburg','Sint Maarten','SX','St. Martin');
INSERT INTO located_on VALUES ('San Fernando','Central Luzon','RP','Luzon');
INSERT INTO located_on VALUES ('Saanich','British Columbia','CDN','Vancouver Island');
INSERT INTO located_on VALUES ('Puerto Plata','Dominican Republic','DOM','Hispaniola');
INSERT INTO located_on VALUES ('Kralendijk','Bonaire','NLB','Bonaire');
INSERT INTO located_on VALUES ('Thane','Maharashtra','IND','Salsette');
INSERT INTO located_on VALUES ('Siracusa','Sicilia','I','Sicilia');
INSERT INTO located_on VALUES ('Tarakan','Kalimantan Utara','RI','Borneo');
INSERT INTO located_on VALUES ('Taguig','Metro Manila','RP','Luzon');
INSERT INTO located_on VALUES ('Gateshead','North East','GB','Great Britain');
INSERT INTO located_on VALUES ('Bacolod','Western Visayas','RP','Negros');
INSERT INTO located_on VALUES ('Yokosuka','Kanagawa','J','Honshu');
INSERT INTO located_on VALUES ('La Habana','La Habana','C','Cuba');
INSERT INTO located_on VALUES ('Helsingør','Hovedstaden','DK','Seeland');
INSERT INTO located_on VALUES ('Pasay','Metro Manila','RP','Luzon');
INSERT INTO located_on VALUES ('Victoria','Malta','M','Gozo');
INSERT INTO located_on VALUES ('High Wycombe','South East','GB','Great Britain');
INSERT INTO located_on VALUES ('Changhua','Taiwan','RC','Taiwan');
INSERT INTO located_on VALUES ('Bayamo','Granma','C','Cuba');
INSERT INTO located_on VALUES ('Charlotte Amalie','Virgin Islands','VIRG','Saint Thomas');
INSERT INTO located_on VALUES ('Yaren','Nauru','NAU','Nauru');
INSERT INTO located_on VALUES ('Kerkyra','Ionion Nison','GR','Korfu');
INSERT INTO located_on VALUES ('Tokushima','Tokushima','J','Shikoku');
INSERT INTO located_on VALUES ('Gonaïves','Haiti','RH','Hispaniola');
INSERT INTO located_on VALUES ('Slough','South East','GB','Great Britain');
INSERT INTO located_on VALUES ('Oxford','South East','GB','Great Britain');
INSERT INTO located_on VALUES ('Batangas','Calabarzon','RP','Luzon');
INSERT INTO located_on VALUES ('Kirkwall','Scotland','GB','Orkney Mainland');
INSERT INTO located_on VALUES ('Chalkida','Stereas Elladas','GR','Euboea');
INSERT INTO located_on VALUES ('New Taipei','Taiwan','RC','Taiwan');
INSERT INTO located_on VALUES ('Palembang','Sumatera Selatan','RI','Sumatra');
INSERT INTO located_on VALUES ('Oldham','North West','GB','Great Britain');
INSERT INTO located_on VALUES ('West Island','Cocos Islands','COCO','Pulau Panjang');
INSERT INTO located_on VALUES ('Suva','Fiji','FJI','Viti Levu');
INSERT INTO located_on VALUES ('Kaohsiung','Taiwan','RC','Taiwan');
INSERT INTO located_on VALUES ('São Vicente','São Paulo','BR','Ilha de São Vicente');
INSERT INTO located_on VALUES ('Antipolo','Calabarzon','RP','Luzon');
INSERT INTO located_on VALUES ('Pétion-Ville','Haiti','RH','Hispaniola');
INSERT INTO located_on VALUES ('Oita','Oita','J','Kyushu');
INSERT INTO located_on VALUES ('Cebu','Central Visayas','RP','Cebu');
INSERT INTO located_on VALUES ('Kingston','Jamaica','JA','Jamaica');
INSERT INTO located_on VALUES ('Samarinda','Kalimantan Timur','RI','Borneo');
INSERT INTO located_on VALUES ('Matsue','Shimane','J','Honshu');
INSERT INTO located_on VALUES ('Taitung','Taiwan','RC','Taiwan');
INSERT INTO located_on VALUES ('Nara','Nara','J','Honshu');
INSERT INTO located_on VALUES ('Lucena','Calabarzon','RP','Luzon');
INSERT INTO located_on VALUES ('George Town','Cayman Islands','CAYM','Grand Cayman');
INSERT INTO located_on VALUES ('Basseterre','Saint Kitts and Nevis','KN','Saint Kitts');
INSERT INTO located_on VALUES ('San Andres','San Andrés, Providencia y Santa Catalina','CO','San Andres');
INSERT INTO located_on VALUES ('Južno-Sachalinsk','Sakhalin','R','Sachalin');
INSERT INTO located_on VALUES ('San Jose Del Monte','Central Luzon','RP','Luzon');
INSERT INTO located_on VALUES ('Copenhagen','Hovedstaden','DK','Seeland');
INSERT INTO located_on VALUES ('Eastbourne','South East','GB','Great Britain');
INSERT INTO located_on VALUES ('Imus','Calabarzon','RP','Luzon');
INSERT INTO located_on VALUES ('Victoria','Seychelles','SY','Mahe');
INSERT INTO located_on VALUES ('Majunga','Madagascar','RM','Madagaskar');
INSERT INTO located_on VALUES ('Hamilton','Bermuda','BERM','Grand Bermuda');
INSERT INTO located_on VALUES ('Grand Turk','Turks and Caicos Islands','TUCA','Grand Turk');
INSERT INTO located_on VALUES ('Gloucester','South West','GB','Great Britain');
INSERT INTO located_on VALUES ('Hagåtña','Guam','GUAM','Guam');
INSERT INTO located_on VALUES ('Southend-on-Sea','East of England','GB','Great Britain');
INSERT INTO located_on VALUES ('Cirebon','Jawa Barat','RI','Java');
INSERT INTO located_on VALUES ('Norwich','East of England','GB','Great Britain');
INSERT INTO located_on VALUES ('Roseau','Dominica','WD','Dominica');
INSERT INTO located_on VALUES ('Saga','Saga','J','Kyushu');
INSERT INTO located_on VALUES ('Huddersfield','Yorkshire and the Humber','GB','Great Britain');
INSERT INTO located_on VALUES ('Ushuaia','Tierra del Fuego','RA','Tierra del Fuego');
INSERT INTO located_on VALUES ('Wellington','New Zealand','NZ','Te Ika-a-Maui (North Island)');
INSERT INTO located_on VALUES ('Roxas','Western Visayas','RP','Panay');
INSERT INTO located_on VALUES ('Limerick','Ireland','IRL','Ireland');
INSERT INTO located_on VALUES ('Mamoutzou','Mayotte','MAYO','Mayotte');
INSERT INTO located_on VALUES ('Pangkal Pinang','Kepulauan Bangka Belitung','RI','Bangka');
INSERT INTO located_on VALUES ('Bandar Seri Begawan','Brunei','BRU','Borneo');
INSERT INTO located_on VALUES ('Kupang','Nusa Tenggara Timur','RI','Timor');
INSERT INTO located_on VALUES ('Derby','East Midlands','GB','Great Britain');
INSERT INTO located_on VALUES ('Hillerød','Hovedstaden','DK','Seeland');
INSERT INTO located_on VALUES ('Taoyuan','Taiwan','RC','Taiwan');
INSERT INTO located_on VALUES ('Banda Aceh','Aceh','RI','Sumatra');
INSERT INTO located_on VALUES ('Coventry','West Midlands','GB','Great Britain');
INSERT INTO located_on VALUES ('Sorø','Sjælland','DK','Seeland');
INSERT INTO located_on VALUES ('Georgetown','Pulau Pinang','MAL','Penang');
INSERT INTO located_on VALUES ('Biñan','Calabarzon','RP','Luzon');
INSERT INTO located_on VALUES ('Mkokotoni','Kaskazini Unguja','EAT','Sansibar');
INSERT INTO located_on VALUES ('Milton Keynes','South East','GB','Great Britain');
INSERT INTO located_on VALUES ('Tokyo','Tokyo','J','Honshu');
INSERT INTO located_on VALUES ('Binangonan','Calabarzon','RP','Luzon');
INSERT INTO located_on VALUES ('Birmingham','West Midlands','GB','Great Britain');
INSERT INTO located_on VALUES ('Fianarantsoa','Madagascar','RM','Madagaskar');
INSERT INTO located_on VALUES ('Puerto Princesa','Mimaropa','RP','Palawan');
INSERT INTO located_on VALUES ('Nassau','Bahamas','BS','New Providence');
INSERT INTO located_on VALUES ('San Pedro','Calabarzon','RP','Luzon');
INSERT INTO located_on VALUES ('Bristol','South West','GB','Great Britain');
INSERT INTO located_on VALUES ('Santiago','Dominican Republic','DOM','Hispaniola');
INSERT INTO located_on VALUES ('Matanzas','Matanzas','C','Cuba');
INSERT INTO located_on VALUES ('Manila','Metro Manila','RP','Luzon');
INSERT INTO located_on VALUES ('Wolverhampton','West Midlands','GB','Great Britain');
INSERT INTO located_on VALUES ('Stanley','Falkland Islands','FALK','East Falkland');
INSERT INTO located_on VALUES ('Papeete','French Polynesia','FPOL','Tahiti');
INSERT INTO located_on VALUES ('Jakarta','DKI Jakarta','RI','Java');
INSERT INTO located_on VALUES ('Vitória','Espírito Santo','BR','Ilha de Vitória');
INSERT INTO located_on VALUES ('Manchester','North West','GB','Great Britain');
INSERT INTO located_on VALUES ('Padang','Sumatera Barat','RI','Sumatra');
INSERT INTO located_on VALUES ('Ichikawa','Chiba','J','Honshu');
INSERT INTO located_on VALUES ('Niigata','Niigata','J','Honshu');
INSERT INTO located_on VALUES ('Mandaue','Central Visayas','RP','Cebu');
INSERT INTO located_on VALUES ('Gorontalo','Gorontalo','RI','Sulawesi');
INSERT INTO located_on VALUES ('Bournemouth','South West','GB','Great Britain');
INSERT INTO located_on VALUES ('Toliara','Madagascar','RM','Madagaskar');
INSERT INTO located_on VALUES ('Antsirabe','Madagascar','RM','Madagaskar');
INSERT INTO located_on VALUES ('Fukuyama','Hiroshima','J','Honshu');
INSERT INTO located_on VALUES ('Avarua','Cook Islands','COOK','Rarotonga');
INSERT INTO located_on VALUES ('Santa Rosa','Calabarzon','RP','Luzon');
INSERT INTO located_on VALUES ('Malabo','Insular','GQ','Bioko');
INSERT INTO located_on VALUES ('Gustavia','Saint Barthelemy','SBAR','St. Barthelemy');
INSERT INTO located_on VALUES ('Solihull','West Midlands','GB','Great Britain');
INSERT INTO located_on VALUES ('Port Louis','Mauritius','MS','Mauritius');
INSERT INTO located_on VALUES ('Tanjung Pinang','Kepulauan Riau','RI','Bintan');
INSERT INTO located_on VALUES ('Nueva Gerona','Isla de la Juventud','C','Isla de la Juventud');
INSERT INTO located_on VALUES ('Nuuk','Greenland','GL','Greenland');
INSERT INTO located_on VALUES ('Cainta','Calabarzon','RP','Luzon');
INSERT INTO located_on VALUES ('Fort-de-France','Martinique','MART','Martinique');
INSERT INTO located_on VALUES ('Adamstown','Pitcairn','PITC','Pitcairn');
INSERT INTO located_on VALUES ('Camagüey','Camagüey','C','Cuba');
INSERT INTO located_on VALUES ('Lefkosia','Cyprus','CY','Cyprus');
INSERT INTO located_on VALUES ('Lipa','Calabarzon','RP','Luzon');
INSERT INTO located_on VALUES ('Kochi','Kochi','J','Shikoku');
INSERT INTO located_on VALUES ('Plymouth','South West','GB','Great Britain');
INSERT INTO located_on VALUES ('San Carlos','Ilocos','RP','Luzon');
INSERT INTO located_on VALUES ('Honolulu','Hawaii','USA','Oahu');
INSERT INTO located_on VALUES ('Apia','Samoa','WS','Upolu');
INSERT INTO located_on VALUES ('Noumea','New Caledonia','NCL','Grande Terre');
INSERT INTO located_on VALUES ('Takamatsu','Kagawa','J','Shikoku');
INSERT INTO located_on VALUES ('Bandar Lampung','Lampung','RI','Sumatra');
INSERT INTO located_on VALUES ('Bacoor','Calabarzon','RP','Luzon');
INSERT INTO located_on VALUES ('Dili','Timor-Leste','TL','Timor');
INSERT INTO located_on VALUES ('St. John''s','Antigua and Barbuda','AG','Antigua');
INSERT INTO located_on VALUES ('Odense','Syddanmark','DK','Fünen');
INSERT INTO located_on VALUES ('Asahikawa','Hokkaido','J','Hokkaido');
INSERT INTO located_on VALUES ('Ermoupoli','Notioy Aigaioy','GR','Syros');
INSERT INTO located_on VALUES ('Pasig','Metro Manila','RP','Luzon');
INSERT INTO located_on VALUES ('Las Piñas','Metro Manila','RP','Luzon');
INSERT INTO located_on VALUES ('Stoke-on-Trent','West Midlands','GB','Great Britain');
INSERT INTO located_on VALUES ('San Mateo','Calabarzon','RP','Luzon');
INSERT INTO located_on VALUES ('Larnaka','Cyprus','CY','Cyprus');
INSERT INTO located_on VALUES ('Hamamatsu','Shizuoka','J','Honshu');
INSERT INTO located_on VALUES ('Kumamoto','Kumamoto','J','Kyushu');
INSERT INTO located_on VALUES ('Iraklio','Kritis','GR','Crete');
INSERT INTO located_on VALUES ('Banjul','Gambia','WAG','St. Mary''s Island');
INSERT INTO located_on VALUES ('Kobe','Hyogo','J','Honshu');
INSERT INTO located_on VALUES ('Saint-Denis','Reunion','REUN','Reunion');
INSERT INTO located_on VALUES ('Kofu','Yamanashi','J','Honshu');
INSERT INTO located_on VALUES ('Matsuyama','Ehime','J','Shikoku');
INSERT INTO located_on VALUES ('Kagoshima','Kagoshima','J','Kyushu');
INSERT INTO located_on VALUES ('Oranjestad','Aruba','ARU','Aruba');
INSERT INTO located_on VALUES ('Crawley','South East','GB','Great Britain');
INSERT INTO located_on VALUES ('Cheltenham','South West','GB','Great Britain');
INSERT INTO located_on VALUES ('Taichung','Taiwan','RC','Taiwan');
INSERT INTO located_on VALUES ('Sutton Coldfield','West Midlands','GB','Great Britain');
INSERT INTO located_on VALUES ('Ngerulmud','Palau','PAL','Babeldaob');
INSERT INTO located_on VALUES ('Santa Clara','Villa Clara','C','Cuba');
INSERT INTO located_on VALUES ('Ponce','Puerto Rico','PR','Puerto Rico');
INSERT INTO located_on VALUES ('Rhodes','Notioy Aigaioy','GR','Rhodos');
INSERT INTO located_on VALUES ('Brighton and Hove','South East','GB','Great Britain');
INSERT INTO located_on VALUES ('Higashiosaka','Osaka','J','Honshu');
INSERT INTO located_on VALUES ('Belfast','Northern Ireland','GB','Ireland');
INSERT INTO located_on VALUES ('Yokohama','Kanagawa','J','Honshu');
INSERT INTO located_on VALUES ('Kalookan','Metro Manila','RP','Luzon');
INSERT INTO located_on VALUES ('Cité Soleil','Haiti','RH','Hispaniola');
INSERT INTO located_on VALUES ('Carolina','Puerto Rico','PR','Puerto Rico');
INSERT INTO located_on VALUES ('Xiamen','Fujian','CN','Xiamen');
INSERT INTO located_on VALUES ('General Santos','Soccsksargen','RP','Mindanao');
INSERT INTO located_on VALUES ('St Helens','North West','GB','Great Britain');
INSERT INTO located_on VALUES ('Saint George''s','Grenada','WG','Grenada');
INSERT INTO located_on VALUES ('Amagasaki','Hyogo','J','Honshu');
INSERT INTO located_on VALUES ('Calamba','Calabarzon','RP','Luzon');
INSERT INTO located_on VALUES ('Kingston upon Hull','Yorkshire and the Humber','GB','Great Britain');
INSERT INTO located_on VALUES ('Leicester','East Midlands','GB','Great Britain');
INSERT INTO located_on VALUES ('Fujisawa','Kanagawa','J','Honshu');
INSERT INTO located_on VALUES ('Sibu','Sarawak','MAL','Borneo');
INSERT INTO located_on VALUES ('Tarlac','Central Luzon','RP','Luzon');
INSERT INTO located_on VALUES ('Victoria','British Columbia','CDN','Vancouver Island');
INSERT INTO located_on VALUES ('Hamilton','New Zealand','NZ','Te Ika-a-Maui (North Island)');
INSERT INTO located_on VALUES ('Jeju','South Korea','ROK','Jeju');
INSERT INTO located_on VALUES ('Chiba','Chiba','J','Honshu');
INSERT INTO located_on VALUES ('Portsmouth','South East','GB','Great Britain');
INSERT INTO located_on VALUES ('Taytay','Calabarzon','RP','Luzon');
INSERT INTO located_on VALUES ('Rodriguez','Calabarzon','RP','Luzon');
INSERT INTO located_on VALUES ('Jamestown','Saint Helena','HELX','Saint Helena');
INSERT INTO located_on VALUES ('Toledo','Central Visayas','RP','Cebu');
INSERT INTO located_on VALUES ('Marikina','Metro Manila','RP','Luzon');
INSERT INTO located_on VALUES ('Jambi','Jambi','RI','Sumatra');
INSERT INTO located_on VALUES ('Guarujá','São Paulo','BR','Ilha de Sãnto Amaro');
INSERT INTO located_on VALUES ('Longyearbyen','Svalbard','SVA','Svalbard');
INSERT INTO located_on VALUES ('Santos','São Paulo','BR','Ilha de São Vicente');
INSERT INTO located_on VALUES ('Jolo','Muslim Mindanao','RP','Jolo');
INSERT INTO located_on VALUES ('Zhoushan','Zhejiang','CN','Zhoushan');
INSERT INTO located_on VALUES ('Valencia','Northern Mindanao','RP','Mindanao');
INSERT INTO located_on VALUES ('Matsudo','Chiba','J','Honshu');
INSERT INTO located_on VALUES ('Tainan','Taiwan','RC','Taiwan');
INSERT INTO located_on VALUES ('Mito','Ibaraki','J','Honshu');
INSERT INTO located_on VALUES ('Galway','Ireland','IRL','Ireland');
INSERT INTO located_on VALUES ('Dasmarinas','Calabarzon','RP','Luzon');
INSERT INTO located_on VALUES ('Sheffield','Yorkshire and the Humber','GB','Great Britain');
INSERT INTO located_on VALUES ('Taipa-Coloane','Macao','MACX','Coloane');
INSERT INTO located_on VALUES ('Tawau','Sabah','MAL','Borneo');
INSERT INTO located_on VALUES ('Gander','Newfoundland and Labrador','CDN','Newfoundland');
INSERT INTO located_on VALUES ('Christchurch','New Zealand','NZ','Te Waka-a-Maui (South Island)');
INSERT INTO located_on VALUES ('New York','New York','USA','Long Island');
INSERT INTO located_on VALUES ('Surabaya','Jawa Timur','RI','Java');
INSERT INTO located_on VALUES ('Jhongli','Taiwan','RC','Taiwan');
INSERT INTO located_on VALUES ('Dundee','Scotland','GB','Great Britain');
INSERT INTO located_on VALUES ('Saipan','Northern Mariana Islands','NMIS','Saipan');
INSERT INTO located_on VALUES ('Sukabumi','Jawa Barat','RI','Java');
INSERT INTO located_on VALUES ('Reading','South East','GB','Great Britain');
INSERT INTO located_on VALUES ('Rikitea','French Polynesia','FPOL','Mangareva');
INSERT INTO located_on VALUES ('Port-of-Spain','Trinidad and Tobago','TT','Trinidad');
INSERT INTO located_on VALUES ('Saitama','Saitama','J','Honshu');
INSERT INTO located_on VALUES ('Phuket','Thailand','THA','Phuket');
INSERT INTO located_on VALUES ('Legazpi','Bicol','RP','Luzon');
INSERT INTO located_on VALUES ('Nagasaki','Nagasaki','J','Kyushu');
INSERT INTO located_on VALUES ('Tangerang','Banten','RI','Java');
INSERT INTO located_on VALUES ('Yogyakarta','DI Yogyakarta','RI','Java');
INSERT INTO located_on VALUES ('Fukushima','Fukushima','J','Honshu');
INSERT INTO located_on VALUES ('Douglas','Isle of Man','GBM','Isle of Man');
