INSERT INTO organization VALUES ('United Nations Interim Force in Lebanon','UNIFIL','New York','New York','USA','19-MAR-78');
INSERT INTO organization VALUES ('World Intellectual Property Organization','WIPO','Genève','Genève','CH','14-JUL-67');
INSERT INTO organization VALUES ('Council of Arab Economic Unity','CAEU','Amman','Jordan','JOR','02-JUN-57');
INSERT INTO organization VALUES ('Gulf Cooperation Council','GCC','Riyadh','Al-Riyadh','SA','25-MAY-81');
INSERT INTO organization VALUES ('Group of 3','G-3','','','','01-OCT-90');
INSERT INTO organization VALUES ('Nonaligned Movement','NAM','Jakarta','DKI Jakarta','RI','05-SEP-61');
INSERT INTO organization VALUES ('International Organization for Standardization','ISO','Genève','Genève','CH','01-FEB-47');
INSERT INTO organization VALUES ('International Organization for Migration','IOM','Genève','Genève','CH','05-DEC-51');
INSERT INTO organization VALUES ('Economic Community of West African States','ECOWAS','Lagos','Lagos','NGR','28-MAY-75');
INSERT INTO organization VALUES ('International Finance Corporation','IFC','Washington','District of Columbia','USA','25-MAY-55');
INSERT INTO organization VALUES ('East Asia Summit','EAS','','','','14-DEC-05');
INSERT INTO organization VALUES ('Australia Group','AG','','','','');
INSERT INTO organization VALUES ('European Union','EU','Bruxelles','Bruxelles','B','06-FEB-92');
INSERT INTO organization VALUES ('South Asian Association for Regional Cooperation','SAARC','Kathmandu','Nepal','NEP','08-DEC-85');
INSERT INTO organization VALUES ('African, Caribbean, and Pacific Group of States','ACP','Bruxelles','Bruxelles','B','05-JUN-75');
INSERT INTO organization VALUES ('International Criminal Court','ICCt','Den Haag','Zuid-Holland','NL','01-JUL-02');
INSERT INTO organization VALUES ('Community of Latin American and Caribbean States','CELAC','','','','22-FEB-10');
INSERT INTO organization VALUES ('Indian Ocean Commission','InOC','Port Louis','Mauritius','MS','21-DEC-82');
INSERT INTO organization VALUES ('International Criminal Police Organization','Interpol','Lyon','Auvergne-Rhône-Alpes','F','13-JUN-56');
INSERT INTO organization VALUES ('Organization of American States','OAS','Washington','District of Columbia','USA','13-APR-90');
INSERT INTO organization VALUES ('United Nations Mission for the Referendum in Western Sahara','MINURSO','New York','New York','USA','28-APR-91');
INSERT INTO organization VALUES ('Collective Security Treaty Organization','CSTO','Moskva','Moscow','R','07-OCT-02');
INSERT INTO organization VALUES ('United Nations High Commissioner for Refugees','UNHCR','Genève','Genève','CH','03-DEC-49');
INSERT INTO organization VALUES ('International Energy Agency','IEA','Paris','Île-de-France','F','14-NOV-74');
INSERT INTO organization VALUES ('Arab Monetary Fund','AMF','Abu Dhabi','United Arab Emirates','UAE','26-APR-76');
INSERT INTO organization VALUES ('World Federation of Trade Unions','WFTU','Praha','Praha','CZ','03-OCT-45');
INSERT INTO organization VALUES ('Economic and Monetary Community of Central Africa','CEMAC','Bangui','Central African Republic','RCA','08-DEC-64');
INSERT INTO organization VALUES ('European Bank for Reconstruction and Development','EBRD','London','London','GB','08-JAN-90');
INSERT INTO organization VALUES ('World Tourism Organization','UNWTO','Madrid','Madrid','E','01-JAN-75');
INSERT INTO organization VALUES ('Group of 5','G-5','','','','21-SEP-85');
INSERT INTO organization VALUES ('Group of 7','G-7','','','','21-SEP-85');
INSERT INTO organization VALUES ('Group of 15','G-15','Genève','Genève','CH','');
INSERT INTO organization VALUES ('Zangger Committee','ZC','','','','');
INSERT INTO organization VALUES ('United Nations Interim Security Force for Abyei','UNISFA','','','','26-JUN-11');
INSERT INTO organization VALUES ('Economic Community of the Great Lakes Countries','CEPGL','','','','19-SEP-76');
INSERT INTO organization VALUES ('Latin American Integration Association','LAIA','Montevideo','Uruguay','ROU','11-AUG-80');
INSERT INTO organization VALUES ('Colombo Plan','CP','Colombo','Sri Lanka','CL','01-JUL-51');
INSERT INTO organization VALUES ('International Bank for Reconstruction and Development','IBRD','Washington','District of Columbia','USA','22-JUL-44');
INSERT INTO organization VALUES ('United Nations Relief and Works Agency for Palestine Refugees in the Near East','UNRWA','Wien','Wien','A','08-DEC-49');
INSERT INTO organization VALUES ('General Confederation of Trade Unions','GCTU','Moskva','Moscow','R','15-APR-92');
INSERT INTO organization VALUES ('Group of 11','G-11','','','','22-JUN-84');
INSERT INTO organization VALUES ('World Trade Organization','WTO','','','','14-APR-94');
INSERT INTO organization VALUES ('Islamic Development Bank','IDB','Jeddah','Makkah Al-Mokarramah','SA','15-DEC-73');
INSERT INTO organization VALUES ('International Labor Organization','ILO','Genève','Genève','CH','27-JUN-19');
INSERT INTO organization VALUES ('Shanghai Cooperation Organization','SCO','Beijing','Beijing','CN','14-JUN-01');
INSERT INTO organization VALUES ('Southern African Development Community','SADC','Gaborone','Botswana','RB','16-AUG-92');
INSERT INTO organization VALUES ('Group of 20','G-20','','','','16-DEC-99');
INSERT INTO organization VALUES ('Benelux Union','Benelux','Bruxelles','Bruxelles','B','02-FEB-58');
INSERT INTO organization VALUES ('Alliance of Small Island States','AOSIS','','','','');
INSERT INTO organization VALUES ('Group of 10','G-10','Paris','Île-de-France','F','01-OCT-62');
INSERT INTO organization VALUES ('Black Sea Economic Cooperation Zone','BSEC','','','','24-JUN-92');
INSERT INTO organization VALUES ('Southern Cone Common Market','Mercosur','Buenos Aires','Distrito Federal','RA','26-MAR-91');
INSERT INTO organization VALUES ('United Nations Security Council','UNSC','Genève','Genève','CH','25-JUN-45');
INSERT INTO organization VALUES ('Inter-Parliamentary Union','IPU','','','','');
INSERT INTO organization VALUES ('United Nations Conference on Trade and Development','UNCTAD','','','','30-DEC-64');
INSERT INTO organization VALUES ('Economic Cooperation Organization','ECO','Tehran','Tehran','IR','28-JAN-85');
INSERT INTO organization VALUES ('Organization of Eastern Caribbean States','OECS','Castries','Saint Lucia','WL','17-JUN-81');
INSERT INTO organization VALUES ('Asian Development Bank','ADB','Manila','Metro Manila','RP','19-DEC-66');
INSERT INTO organization VALUES ('Commonwealth of Independent States','CIS','Minsk','Minsk City','BY','08-DEC-91');
INSERT INTO organization VALUES ('Central African States Development Bank','BDEAC','Brazzaville','Brazzaville','RCB','03-DEC-75');
INSERT INTO organization VALUES ('United Nations Peacekeeping Force in Cyprus','UNFICYP','New York','New York','USA','04-MAR-64');
INSERT INTO organization VALUES ('Inter-Governmental Authority on Development','IGAD','','','','');
INSERT INTO organization VALUES ('International Monetary Fund','IMF','Washington','District of Columbia','USA','22-JUL-44');
INSERT INTO organization VALUES ('United Nations Industrial Development Organization','UNIDO','Wien','Wien','A','16-NOV-66');
INSERT INTO organization VALUES ('Central European Initiative','CEI','Budapest','Budapest','H','10-NOV-89');
INSERT INTO organization VALUES ('East African Community','EAC','','','','');
INSERT INTO organization VALUES ('Group of 24','G-24','Bruxelles','Bruxelles','B','31-JUL-89');
INSERT INTO organization VALUES ('Comuinidade dos Paises de Lingua Portuguesa','CPLP','','','','');
INSERT INTO organization VALUES ('International Mobile Satellite Organization','IMSO','London','London','GB','14-APR-99');
INSERT INTO organization VALUES ('Euro-Atlantic Partnership Council','EAPC','Bruxelles','Bruxelles','B','07-NOV-91');
INSERT INTO organization VALUES ('Eurasian Economic Community','EurasEC','','','','');
INSERT INTO organization VALUES ('Organization of Petroleum Exporting Countries','OPEC','Wien','Wien','A','13-SEP-60');
INSERT INTO organization VALUES ('International Federation of Red Cross and Red Crescent Societies','IFRCS','Genève','Genève','CH','05-MAY-19');
INSERT INTO organization VALUES ('Extractive Industry Transparency Initiative','EITI','','','','');
INSERT INTO organization VALUES ('Council of Europe','CE','Strasbourg','Grand Est','F','05-MAY-49');
INSERT INTO organization VALUES ('European Central Bank','ECB','Frankfurt','Hessen','D','31-MAY-98');
INSERT INTO organization VALUES ('North Atlantic Treaty Organization','NATO','Bruxelles','Bruxelles','B','03-APR-49');
INSERT INTO organization VALUES ('Council of the Baltic Sea States','CBSS','','','','06-MAR-92');
INSERT INTO organization VALUES ('United Nations Integrated Mission in Timor-Leste','UNMIT','','','','24-AUG-06');
INSERT INTO organization VALUES ('Central American Bank for Economic Integration','BCIE','Tegucigalpa','Francisco Morazán','HN','13-DEC-60');
INSERT INTO organization VALUES ('Organization for Economic Cooperation and Development','OECD','Paris','Île-de-France','F','14-DEC-60');
INSERT INTO organization VALUES ('Secretariat of the Pacific Community','SPC','Noumea','New Caledonia','NCL','05-FEB-47');
INSERT INTO organization VALUES ('Nuclear Suppliers Group','NSG','Wien','Wien','A','');
INSERT INTO organization VALUES ('Organization of Arab Petroleum Exporting Countries','OAPEC','','','','08-JAN-68');
INSERT INTO organization VALUES ('United Nations Institute for Training and Research','UNITAR','','','','11-DEC-63');
INSERT INTO organization VALUES ('South Pacific Regional Trade and Economic Cooperation Agreement','Sparteca','','','','01-JAN-81');
INSERT INTO organization VALUES ('International Court of Justice','ICJ','Den Haag','Zuid-Holland','NL','25-JUN-45');
INSERT INTO organization VALUES ('Association of Southeast Asian Nations','ASEAN','Jakarta','DKI Jakarta','RI','07-AUG-67');
INSERT INTO organization VALUES ('United Nations Military Observer Group in India and Pakistan','UNMOGIP','New York','New York','USA','23-JAN-49');
INSERT INTO organization VALUES ('South Asia Co-operative Environment Program','SACEP','','','','');
INSERT INTO organization VALUES ('Economic and Monetary Union','EMU','Bruxelles','Bruxelles','B','06-FEB-92');
INSERT INTO organization VALUES ('Universal Postal Union','UPU','Bern','Bern','CH','09-OCT-74');
INSERT INTO organization VALUES ('European Organization for Nuclear Research','CERN','Genève','Genève','CH','01-JUL-53');
INSERT INTO organization VALUES ('Visegrád Group','V4','','','','15-FEB-91');
INSERT INTO organization VALUES ('Community of Democracies','CD','','','','26-JUN-00');
INSERT INTO organization VALUES ('Franc Zone','FZ','Paris','Île-de-France','F','20-DEC-45');
INSERT INTO organization VALUES ('Union of South American Nations','UNASUR','Quito','Ecuador','EC','23-MAY-08');
INSERT INTO organization VALUES ('ASEAN Regional Forum','ARF','','','','25-JUL-94');
INSERT INTO organization VALUES ('World Meteorological Organization','WMO','Genève','Genève','CH','11-OCT-47');
INSERT INTO organization VALUES ('Convention of the Southeast European Law Enforcement Center','SELEC','Bucureşti','Bucureşti','RO','07-OCT-11');
INSERT INTO organization VALUES ('Conference of Interaction and Confidence-Building Measures in Asia','CICA','Almaty','Almaty City','KZ','13-SEP-99');
INSERT INTO organization VALUES ('United Nations Mission in the Republic of South Sudan','UNMISS','','','','08-JUL-11');
INSERT INTO organization VALUES ('United Nations','UN','New York','New York','USA','25-JUN-45');
INSERT INTO organization VALUES ('Partnership for Peace','PFP','','','','10-JAN-94');
INSERT INTO organization VALUES ('Developing Eight','D-8','','','','14-JUN-97');
INSERT INTO organization VALUES ('Nordic Council','NC','Stockholm','Stockholm','S','16-MAR-52');
INSERT INTO organization VALUES ('Pacific Islands Forum','PIF','Suva','Fiji','FJI','04-AUG-71');
INSERT INTO organization VALUES ('European Investment Bank','EIB','Luxembourg','Luxembourg','L','25-MAR-57');
INSERT INTO organization VALUES ('Bank for International Settlements','BIS','Basel','Basel-Stadt','CH','19-JAN-30');
INSERT INTO organization VALUES ('Food and Agriculture Organization','FAO','Roma','Lazio','I','16-OCT-45');
INSERT INTO organization VALUES ('African Union/United Nations Hybrid Operation in Darfur','UNAMID','','','','31-JUL-07');
INSERT INTO organization VALUES ('International Trade Union Confederation','ITUC','Bruxelles','Bruxelles','B','02-NOV-06');
INSERT INTO organization VALUES ('United Nations Educational, Scientific, and Cultural Organization','UNESCO','Paris','Île-de-France','F','15-NOV-45');
INSERT INTO organization VALUES ('Council of the Entente','Entente','Abidjan','Abidjan','CI','29-MAY-59');
INSERT INTO organization VALUES ('United Nations Mission in Liberia','UNMIL','','','','18-SEP-03');
INSERT INTO organization VALUES ('Nordic Investment Bank','NIB','Helsinki','Uusimaa','SF','04-DEC-75');
INSERT INTO organization VALUES ('African Development Bank Group','AfDB','Abidjan','Abidjan','CI','09-SEP-64');
INSERT INTO organization VALUES ('Andean Community','CAN','Lima','Lima City','PE','26-MAY-69');
INSERT INTO organization VALUES ('African Union','AU','Addis Ababa','Addis Ababa','ETH','25-MAY-63');
INSERT INTO organization VALUES ('East African Development Bank','EADB','Kampala','Central','EAU','05-JUN-67');
INSERT INTO organization VALUES ('International Olympic Committee','IOC','Lausanne','Vaud','CH','22-JUN-94');
INSERT INTO organization VALUES ('United Nations Truce Supervision Organization','UNTSO','Yerushalayim','Yerushalayim','IL','01-MAY-48');
INSERT INTO organization VALUES ('International Telecommunication Satellite Organization','ITSO','','','','');
INSERT INTO organization VALUES ('International Telecommunication Union','ITU','Genève','Genève','CH','17-MAY-65');
INSERT INTO organization VALUES ('Nuclear Energy Agency','NEA','','','','31-JAN-58');
INSERT INTO organization VALUES ('Permanent Court of Arbitration','PCA','','','','29-JUL-99');
INSERT INTO organization VALUES ('Group of 77','G-77','','','','14-JUN-64');
INSERT INTO organization VALUES ('Arab Maghreb Union','AMU','Rabat','Rabat Sale Zemmour Zaer','MA','16-FEB-89');
INSERT INTO organization VALUES ('Bay of Bengal Initiative for Multi-Sectoral Technical and Economic Cooperation','BIMSTEC','','','','');
INSERT INTO organization VALUES ('Asia-Pacific Economic Cooperation','APEC','Singapore','Singapore','SGP','06-NOV-89');
INSERT INTO organization VALUES ('North American Free Trade Agreement','NAFTA','','','','17-DEC-92');
INSERT INTO organization VALUES ('Group of 9','G-9','','','','');
INSERT INTO organization VALUES ('United Nations Disengagement Observer Force','UNDOF','Dimashq','Dimashq','SYR','31-MAY-74');
INSERT INTO organization VALUES ('Arab Bank for Economic Development in Africa','ABEDA','Khartoum','Al-Kharṭūm','SUD','17-FEB-74');
INSERT INTO organization VALUES ('United Nations Organization Stabilization Mission in the Democratic Republic of the Congo','MONUSCO','','','','28-MAY-10');
INSERT INTO organization VALUES ('World Health Organization','WHO','Genève','Genève','CH','22-JUL-46');
INSERT INTO organization VALUES ('International Fund for Agricultural Development','IFAD','Roma','Lazio','I','01-NOV-74');
INSERT INTO organization VALUES ('Caribbean Development Bank','CDB','','','','18-OCT-69');
INSERT INTO organization VALUES ('Australia-New Zealand-United States Security Treaty','ANZUS','Canberra','Australia Capital Territory','AUS','31-AUG-51');
INSERT INTO organization VALUES ('Organization of Islamic Cooperation','OIC','Jeddah','Makkah Al-Mokarramah','SA','24-SEP-69');
INSERT INTO organization VALUES ('International Development Association','IDA','Washington','District of Columbia','USA','25-JAN-60');
INSERT INTO organization VALUES ('World Customs Organization','WCO','Bruxelles','Bruxelles','B','15-DEC-50');
INSERT INTO organization VALUES ('International Organization of the French-speaking World','OIF','Paris','Île-de-France','F','20-MAR-70');
INSERT INTO organization VALUES ('Multilateral Investment Guarantee Agency','MIGA','Washington','District of Columbia','USA','11-APR-88');
INSERT INTO organization VALUES ('Organization for the Prohibition of Chemical Weapons','OPCW','Den Haag','Zuid-Holland','NL','28-APR-97');
INSERT INTO organization VALUES ('United Nations Operation in Cote d''Ivoire','UNOCI','','','','26-FEB-04');
INSERT INTO organization VALUES ('International Chamber of Commerce','ICC','Paris','Île-de-France','F','01-JAN-19');
INSERT INTO organization VALUES ('Latin American and Caribbean Economic System','LAES','Caracas','Distrito Federal','YV','17-OCT-75');
INSERT INTO organization VALUES ('Agency for the Prohibition of Nuclear Weapons in Latin America and the Caribbean','OPANAL','Ciudad de México','Distrito Federal','MEX','13-FEB-67');
INSERT INTO organization VALUES ('Arab Fund for Economic and Social Development','AFESD','','','','16-MAY-68');
INSERT INTO organization VALUES ('Baltic Assembly','BA','Rīga','Latvia','LV','12-MAY-90');
INSERT INTO organization VALUES ('International Atomic Energy Agency','IAEA','Wien','Wien','A','26-OCT-56');
INSERT INTO organization VALUES ('Commonwealth','C','London','London','GB','31-DEC-31');
INSERT INTO organization VALUES ('Organization for Democracy and Economic Development','GUAM','Kyïv','Kyïv','UA','06-JUN-01');
INSERT INTO organization VALUES ('Central American Integration System','SICA','San Salvador','El Salvador','ES','13-DEC-91');
INSERT INTO organization VALUES ('International Hydrographic Organization','IHO','','','','');
INSERT INTO organization VALUES ('Southern African Customs Union','SACU','Windhoek','Namibia','NAM','11-DEC-69');
INSERT INTO organization VALUES ('Inter-American Development Bank','IADB','Washington','District of Columbia','USA','07-APR-59');
INSERT INTO organization VALUES ('Caribbean Community and Common Market','Caricom','Georgetown','Guyana','GUY','04-JUL-73');
INSERT INTO organization VALUES ('European Space Agency','ESA','Paris','Île-de-France','F','31-MAY-75');
INSERT INTO organization VALUES ('Financial Action Task Force','FATF','Paris','Île-de-France','F','15-JUL-89');
INSERT INTO organization VALUES ('Common Market for Eastern and Southern Africa','COMESA','Lusaka','Lusaka','Z','08-DEC-94');
INSERT INTO organization VALUES ('European Free Trade Association','EFTA','Genève','Genève','CH','03-JAN-60');
INSERT INTO organization VALUES ('International Civil Aviation Organization','ICAO','Montréal','Quebec','CDN','07-DEC-44');
INSERT INTO organization VALUES ('Organization for Security and Cooperation in Europe','OSCE','Wien','Wien','A','31-DEC-94');
INSERT INTO organization VALUES ('International Maritime Organization','IMO','London','London','GB','06-MAR-48');
INSERT INTO organization VALUES ('Group of 8','G-8','','','','01-OCT-75');
INSERT INTO organization VALUES ('League of Arab States','LAS','Al Qahirah','Egypt','ET','22-MAR-45');
INSERT INTO organization VALUES ('Central American Common Market','CACM','Ciudad de Guatemala','Guatemala','GCA','13-DEC-60');
