INSERT INTO politics VALUES ('E','01-JAN-92','','','parliamentary monarchy');
INSERT INTO politics VALUES ('CH','01-JAN-91','','','formally a confederation but similar in structure to a federal republic');
INSERT INTO politics VALUES ('ANG','11-NOV-75','P','','republic; multiparty presidential regime');
INSERT INTO politics VALUES ('K','09-NOV-49','F','','multiparty democracy under a constitutional monarchy');
INSERT INTO politics VALUES ('GBZ','','','GB','dependent territory of the UK');
INSERT INTO politics VALUES ('DOM','27-FEB-44','RH','','democratic republic');
INSERT INTO politics VALUES ('FPOL','','','F','parliamentary representative democratic French overseas collectivity');
INSERT INTO politics VALUES ('KN','19-SEP-83','GB','','parliamentary democracy and a Commonwealth realm');
INSERT INTO politics VALUES ('AZ','30-AUG-91','Soviet Union','','republic');
INSERT INTO politics VALUES ('BHT','08-AUG-49','GB','','constitutional monarchy');
INSERT INTO politics VALUES ('MAL','31-AUG-57','GB','','constitutional monarchy');
INSERT INTO politics VALUES ('CGO','30-JUN-60','B','','republic');
INSERT INTO politics VALUES ('SY','29-JUN-76','GB','','republic');
INSERT INTO politics VALUES ('GH','06-MAR-57','GB','','constitutional democracy');
INSERT INTO politics VALUES ('SRB','11-APR-92','Yugoslavia','','republic');
INSERT INTO politics VALUES ('GBM','','','GB','parliamentary democracy');
INSERT INTO politics VALUES ('AFG','19-AUG-19','GB','','Islamic republic');
INSERT INTO politics VALUES ('WAG','18-FEB-65','GB','','republic');
INSERT INTO politics VALUES ('TCH','11-AUG-60','F','','republic');
INSERT INTO politics VALUES ('TT','31-AUG-62','GB','','parliamentary democracy');
INSERT INTO politics VALUES ('MNE','03-JUN-06','SRB','','republic');
INSERT INTO politics VALUES ('SF','06-DEC-17','R','','republic');
INSERT INTO politics VALUES ('REUN','','','F','overseas department of France');
INSERT INTO politics VALUES ('CDN','01-JUL-67','GB','','a parliamentary democracy, a federation, and a constitutional monarchy');
INSERT INTO politics VALUES ('USA','04-JUL-76','GB','','constitution-based federal republic; strong democratic tradition');
INSERT INTO politics VALUES ('COCO','','','AUS','territory of Australia');
INSERT INTO politics VALUES ('MNTS','','','GB','British Overseas Territories');
INSERT INTO politics VALUES ('AUS','01-JAN-01','GB','','federal parliamentary democracy and a Commonwealth realm');
INSERT INTO politics VALUES ('I','17-MAR-61','','','republic');
INSERT INTO politics VALUES ('GL','','','DK','parliamentary democracy within a constitutional monarchy');
INSERT INTO politics VALUES ('CAYM','','','GB','parliamentary democracy');
INSERT INTO politics VALUES ('AL','28-NOV-12','Ottoman Empire','','parliamentary democracy');
INSERT INTO politics VALUES ('ARU','','','NL','parliamentary democracy');
INSERT INTO politics VALUES ('S','','','','constitutional monarchy');
INSERT INTO politics VALUES ('GCA','15-SEP-21','E','','constitutional democratic republic');
INSERT INTO politics VALUES ('HN','15-SEP-21','E','','democratic constitutional republic');
INSERT INTO politics VALUES ('FALK','','','GB','British Overseas Territories');
INSERT INTO politics VALUES ('GAZA','','','','');
INSERT INTO politics VALUES ('WG','07-FEB-74','GB','','parliamentary democracy and a Commonwealth realm');
INSERT INTO politics VALUES ('EC','24-MAY-22','E','','republic');
INSERT INTO politics VALUES ('HK','','','CN','limited democracy');
INSERT INTO politics VALUES ('NORF','','','AUS','territory of Australia');
INSERT INTO politics VALUES ('KIR','12-JUL-79','GB','','republic');
INSERT INTO politics VALUES ('KWT','19-JUN-61','GB','','constitutional emirate');
INSERT INTO politics VALUES ('NIUE','19-OCT-74','NZ','','self-governing parliamentary democracy');
INSERT INTO politics VALUES ('LAR','24-DEC-51','I','','operates under a transitional government');
INSERT INTO politics VALUES ('SGP','09-AUG-65','MAL','','parliamentary republic');
INSERT INTO politics VALUES ('NIC','15-SEP-21','E','','republic');
INSERT INTO politics VALUES ('CO','20-JUL-10','E','','republic; executive branch dominates government structure');
INSERT INTO politics VALUES ('CY','16-AUG-60','GB','','republic');
INSERT INTO politics VALUES ('VIRG','','','USA','organized');
INSERT INTO politics VALUES ('TR','29-OCT-23','Ottoman Empire','','republican parliamentary democracy');
INSERT INTO politics VALUES ('BG','22-SEP-08','Ottoman Empire','','parliamentary democracy');
INSERT INTO politics VALUES ('UAE','02-DEC-71','GB','','federation with specified powers delegated to the UAE federal government and other powers reserved to member emirates');
INSERT INTO politics VALUES ('NMIS','','','USA','commonwealth; self-governing with locally elected governor, lieutenant governor, and legislature');
INSERT INTO politics VALUES ('GUB','10-SEP-74','P','','republic');
INSERT INTO politics VALUES ('MEX','16-SEP-10','E','','federal republic');
INSERT INTO politics VALUES ('LV','06-SEP-91','Soviet Union','','parliamentary democracy');
INSERT INTO politics VALUES ('ROU','25-AUG-28','BR','','constitutional republic');
INSERT INTO politics VALUES ('RCA','13-AUG-60','F','','republic');
INSERT INTO politics VALUES ('IS','17-JUN-44','DK','','constitutional republic');
INSERT INTO politics VALUES ('CL','04-FEB-48','GB','','republic');
INSERT INTO politics VALUES ('BY','25-AUG-91','Soviet Union','','republic in name, although in fact a dictatorship');
INSERT INTO politics VALUES ('CEU','','','E','dependent territory of Spain');
INSERT INTO politics VALUES ('SVA','','','N','territory of Norway administered by the Ministry of Industry');
INSERT INTO politics VALUES ('SA','23-SEP-32','','','monarchy');
INSERT INTO politics VALUES ('RP','04-JUL-46','USA','','republic');
INSERT INTO politics VALUES ('NGR','01-OCT-60','GB','','federal republic');
INSERT INTO politics VALUES ('SUD','01-JAN-56','ET','','federal republic');
INSERT INTO politics VALUES ('TOK','','','NZ','');
INSERT INTO politics VALUES ('C','20-MAY-02','E','','Communist state');
INSERT INTO politics VALUES ('SX','','','NL','parliamentary');
INSERT INTO politics VALUES ('M','21-SEP-64','GB','','republic');
INSERT INTO politics VALUES ('GUAD','','','F','overseas department of France');
INSERT INTO politics VALUES ('SLO','25-JUN-91','Yugoslavia','','parliamentary republic');
INSERT INTO politics VALUES ('RL','22-NOV-43','United Nations','','republic');
INSERT INTO politics VALUES ('BD','16-DEC-71','PK','','parliamentary democracy');
INSERT INTO politics VALUES ('ETH','','','','federal republic');
INSERT INTO politics VALUES ('MAYO','','','F','territorial collectivity of France');
INSERT INTO politics VALUES ('COM','06-JUL-75','F','','republic');
INSERT INTO politics VALUES ('BRU','01-JAN-84','GB','','constitutional sultanate (locally known as Malay Islamic Monarchy)');
INSERT INTO politics VALUES ('MD','27-AUG-91','Soviet Union','','republic');
INSERT INTO politics VALUES ('SK','01-JAN-93','Czechoslovakia','','parliamentary democracy');
INSERT INTO politics VALUES ('PK','14-AUG-47','GB','','federal republic');
INSERT INTO politics VALUES ('NLB','','','NL','democracy');
INSERT INTO politics VALUES ('TO','04-JUN-70','GB','','constitutional monarchy');
INSERT INTO politics VALUES ('BVI','','','GB','British Overseas Territories');
INSERT INTO politics VALUES ('J','','','','a parliamentary government with a constitutional monarchy');
INSERT INTO politics VALUES ('AG','01-NOV-81','GB','','constitutional monarchy with a parliamentary system of government and a Commonwealth realm');
INSERT INTO politics VALUES ('IND','15-AUG-47','GB','','federal republic');
INSERT INTO politics VALUES ('RH','01-JAN-04','F','','republic');
INSERT INTO politics VALUES ('RSM','01-JAN-01','','','republic');
INSERT INTO politics VALUES ('SOL','07-JUL-78','GB','','parliamentary democracy and a Commonwealth realm');
INSERT INTO politics VALUES ('CI','07-AUG-60','F','','republic; multiparty presidential regime established 1960');
INSERT INTO politics VALUES ('MS','12-MAR-68','GB','','parliamentary democracy');
INSERT INTO politics VALUES ('SMAR','','','F','overseas collectivity of France');
INSERT INTO politics VALUES ('CN','','','','Socialist republic');
INSERT INTO politics VALUES ('EST','06-SEP-91','Soviet Union','','parliamentary republic');
INSERT INTO politics VALUES ('SN','20-AUG-60','F','','republic');
INSERT INTO politics VALUES ('TUV','01-OCT-78','GB','','parliamentary democracy and a Commonwealth realm');
INSERT INTO politics VALUES ('Q','03-SEP-71','GB','','emirate');
INSERT INTO politics VALUES ('RWA','01-JUL-62','United Nations','','republic; presidential, multiparty system');
INSERT INTO politics VALUES ('EAT','26-APR-64','GB','','republic');
INSERT INTO politics VALUES ('EAK','12-DEC-63','GB','','republic');
INSERT INTO politics VALUES ('PAL','01-OCT-94','United Nations','','constitutional government in free association with the US');
INSERT INTO politics VALUES ('WS','01-JAN-62','United Nations','','parliamentary democracy');
INSERT INTO politics VALUES ('RA','09-JUL-16','E','','republic');
INSERT INTO politics VALUES ('HR','25-JUN-91','Yugoslavia','','parliamentary democracy');
INSERT INTO politics VALUES ('RIM','28-NOV-60','F','','military junta');
INSERT INTO politics VALUES ('WSA','','','','legal status of territory and question of sovereignty unresolved');
INSERT INTO politics VALUES ('PY','14-MAY-11','E','','constitutional republic');
INSERT INTO politics VALUES ('MEL','','','E','dependent territory of Spain');
INSERT INTO politics VALUES ('GBG','','','GB','parliamentary democracy');
INSERT INTO politics VALUES ('MART','','','F','overseas department of France');
INSERT INTO politics VALUES ('TJ','09-SEP-91','Soviet Union','','republic');
INSERT INTO politics VALUES ('TL','20-MAY-02','RI','','republic');
INSERT INTO politics VALUES ('UZ','31-AUG-91','Soviet Union','','republic; authoritarian presidential rule with little power outside the executive branch');
INSERT INTO politics VALUES ('VN','02-SEP-45','F','','Communist state');
INSERT INTO politics VALUES ('RN','03-AUG-60','F','','republic');
INSERT INTO politics VALUES ('SO','01-JUL-60','GB','','in the process of building a federal parliamentary republic');
INSERT INTO politics VALUES ('NAM','21-MAR-90','United Nations','','republic');
INSERT INTO politics VALUES ('GR','01-JAN-29','Ottoman Empire','','parliamentary republic');
INSERT INTO politics VALUES ('DK','','','','constitutional monarchy');
INSERT INTO politics VALUES ('DJI','27-JUN-77','F','','republic');
INSERT INTO politics VALUES ('SME','25-NOV-75','NL','','constitutional democracy');
INSERT INTO politics VALUES ('BF','05-AUG-60','F','','parliamentary republic');
INSERT INTO politics VALUES ('NL','01-JAN-79','E','','constitutional monarchy');
INSERT INTO politics VALUES ('WV','27-OCT-79','GB','','parliamentary democracy and a Commonwealth realm');
INSERT INTO politics VALUES ('IR','','','','theocratic republic');
INSERT INTO politics VALUES ('WF','','','F','parliamentary representative democratic French overseas collectivity');
INSERT INTO politics VALUES ('KZ','16-DEC-91','Soviet Union','','republic; authoritarian presidential rule, with little power outside the executive branch');
INSERT INTO politics VALUES ('LT','06-SEP-91','Soviet Union','','parliamentary democracy');
INSERT INTO politics VALUES ('FJI','10-OCT-70','GB','','republic');
INSERT INTO politics VALUES ('GQ','12-OCT-68','E','','republic');
INSERT INTO politics VALUES ('WD','03-NOV-78','GB','','parliamentary democracy');
INSERT INTO politics VALUES ('BRN','15-AUG-71','GB','','constitutional monarchy');
INSERT INTO politics VALUES ('EAU','09-OCT-62','GB','','republic');
INSERT INTO politics VALUES ('BZ','21-SEP-81','GB','','parliamentary democracy and a Commonwealth realm');
INSERT INTO politics VALUES ('RO','09-MAY-77','Ottoman Empire','','republic');
INSERT INTO politics VALUES ('MA','02-MAR-56','F','','constitutional monarchy');
INSERT INTO politics VALUES ('GUY','26-MAY-66','GB','','republic');
INSERT INTO politics VALUES ('RI','17-AUG-45','NL','','republic');
INSERT INTO politics VALUES ('LB','26-JUL-47','','','republic');
INSERT INTO politics VALUES ('CV','05-JUL-75','P','','republic');
INSERT INTO politics VALUES ('MV','26-JUL-65','GB','','republic');
INSERT INTO politics VALUES ('IRL','06-DEC-21','GB','','republic, parliamentary democracy');
INSERT INTO politics VALUES ('LS','04-OCT-66','GB','','parliamentary constitutional monarchy');
INSERT INTO politics VALUES ('CZ','01-JAN-93','Czechoslovakia','','parliamentary democracy');
INSERT INTO politics VALUES ('JOR','25-MAY-46','United Nations','','constitutional monarchy');
INSERT INTO politics VALUES ('GE','09-APR-91','Soviet Union','','republic');
INSERT INTO politics VALUES ('XMAS','','','AUS','territory of Australia');
INSERT INTO politics VALUES ('IL','14-MAY-48','United Nations','','parliamentary democracy');
INSERT INTO politics VALUES ('FGU','','','F','overseas department of France');
INSERT INTO politics VALUES ('B','04-OCT-30','NL','','federal parliamentary democracy under a constitutional monarchy');
INSERT INTO politics VALUES ('MOC','25-JUN-75','P','','republic');
INSERT INTO politics VALUES ('D','18-JAN-71','','','federal republic');
INSERT INTO politics VALUES ('MNG','13-MAR-21','CN','','parliamentary');
INSERT INTO politics VALUES ('PE','28-JUL-21','E','','constitutional republic');
INSERT INTO politics VALUES ('Z','24-OCT-64','GB','','republic');
INSERT INTO politics VALUES ('MW','06-JUL-64','GB','','multiparty democracy');
INSERT INTO politics VALUES ('ROK','15-AUG-45','J','','republic');
INSERT INTO politics VALUES ('IRQ','03-OCT-32','United Nations','','parliamentary democracy');
INSERT INTO politics VALUES ('MH','21-OCT-86','United Nations','','constitutional government in free association with the US');
INSERT INTO politics VALUES ('RM','26-JUN-60','F','','republic');
INSERT INTO politics VALUES ('G','17-AUG-60','F','','republic; multiparty presidential regime');
INSERT INTO politics VALUES ('KP','15-AUG-45','J','','Communist state one-man dictatorship');
INSERT INTO politics VALUES ('WL','22-FEB-79','GB','','parliamentary democracy and a Commonwealth realm');
INSERT INTO politics VALUES ('V','11-FEB-29','I','','monarchical sacerdotal state');
INSERT INTO politics VALUES ('SYR','17-APR-46','United Nations','','republic under an authoritarian regime');
INSERT INTO politics VALUES ('HELX','','','GB','British Overseas Territories');
INSERT INTO politics VALUES ('YE','22-MAY-90','Merger of North/South Yemen','','republic');
INSERT INTO politics VALUES ('MC','01-JAN-19','','','constitutional monarchy');
INSERT INTO politics VALUES ('BS','10-JUL-73','GB','','constitutional parliamentary democracy and a Commonwealth realm');
INSERT INTO politics VALUES ('N','26-OCT-05','S','','constitutional monarchy');
INSERT INTO politics VALUES ('TM','27-OCT-91','Soviet Union','','authoritarian presidential rule');
INSERT INTO politics VALUES ('ZW','18-APR-80','GB','','parliamentary democracy');
INSERT INTO politics VALUES ('MACX','','','CN','limited democracy');
INSERT INTO politics VALUES ('RCB','15-AUG-60','F','','republic');
INSERT INTO politics VALUES ('UA','01-DEC-91','Soviet Union','','republic');
INSERT INTO politics VALUES ('MK','17-SEP-91','Yugoslavia','','parliamentary democracy');
INSERT INTO politics VALUES ('KG','31-AUG-91','Soviet Union','','republic');
INSERT INTO politics VALUES ('PNG','16-SEP-75','United Nations','','constitutional parliamentary democracy and a Commonwealth realm');
INSERT INTO politics VALUES ('FL','12-JUL-06','Holy Roman Empire','','hereditary constitutional monarchy');
INSERT INTO politics VALUES ('GBJ','','','GB','parliamentary democracy');
INSERT INTO politics VALUES ('COOK','04-AUG-65','NZ','','self-governing parliamentary democracy');
INSERT INTO politics VALUES ('PA','03-NOV-03','CO','','constitutional democracy');
INSERT INTO politics VALUES ('CR','15-SEP-21','E','','democratic republic');
INSERT INTO politics VALUES ('ES','15-SEP-21','E','','republic');
INSERT INTO politics VALUES ('PL','11-NOV-18','','','republic');
INSERT INTO politics VALUES ('P','25-JUL-39','E','','republic; parliamentary democracy');
INSERT INTO politics VALUES ('OM','01-JAN-50','P','','monarchy');
INSERT INTO politics VALUES ('RB','30-SEP-66','GB','','parliamentary republic');
INSERT INTO politics VALUES ('FO','','','DK','part of the Danish realm');
INSERT INTO politics VALUES ('LAO','19-JUL-49','F','','Communist state');
INSERT INTO politics VALUES ('BIH','01-APR-92','Yugoslavia','','emerging federal democratic republic');
INSERT INTO politics VALUES ('BOL','06-AUG-25','E','','republic; Social Unitarian State');
INSERT INTO politics VALUES ('PITC','','','GB','British Overseas Territories');
INSERT INTO politics VALUES ('SBAR','','','F','overseas collectivity of France');
INSERT INTO politics VALUES ('A','12-NOV-18','Austria-Hungary','','federal republic');
INSERT INTO politics VALUES ('THA','01-JAN-38','','','constitutional monarchy');
INSERT INTO politics VALUES ('NAU','31-JAN-68','United Nations','','republic');
INSERT INTO politics VALUES ('RG','02-OCT-58','F','','republic');
INSERT INTO politics VALUES ('BEN','01-AUG-60','F','','republic');
INSERT INTO politics VALUES ('CAM','01-JAN-60','United Nations','','republic; multiparty presidential regime');
INSERT INTO politics VALUES ('SD','06-SEP-68','GB','','monarchy');
INSERT INTO politics VALUES ('BERM','','','GB','parliamentary; self-governing territory');
INSERT INTO politics VALUES ('STP','12-JUL-75','P','','republic');
INSERT INTO politics VALUES ('SPMI','','','F','parliamentary representative democracy');
INSERT INTO politics VALUES ('WB','','','','');
INSERT INTO politics VALUES ('PR','','','USA','commonwealth');
INSERT INTO politics VALUES ('ET','28-FEB-22','GB','','republic');
INSERT INTO politics VALUES ('L','24-NOV-90','NL','','constitutional monarchy');
INSERT INTO politics VALUES ('JA','06-AUG-62','GB','','constitutional parliamentary democracy and a Commonwealth realm');
INSERT INTO politics VALUES ('CUR','','','NL','parliamentary');
INSERT INTO politics VALUES ('TUCA','','','GB','British Overseas Territories');
INSERT INTO politics VALUES ('AND','08-SEP-78','','','parliamentary democracy that retains as its chiefs of state a co-principality');
INSERT INTO politics VALUES ('GB','01-JAN-01','','','constitutional monarchy and Commonwealth realm');
INSERT INTO politics VALUES ('SLE','27-APR-61','GB','','constitutional democracy');
INSERT INTO politics VALUES ('RMM','22-SEP-60','F','','republic');
INSERT INTO politics VALUES ('TN','20-MAR-56','F','','republic');
INSERT INTO politics VALUES ('F','','','','republic');
INSERT INTO politics VALUES ('FSM','03-NOV-86','United Nations','','constitutional government in free association with the US');
INSERT INTO politics VALUES ('NEP','01-JAN-68','','','federal democratic republic');
INSERT INTO politics VALUES ('ARM','28-MAY-18','Soviet Union','','republic');
INSERT INTO politics VALUES ('VU','30-JUL-80','F','','parliamentary republic');
INSERT INTO politics VALUES ('AMSA','','','USA','unincorporated and unorganized territory of the US');
INSERT INTO politics VALUES ('AXA','','','GB','British Overseas Territories');
INSERT INTO politics VALUES ('BDS','30-NOV-66','GB','','parliamentary democracy and a Commonwealth realm');
INSERT INTO politics VALUES ('NZ','26-SEP-07','GB','','parliamentary democracy and a Commonwealth realm');
INSERT INTO politics VALUES ('RT','27-APR-60','F','','republic under transition to multiparty democratic rule');
INSERT INTO politics VALUES ('MYA','04-JAN-48','GB','','parliamentary government took power in March 2011');
INSERT INTO politics VALUES ('KOS','17-FEB-08','SRB','','republic');
INSERT INTO politics VALUES ('RSA','31-MAY-10','GB','','republic');
INSERT INTO politics VALUES ('BI','01-JUL-62','United Nations','','republic');
INSERT INTO politics VALUES ('ER','27-MAY-93','ETH','','transitional government');
INSERT INTO politics VALUES ('RCH','18-SEP-10','E','','republic');
INSERT INTO politics VALUES ('BR','07-SEP-22','P','','federal republic');
INSERT INTO politics VALUES ('GUAM','','','USA','organized');
INSERT INTO politics VALUES ('NCL','','','F','parliamentary representative democracy');
INSERT INTO politics VALUES ('H','18-NOV-18','Austria-Hungary','','parliamentary democracy');
INSERT INTO politics VALUES ('SSD','09-JUL-11','SUD','','republic');
INSERT INTO politics VALUES ('YV','05-JUL-11','E','','federal republic');
INSERT INTO politics VALUES ('RC','01-OCT-49','','','multiparty democracy');
INSERT INTO politics VALUES ('DZ','05-JUL-62','F','','republic');
INSERT INTO politics VALUES ('R','24-AUG-91','Soviet Union','','federation');
