INSERT INTO province_other_name (province_name,country_code,province_other_name) VALUES ('Jazan','SA','Jizan');
INSERT INTO province_other_name (province_name,country_code,province_other_name) VALUES ('Magwe','MYA','Magway');
INSERT INTO province_other_name (province_name,country_code,province_other_name) VALUES ('Duhouk','IRQ','Dahuk');
INSERT INTO province_other_name (province_name,country_code,province_other_name) VALUES ('Gilan','IR','Gillan');
INSERT INTO province_other_name (province_name,country_code,province_other_name) VALUES ('Al-Kharṭūm','SUD','Khartoum');
INSERT INTO province_other_name (province_name,country_code,province_other_name) VALUES ('Sankt-Peterburg','R','St. Peterburg');
INSERT INTO province_other_name (province_name,country_code,province_other_name) VALUES ('An-Nīl al-Azraq','SUD','Blue Nile');
INSERT INTO province_other_name (province_name,country_code,province_other_name) VALUES ('Shamāl Kurdufān','SUD','North Kordofan');
INSERT INTO province_other_name (province_name,country_code,province_other_name) VALUES ('Nizhnii Novgorodskaya','R','Nizhny Novgorodskaya');
INSERT INTO province_other_name (province_name,country_code,province_other_name) VALUES ('Euskadi','E','País Vasco');
INSERT INTO province_other_name (province_name,country_code,province_other_name) VALUES ('Afyonkarahisar','TR','Afyon');
INSERT INTO province_other_name (province_name,country_code,province_other_name) VALUES ('Kerbela','IRQ','Karbala');
INSERT INTO province_other_name (province_name,country_code,province_other_name) VALUES ('Gharb al-Dārfūr','SUD','West Darfur');
INSERT INTO province_other_name (province_name,country_code,province_other_name) VALUES ('Gumma','J','Gunma');
INSERT INTO province_other_name (province_name,country_code,province_other_name) VALUES ('Toshkent','UZ','Tashkent');
INSERT INTO province_other_name (province_name,country_code,province_other_name) VALUES ('Hamedan','IR','Hamadan');
INSERT INTO province_other_name (province_name,country_code,province_other_name) VALUES ('Yerushalayim','IL','Jerusalem');
INSERT INTO province_other_name (province_name,country_code,province_other_name) VALUES ('Janūb Kurdufān','SUD','South Kordofan');
INSERT INTO province_other_name (province_name,country_code,province_other_name) VALUES ('Nahr an-Nīl','SUD','River Nile');
INSERT INTO province_other_name (province_name,country_code,province_other_name) VALUES ('Samarqand','UZ','Samarkand');
INSERT INTO province_other_name (province_name,country_code,province_other_name) VALUES ('Shamāl Dārfūr','SUD','North Darfur');
INSERT INTO province_other_name (province_name,country_code,province_other_name) VALUES ('Durango','MEX','Victoria de Durango');
INSERT INTO province_other_name (province_name,country_code,province_other_name) VALUES ('Gharb Kurdufān','SUD','West Kordofan');
INSERT INTO province_other_name (province_name,country_code,province_other_name) VALUES ('Ticino','CH','Tessin');
INSERT INTO province_other_name (province_name,country_code,province_other_name) VALUES ('Neuchâtel','CH','Neuenburg');
INSERT INTO province_other_name (province_name,country_code,province_other_name) VALUES ('Karaganda','KZ','Karagandy');
INSERT INTO province_other_name (province_name,country_code,province_other_name) VALUES ('Buxoro','UZ','Bukhara');
INSERT INTO province_other_name (province_name,country_code,province_other_name) VALUES ('San Andrés, Providencia y Santa Catalina','CO','San Andres y Providencia');
INSERT INTO province_other_name (province_name,country_code,province_other_name) VALUES ('Rakhine','MYA','Arakan');
INSERT INTO province_other_name (province_name,country_code,province_other_name) VALUES ('Al-Baḥr al-Aḥmar','SUD','Red Sea');
INSERT INTO province_other_name (province_name,country_code,province_other_name) VALUES ('Wasaṭ Dārfūr','SUD','Central Darfur');
INSERT INTO province_other_name (province_name,country_code,province_other_name) VALUES ('Janūb Dārfūr','SUD','South Darfur');
INSERT INTO province_other_name (province_name,country_code,province_other_name) VALUES ('Kurdestan','IR','Kordestan');
INSERT INTO province_other_name (province_name,country_code,province_other_name) VALUES ('Fribourg','CH','Freiburg');
INSERT INTO province_other_name (province_name,country_code,province_other_name) VALUES ('Saratovskaya','R','Saratov');
INSERT INTO province_other_name (province_name,country_code,province_other_name) VALUES ('al-Qadisiya','IRQ','Al-Qādisiyyah');
INSERT INTO province_other_name (province_name,country_code,province_other_name) VALUES ('Al Qunaytirah','SYR','Quneitra');
INSERT INTO province_other_name (province_name,country_code,province_other_name) VALUES ('Sankt-Peterburg','R','Sankt Petersburg');
INSERT INTO province_other_name (province_name,country_code,province_other_name) VALUES ('Kohgiluyeh and Boyer-Ahmad','IR','Kohkiluyeh va Boyer Ahmad');
INSERT INTO province_other_name (province_name,country_code,province_other_name) VALUES ('Kongo Central','CGO','Bas-Congo');
INSERT INTO province_other_name (province_name,country_code,province_other_name) VALUES ('Al-Jazīrah','SUD','Al Gezira');
INSERT INTO province_other_name (province_name,country_code,province_other_name) VALUES ('Santarem','P','Santarém');
INSERT INTO province_other_name (province_name,country_code,province_other_name) VALUES ('Genève','CH','Genf');
INSERT INTO province_other_name (province_name,country_code,province_other_name) VALUES ('Tabouk','SA','Tabuk');
INSERT INTO province_other_name (province_name,country_code,province_other_name) VALUES ('Ash-Shamālīyah','SUD','Northern');
INSERT INTO province_other_name (province_name,country_code,province_other_name) VALUES ('Afar','ETH','Affar');
INSERT INTO province_other_name (province_name,country_code,province_other_name) VALUES ('Sharq Dārfūr','SUD','East Darfur');
INSERT INTO province_other_name (province_name,country_code,province_other_name) VALUES ('Kostanai','KZ','Kostanay');
INSERT INTO province_other_name (province_name,country_code,province_other_name) VALUES ('Al-Baha','SA','Al Bahah');
INSERT INTO province_other_name (province_name,country_code,province_other_name) VALUES ('Al-Qaḍārif','SUD','Gadaref');
INSERT INTO province_other_name (province_name,country_code,province_other_name) VALUES ('Dimashq','SYR','Damascus');
INSERT INTO province_other_name (province_name,country_code,province_other_name) VALUES ('Sakha','R','Jakutiya');
INSERT INTO province_other_name (province_name,country_code,province_other_name) VALUES ('Sankt-Peterburg','R','Saint Petersburg');
INSERT INTO province_other_name (province_name,country_code,province_other_name) VALUES ('Hamah','SYR','Hama');
INSERT INTO province_other_name (province_name,country_code,province_other_name) VALUES ('Catalunya','E','Cataluña');
INSERT INTO province_other_name (province_name,country_code,province_other_name) VALUES ('Surkhandarya','UZ','Surxondaryo');
INSERT INTO province_other_name (province_name,country_code,province_other_name) VALUES ('Akmola','KZ','Aqmola');
INSERT INTO province_other_name (province_name,country_code,province_other_name) VALUES ('Permskij','R','Permskiy');
INSERT INTO province_other_name (province_name,country_code,province_other_name) VALUES ('Fargʻona','UZ','Fergana');
INSERT INTO province_other_name (province_name,country_code,province_other_name) VALUES ('Liège','B','Luik');
INSERT INTO province_other_name (province_name,country_code,province_other_name) VALUES ('Toshkent City','UZ','Tashkent City');
INSERT INTO province_other_name (province_name,country_code,province_other_name) VALUES ('Hims','SYR','Homs');
INSERT INTO province_other_name (province_name,country_code,province_other_name) VALUES ('México, Estado de','MEX','Estado de Mexico');
INSERT INTO province_other_name (province_name,country_code,province_other_name) VALUES ('Kostanai','KZ','Kustanay');
INSERT INTO province_other_name (province_name,country_code,province_other_name) VALUES ('Catalunya','E','Catalonia');
INSERT INTO province_other_name (province_name,country_code,province_other_name) VALUES ('Gambella','ETH','Gambela');
INSERT INTO province_other_name (province_name,country_code,province_other_name) VALUES ('Basrah','IRQ','Basra');
INSERT INTO province_other_name (province_name,country_code,province_other_name) VALUES ('Valais','CH','Wallis');
INSERT INTO province_other_name (province_name,country_code,province_other_name) VALUES ('An-Nīl al-Abyaḍ','SUD','White Nile');
INSERT INTO province_other_name (province_name,country_code,province_other_name) VALUES ('Sannār','SUD','Sennar');
INSERT INTO province_other_name (province_name,country_code,province_other_name) VALUES ('Samarskaya','R','Samara');
INSERT INTO province_other_name (province_name,country_code,province_other_name) VALUES ('Dayr az Zawr','SYR','Deir ez-Zor');
INSERT INTO province_other_name (province_name,country_code,province_other_name) VALUES ('Yangon','MYA','Rangoon');
INSERT INTO province_other_name (province_name,country_code,province_other_name) VALUES ('Vaud','CH','Waadt');
INSERT INTO province_other_name (province_name,country_code,province_other_name) VALUES ('Penzenskaya','R','Penza');
INSERT INTO province_other_name (province_name,country_code,province_other_name) VALUES ('Esfahan','IR','Isfahan');
