INSERT INTO province VALUES ('Gauteng','RSA','18178');
INSERT INTO province VALUES ('Lebap','TM','93800');
INSERT INTO province VALUES ('Katsina','NGR','24971');
INSERT INTO province VALUES ('Ardahan','TR','4967');
INSERT INTO province VALUES ('Arica y Parinacota','RCH','16873');
INSERT INTO province VALUES ('Steiermark','A','16401');
INSERT INTO province VALUES ('Liaoning','CN','151000');
INSERT INTO province VALUES ('Alajuela','CR','9757');
INSERT INTO province VALUES ('Chandigarh','IND','114');
INSERT INTO province VALUES ('Madagascar','RM','587041');
INSERT INTO province VALUES ('Chihuahua','MEX','247455');
INSERT INTO province VALUES ('Aragua','YV','7014');
INSERT INTO province VALUES ('Sindh','PK','140914');
INSERT INTO province VALUES ('Etelä-Pohjanmaa','SF','13444');
INSERT INTO province VALUES ('Aveiro','P','2808');
INSERT INTO province VALUES ('Kharkivska','UA','31418');
INSERT INTO province VALUES ('Jönköping','S','10495');
INSERT INTO province VALUES ('Nasarawa','NGR','27271');
INSERT INTO province VALUES ('Anatolikis Makedonias kai Thrakis','GR','14157');
INSERT INTO province VALUES ('Chuquisaca','BOL','51524');
INSERT INTO province VALUES ('Santa Fe','RA','133007');
INSERT INTO province VALUES ('Lima','PE','32126');
INSERT INTO province VALUES ('Odeska','UA','33313');
INSERT INTO province VALUES ('Sagaing','MYA','93704');
INSERT INTO province VALUES ('Terengganu','MAL','13035');
INSERT INTO province VALUES ('Emberá','PA','4393');
INSERT INTO province VALUES ('Khyber Pakhtunkhwa','PK','74521');
INSERT INTO province VALUES ('Yamanashi','J','4465');
INSERT INTO province VALUES ('Yamoussoukro','CI','2074');
INSERT INTO province VALUES ('Luanda','ANG','2417');
INSERT INTO province VALUES ('Uttar Pradesh','IND','240928');
INSERT INTO province VALUES ('West Bengal','IND','88752');
INSERT INTO province VALUES ('Moquegua','PE','15733');
INSERT INTO province VALUES ('Hubei','CN','187500');
INSERT INTO province VALUES ('Qatar','Q','11000');
INSERT INTO province VALUES ('Paraná','BR','199315');
INSERT INTO province VALUES ('Călăraşi','RO','5087');
INSERT INTO province VALUES ('New Zealand','NZ','268680');
INSERT INTO province VALUES ('Borsod-Abaúj-Zemplén','H','7249');
INSERT INTO province VALUES ('Chiapas','MEX','73288');
INSERT INTO province VALUES ('Dytikis Makedonias','GR','9451');
INSERT INTO province VALUES ('Denizli','TR','11804');
INSERT INTO province VALUES ('South Khorasan','IR','95385');
INSERT INTO province VALUES ('Iringa','EAT','35503');
INSERT INTO province VALUES ('Bermuda','BERM','53.3');
INSERT INTO province VALUES ('Armenia','ARM','29800');
INSERT INTO province VALUES ('Newfoundland and Labrador','CDN','370510');
INSERT INTO province VALUES ('Madhya Pradesh','IND','308252');
INSERT INTO province VALUES ('Cyprus','CY','9251');
INSERT INTO province VALUES ('Oklahoma','USA','177660');
INSERT INTO province VALUES ('Brazzaville','RCB','100');
INSERT INTO province VALUES ('Adrar','RIM','235002');
INSERT INTO province VALUES ('Bartın','TR','2080');
INSERT INTO province VALUES ('Syddanmark','DK','12206');
INSERT INTO province VALUES ('Villa Clara','C','8411');
INSERT INTO province VALUES ('Central Luzon','RP','22014');
INSERT INTO province VALUES ('Karlovarský','CZ','3314');
INSERT INTO province VALUES ('Wakayama','J','4726');
INSERT INTO province VALUES ('Somogy','H','6065');
INSERT INTO province VALUES ('Rukwa','EAT','22792');
INSERT INTO province VALUES ('Västmanland','S','5145');
INSERT INTO province VALUES ('Meknes Tafilalet','MA','79210');
INSERT INTO province VALUES ('Colón','HN','8248');
INSERT INTO province VALUES ('Pwani','EAT','32547');
INSERT INTO province VALUES ('Santa Cruz','RA','243943');
INSERT INTO province VALUES ('Zanjan','IR','21773');
INSERT INTO province VALUES ('Chaharmahal and Bakhtiyari','IR','16328');
INSERT INTO province VALUES ('Cundinamarca','CO','22623');
INSERT INTO province VALUES ('Manica','MOC','62272');
INSERT INTO province VALUES ('Zamfara','NGR','35170');
INSERT INTO province VALUES ('Australia Capital Territory','AUS','2358');
INSERT INTO province VALUES ('Buzău','RO','6102');
INSERT INTO province VALUES ('Johor','MAL','19210');
INSERT INTO province VALUES ('Selangor','MAL','8104');
INSERT INTO province VALUES ('Penzenskaya','R','43200');
INSERT INTO province VALUES ('Svalbard','SVA','62049');
INSERT INTO province VALUES ('Kochi','J','7105');
INSERT INTO province VALUES ('Lorestan','IR','28294');
INSERT INTO province VALUES ('Chhattisgarh','IND','135191');
INSERT INTO province VALUES ('Obwalden','CH','490');
INSERT INTO province VALUES ('Stavropolskiy','R','66500');
INSERT INTO province VALUES ('Mary','TM','86800');
INSERT INTO province VALUES ('Samarqand','UZ','16400');
INSERT INTO province VALUES ('Veneto','I','18398');
INSERT INTO province VALUES ('Rivnenska','UA','20051');
INSERT INTO province VALUES ('Río Negro','RA','203013');
INSERT INTO province VALUES ('Adıyaman','TR','7606');
INSERT INTO province VALUES ('Hong Kong','HK','1092');
INSERT INTO province VALUES ('Tanganyika','CGO','134940');
INSERT INTO province VALUES ('Bushehr','IR','22743');
INSERT INTO province VALUES ('Labuan','MAL','91');
INSERT INTO province VALUES ('Mazowieckie','PL','35558');
INSERT INTO province VALUES ('Cojedes','YV','14800');
INSERT INTO province VALUES ('Kalimantan Tengah','RI','153564');
INSERT INTO province VALUES ('Bayern','D','70550');
INSERT INTO province VALUES ('Belgorodskaya','R','27134');
INSERT INTO province VALUES ('Maniema','CGO','132250');
INSERT INTO province VALUES ('Idlib','SYR','6097');
INSERT INTO province VALUES ('Caquetá','CO','88965');
INSERT INTO province VALUES ('Loreto','PE','368851');
INSERT INTO province VALUES ('Barbados','BDS','430');
INSERT INTO province VALUES ('Central','EAU','61403.2');
INSERT INTO province VALUES ('Mangistau','KZ','165642');
INSERT INTO province VALUES ('Insular','GQ','2034');
INSERT INTO province VALUES ('Finnmark','N','48631');
INSERT INTO province VALUES ('Republika Srpska','BIH','24857');
INSERT INTO province VALUES ('Distrito Federal','BR','5801');
INSERT INTO province VALUES ('Qazvin','IR','15567');
INSERT INTO province VALUES ('Zanzan','CI','38200');
INSERT INTO province VALUES ('Tokelau','TOK','12');
INSERT INTO province VALUES ('Nusa Tenggara Barat','RI','18572');
INSERT INTO province VALUES ('Cartago','CR','3124');
INSERT INTO province VALUES ('Sør-Trøndelag','N','18839');
INSERT INTO province VALUES ('Eastern','GH','19323');
INSERT INTO province VALUES ('Luxembourg','L','2586');
INSERT INTO province VALUES ('Sumatera Selatan','RI','91592');
INSERT INTO province VALUES ('Azores','P','2247');
INSERT INTO province VALUES ('Monaco','MC','1.9');
INSERT INTO province VALUES ('Fars','IR','122608');
INSERT INTO province VALUES ('Sankt Gallen','CH','2025');
INSERT INTO province VALUES ('Santa Fe de Bogotá','CO','1587');
INSERT INTO province VALUES ('Agadez','RN','667799');
INSERT INTO province VALUES ('Cuando Cubango','ANG','199049');
INSERT INTO province VALUES ('Morogoro','EAT','70624');
INSERT INTO province VALUES ('Benishangul-Gumuz','ETH','50698');
INSERT INTO province VALUES ('Massachusetts','USA','20202');
INSERT INTO province VALUES ('Kahramanmaraş','TR','14456');
INSERT INTO province VALUES ('Khorasan-e-Razavi','IR','118851');
INSERT INTO province VALUES ('Kermanshah','IR','25009');
INSERT INTO province VALUES ('Neamţ','RO','5896');
INSERT INTO province VALUES ('Colón','PA','4575');
INSERT INTO province VALUES ('Qinghai','CN','721000');
INSERT INTO province VALUES ('Navarra','E','10573');
INSERT INTO province VALUES ('Jammu and Kashmir','IND','222236');
INSERT INTO province VALUES ('Valle','HN','1665');
INSERT INTO province VALUES ('Botswana','RB','600370');
INSERT INTO province VALUES ('Southern','Z','85283');
INSERT INTO province VALUES ('Kuna Yala','PA','2358');
INSERT INTO province VALUES ('Volgogradskaya','R','113900');
INSERT INTO province VALUES ('Christmas Island','XMAS','135');
INSERT INTO province VALUES ('Yozgat','TR','14074');
INSERT INTO province VALUES ('Chongqing','CN','82400');
INSERT INTO province VALUES ('Yazd','IR','129285');
INSERT INTO province VALUES ('Mongolia','MNG','1565000');
INSERT INTO province VALUES ('Anguilla','AXA','102');
INSERT INTO province VALUES ('Rajasthan','IND','342239');
INSERT INTO province VALUES ('Amapá','BR','142814');
INSERT INTO province VALUES ('Altay','R','92600');
INSERT INTO province VALUES ('Victoria','AUS','227495');
INSERT INTO province VALUES ('Western Visayas','RP','20794');
INSERT INTO province VALUES ('Namur','B','3666');
INSERT INTO province VALUES ('San Andrés, Providencia y Santa Catalina','CO','44');
INSERT INTO province VALUES ('Pohjols-Karjala','SF','17761');
INSERT INTO province VALUES ('Kuwait','KWT','17820');
INSERT INTO province VALUES ('Cabo Delgado','MOC','78778');
INSERT INTO province VALUES ('Kanta-Häme','SF','5199');
INSERT INTO province VALUES ('Guangdong','CN','197100');
INSERT INTO province VALUES ('Chernihivska','UA','31903');
INSERT INTO province VALUES ('Ash Sharqiyah','SA','672522');
INSERT INTO province VALUES ('Kenya','EAK','582650');
INSERT INTO province VALUES ('Møre og Romsdal','N','15101');
INSERT INTO province VALUES ('South','PNG','223900');
INSERT INTO province VALUES ('Centre','CAM','68953');
INSERT INTO province VALUES ('Mjini Magharibi Unguja','EAT','230');
INSERT INTO province VALUES ('Amhara','ETH','154708');
INSERT INTO province VALUES ('Northern Ireland','GB','14130');
INSERT INTO province VALUES ('Jilin','CN','187000');
INSERT INTO province VALUES ('Puno','PE','71999');
INSERT INTO province VALUES ('Burkina Faso','BF','274200');
INSERT INTO province VALUES ('Ondo','NGR','15195');
INSERT INTO province VALUES ('Pardubický','CZ','4518');
INSERT INTO province VALUES ('Makkah Al-Mokarramah','SA','153128');
INSERT INTO province VALUES ('Bicol','RP','18155');
INSERT INTO province VALUES ('Bahrain','BRN','620');
INSERT INTO province VALUES ('Karachayevo-Cherkesskaya','R','14100');
INSERT INTO province VALUES ('Benguela','ANG','39826');
INSERT INTO province VALUES ('Taraba','NGR','60291');
INSERT INTO province VALUES ('Kasai-Central','CGO','60958');
INSERT INTO province VALUES ('Rakhine','MYA','36778');
INSERT INTO province VALUES ('Nord-Trøndelag','N','22414');
INSERT INTO province VALUES ('Guelmim Es Semara','MA','62825');
INSERT INTO province VALUES ('Karaganda','KZ','427982');
INSERT INTO province VALUES ('Maranhão','BR','331983');
INSERT INTO province VALUES ('Bas-Uele','CGO','148331');
INSERT INTO province VALUES ('Lubelskie','PL','25122');
INSERT INTO province VALUES ('Wallis and Futuna','WF','274');
INSERT INTO province VALUES ('Saitama','J','3798');
INSERT INTO province VALUES ('Matanzas','C','11791');
INSERT INTO province VALUES ('Primorskiy','R','165900');
INSERT INTO province VALUES ('Molise','I','4437');
INSERT INTO province VALUES ('Sangha','RCB','55800');
INSERT INTO province VALUES ('Ankara','TR','25401');
INSERT INTO province VALUES ('Grand Casablanca','MA','1615');
INSERT INTO province VALUES ('Borno','NGR','75480');
INSERT INTO province VALUES ('Kentrikis Makedonias','GR','18810');
INSERT INTO province VALUES ('Limón','CR','9188');
INSERT INTO province VALUES ('Rio de Janeiro','BR','43696');
INSERT INTO province VALUES ('Rostovskaya','R','100800');
INSERT INTO province VALUES ('Wales','GB','20735');
INSERT INTO province VALUES ('Solothurn','CH','790');
INSERT INTO province VALUES ('Dakhlet Nouadhibou','RIM','23090');
INSERT INTO province VALUES ('Plateau','NGR','27216');
INSERT INTO province VALUES ('Iğdır','TR','3587');
INSERT INTO province VALUES ('Nei Mongol','CN','1177500');
INSERT INTO province VALUES ('Cambodia','K','181040');
INSERT INTO province VALUES ('Düzce','TR','2592');
INSERT INTO province VALUES ('Sancti Spíritus','C','6777');
INSERT INTO province VALUES ('Jujuy','RA','53219');
INSERT INTO province VALUES ('El Paraíso','HN','7489');
INSERT INTO province VALUES ('Auvergne-Rhône-Alpes','F','69711');
INSERT INTO province VALUES ('Vaupés','CO','65268');
INSERT INTO province VALUES ('Murcia','E','11312');
INSERT INTO province VALUES ('Sakhalin','R','87100');
INSERT INTO province VALUES ('Idaho','USA','214045');
INSERT INTO province VALUES ('Kirkuk','IRQ','9679');
INSERT INTO province VALUES ('Bayelsa','NGR','9415');
INSERT INTO province VALUES ('Kwilu','CGO','78533');
INSERT INTO province VALUES ('Covasna','RO','3709');
INSERT INTO province VALUES ('Curacao','CUR','444');
INSERT INTO province VALUES ('Yamalo Nenets ao','R','750300');
INSERT INTO province VALUES ('Rize','TR','3921');
INSERT INTO province VALUES ('Liechtenstein','FL','160');
INSERT INTO province VALUES ('Kyrgyzstan','KG','198500');
INSERT INTO province VALUES ('Drenthe','NL','2680');
INSERT INTO province VALUES ('Saint Pierre and Miquelon','SPMI','242');
INSERT INTO province VALUES ('East-Kazakhstan','KZ','283226');
INSERT INTO province VALUES ('Northern','GH','70384');
INSERT INTO province VALUES ('Portuguesa','YV','15200');
INSERT INTO province VALUES ('Grenada','WG','344');
INSERT INTO province VALUES ('Montenegro','MNE','14026');
INSERT INTO province VALUES ('Chukotka','R','737700');
INSERT INTO province VALUES ('Åland','SF','1553');
INSERT INTO province VALUES ('Trujillo','YV','7198');
INSERT INTO province VALUES ('Magwe','MYA','44820');
INSERT INTO province VALUES ('Tripura','IND','10486');
INSERT INTO province VALUES ('Oslo','N','454');
INSERT INTO province VALUES ('Nagasaki','J','4105');
INSERT INTO province VALUES ('Córdoba','RA','165321');
INSERT INTO province VALUES ('Teleorman','RO','5789');
INSERT INTO province VALUES ('Sumatera Utara','RI','72981');
INSERT INTO province VALUES ('Nahr an-Nīl','SUD','122123');
INSERT INTO province VALUES ('Warmińsko-Mazurskie','PL','24173');
INSERT INTO province VALUES ('Jihomoravský','CZ','7194');
INSERT INTO province VALUES ('Varsinais-Suomi','SF','10663');
INSERT INTO province VALUES ('Shandong','CN','153300');
INSERT INTO province VALUES ('Bacău','RO','6620');
INSERT INTO province VALUES ('Zabaykalskiy','R','431500');
INSERT INTO province VALUES ('Holguín','C','9215');
INSERT INTO province VALUES ('Aruba','ARU','193');
INSERT INTO province VALUES ('Graubünden','CH','7105');
INSERT INTO province VALUES ('Njombe','EAT','21347');
INSERT INTO province VALUES ('Xorazm','UZ','6300');
INSERT INTO province VALUES ('Bilecik','TR','4306');
INSERT INTO province VALUES ('Zürich','CH','1728');
INSERT INTO province VALUES ('Hakkari','TR','7178');
INSERT INTO province VALUES ('Tucumán','RA','22524');
INSERT INTO province VALUES ('Gorgol','RIM','13600');
INSERT INTO province VALUES ('South Sudan','SSD','644329');
INSERT INTO province VALUES ('Jawa Tengah','RI','32800');
INSERT INTO province VALUES ('Constanţa','RO','7071');
INSERT INTO province VALUES ('Appenzell Innerrhoden','CH','172');
INSERT INTO province VALUES ('Guárico','YV','64986');
INSERT INTO province VALUES ('Iaşi','RO','5475');
INSERT INTO province VALUES ('Hovedstaden','DK','2561');
INSERT INTO province VALUES ('Xinjiang','CN','1646900');
INSERT INTO province VALUES ('Cordillera','RP','19422');
INSERT INTO province VALUES ('Heves','H','3637');
INSERT INTO province VALUES ('Madeira','P','794');
INSERT INTO province VALUES ('Antofagasta','RCH','126049');
INSERT INTO province VALUES ('Arad','RO','7754');
INSERT INTO province VALUES ('Fiji','FJI','18270');
INSERT INTO province VALUES ('Guarda','P','5518');
INSERT INTO province VALUES ('Arkhangelskaya','R','587400');
INSERT INTO province VALUES ('Niger','NGR','74108');
INSERT INTO province VALUES ('Keski-Pohjanmaa','SF','5020');
INSERT INTO province VALUES ('Zakarpatska','UA','12753');
INSERT INTO province VALUES ('Kachin','MYA','89041');
INSERT INTO province VALUES ('Miranda','YV','7950');
INSERT INTO province VALUES ('Maine','USA','79883');
INSERT INTO province VALUES ('Brabant Wallon','B','1090');
INSERT INTO province VALUES ('Kentucky','USA','102269');
INSERT INTO province VALUES ('Fes Boulemane','MA','19795');
INSERT INTO province VALUES ('Moscow','R','1100');
INSERT INTO province VALUES ('Tanintharyi','MYA','43344');
INSERT INTO province VALUES ('Chocó','CO','46530');
INSERT INTO province VALUES ('Fujian','CN','123100');
INSERT INTO province VALUES ('Táchira','YV','10812');
INSERT INTO province VALUES ('Tambovskaya','R','34300');
INSERT INTO province VALUES ('Namangan','UZ','7900');
INSERT INTO province VALUES ('Tehran','IR','13692');
INSERT INTO province VALUES ('Burdur','TR','7134');
INSERT INTO province VALUES ('Kirovohradska','UA','24588');
INSERT INTO province VALUES ('La Rioja','E','5045');
INSERT INTO province VALUES ('Kalmykiya','R','76100');
INSERT INTO province VALUES ('Mandalay','MYA','37945');
INSERT INTO province VALUES ('Ica','PE','21327');
INSERT INTO province VALUES ('Satakunta','SF','7820');
INSERT INTO province VALUES ('Krasnodarskiy','R','76000');
INSERT INTO province VALUES ('Guainía','CO','72238');
INSERT INTO province VALUES ('Moxico','ANG','223023');
INSERT INTO province VALUES ('New Hampshire','USA','23187');
INSERT INTO province VALUES ('Kedah','MAL','9500');
INSERT INTO province VALUES ('Niari','RCB','25942');
INSERT INTO province VALUES ('Niederösterreich','A','19186');
INSERT INTO province VALUES ('Paraíba','BR','56439');
INSERT INTO province VALUES ('Zeeland','NL','2933');
INSERT INTO province VALUES ('Vlaams-Brabant','B','2106');
INSERT INTO province VALUES ('Maradi','RN','41796');
INSERT INTO province VALUES ('United Arab Emirates','UAE','75581');
INSERT INTO province VALUES ('Louisiana','USA','111898');
INSERT INTO province VALUES ('Barisal','BD','13225');
INSERT INTO province VALUES ('Buskerud','N','14910');
INSERT INTO province VALUES ('London','GB','1572');
INSERT INTO province VALUES ('North Korea','KP','120540');
INSERT INTO province VALUES ('Guinea','RG','245860');
INSERT INTO province VALUES ('Jawa Timur','RI','47799');
INSERT INTO province VALUES ('South East','GB','19069');
INSERT INTO province VALUES ('Misiones','RA','29801');
INSERT INTO province VALUES ('Edo','NGR','19819');
INSERT INTO province VALUES ('Magallanes','RCH','116437');
INSERT INTO province VALUES ('Sonora','MEX','179502');
INSERT INTO province VALUES ('Babylon','IRQ','5119');
INSERT INTO province VALUES ('Irkutskaya','R','767900');
INSERT INTO province VALUES ('Gelderland','NL','5136');
INSERT INTO province VALUES ('Lagos','NGR','3496');
INSERT INTO province VALUES ('Virginia','USA','102279');
INSERT INTO province VALUES ('Kainuu','SF','20197');
INSERT INTO province VALUES ('Lara','YV','19800');
INSERT INTO province VALUES ('Hefa','IL','866');
INSERT INTO province VALUES ('Sarawak','MAL','124450');
INSERT INTO province VALUES ('Est','CAM','109002');
INSERT INTO province VALUES ('Bryanskaya','R','34857');
INSERT INTO province VALUES ('Northern','EAU','85391.7');
INSERT INTO province VALUES ('Kepulauan Bangka Belitung','RI','16424');
INSERT INTO province VALUES ('Kritis','GR','8335');
INSERT INTO province VALUES ('Beni','BOL','213564');
INSERT INTO province VALUES ('Østfold','N','4180');
INSERT INTO province VALUES ('Khanty Mansi ao','R','534800');
INSERT INTO province VALUES ('Stockholm','S','6519');
INSERT INTO province VALUES ('Miyagi','J','7285');
INSERT INTO province VALUES ('Kostromskaya','R','60100');
INSERT INTO province VALUES ('Porto','P','2395');
INSERT INTO province VALUES ('Gaza','MOC','75334');
INSERT INTO province VALUES ('Assaba','RIM','36600');
INSERT INTO province VALUES ('Al-Jazīrah','SUD','23373');
INSERT INTO province VALUES ('Sylhet','BD','12635');
INSERT INTO province VALUES ('Nord','CAM','66090');
INSERT INTO province VALUES ('Catamarca','RA','102602');
INSERT INTO province VALUES ('Bouenza','RCB','12265');
INSERT INTO province VALUES ('Fatick','SN','6849');
INSERT INTO province VALUES ('San Luis Potosí','MEX','60982');
INSERT INTO province VALUES ('Iwate','J','15278');
INSERT INTO province VALUES ('Huancavelica','PE','22131');
INSERT INTO province VALUES ('Haut-Katanga','CGO','132425');
INSERT INTO province VALUES ('Kohgiluyeh and Boyer-Ahmad','IR','15504');
INSERT INTO province VALUES ('Voronezhskaya','R','52400');
INSERT INTO province VALUES ('Perak','MAL','21035');
INSERT INTO province VALUES ('Atyrau','KZ','118631');
INSERT INTO province VALUES ('Bolu','TR','8323');
INSERT INTO province VALUES ('Niigata','J','12583');
INSERT INTO province VALUES ('Kujawsko-Pomorskie','PL','17971');
INSERT INTO province VALUES ('Cochabamba','BOL','55631');
INSERT INTO province VALUES ('Dodoma','EAT','41311');
INSERT INTO province VALUES ('Minsk','BY','39912');
INSERT INTO province VALUES ('Zug','CH','238');
INSERT INTO province VALUES ('Ticino','CH','2812');
INSERT INTO province VALUES ('Thurgau','CH','990');
INSERT INTO province VALUES ('Novosibirskaya','R','178200');
INSERT INTO province VALUES ('Rajshahi','BD','18153');
INSERT INTO province VALUES ('Bengkulu','RI','19919');
INSERT INTO province VALUES ('Praha','CZ','496');
INSERT INTO province VALUES ('Saint Lucia','WL','620');
INSERT INTO province VALUES ('Szabolcs-Szatmár-Bereg','H','5935');
INSERT INTO province VALUES ('Smolenskaya','R','49800');
INSERT INTO province VALUES ('Yorkshire and the Humber','GB','15407');
INSERT INTO province VALUES ('Vargas','YV','1172');
INSERT INTO province VALUES ('Tottori','J','3507');
INSERT INTO province VALUES ('Huíla','ANG','79023');
INSERT INTO province VALUES ('Yukon','CDN','474712');
INSERT INTO province VALUES ('Trenčiansky','SK','4502');
INSERT INTO province VALUES ('Guanacaste','CR','10140');
INSERT INTO province VALUES ('Sughd','TJ','25200');
INSERT INTO province VALUES ('Denguélé','CI','20900');
INSERT INTO province VALUES ('Salah al-Deen','IRQ','24075');
INSERT INTO province VALUES ('Al-Riyadh','SA','404240');
INSERT INTO province VALUES ('Chiba','J','5156');
INSERT INTO province VALUES ('Sinop','TR','5816');
INSERT INTO province VALUES ('Alba','RO','6241');
INSERT INTO province VALUES ('Vâlcea','RO','5764');
INSERT INTO province VALUES ('Luapula','Z','50567');
INSERT INTO province VALUES ('San Juan','RA','89651');
INSERT INTO province VALUES ('Tatarstan','R','68000');
INSERT INTO province VALUES ('Shan','MYA','155801');
INSERT INTO province VALUES ('Guam','GUAM','545');
INSERT INTO province VALUES ('Gorno-Badakhshan','TJ','64100');
INSERT INTO province VALUES ('Bago','MYA','39402');
INSERT INTO province VALUES ('Gilgit-Baltistan','PK','72520');
INSERT INTO province VALUES ('Eskişehir','TR','13902');
INSERT INTO province VALUES ('Notioy Aigaioy','GR','5285');
INSERT INTO province VALUES ('al-Qadisiya','IRQ','8153');
INSERT INTO province VALUES ('Setubal','P','5064');
INSERT INTO province VALUES ('Kaskazini Unguja','EAT','470');
INSERT INTO province VALUES ('Bolívar','YV','240528');
INSERT INTO province VALUES ('Thi Qar','IRQ','12900');
INSERT INTO province VALUES ('Burundi','BI','27830');
INSERT INTO province VALUES ('Sevastopol','UA','864');
INSERT INTO province VALUES ('Tasmania','AUS','68018');
INSERT INTO province VALUES ('Vestfold','N','2225');
INSERT INTO province VALUES ('Schaffhausen','CH','298');
INSERT INTO province VALUES ('San Marino','RSM','60');
INSERT INTO province VALUES ('Moravskoslezský','CZ','5426');
INSERT INTO province VALUES ('Lunda-Sul','ANG','77367');
INSERT INTO province VALUES ('Lubuskie','PL','13987');
INSERT INTO province VALUES ('Coclé','PA','4946');
INSERT INTO province VALUES ('Pahang','MAL','36137');
INSERT INTO province VALUES ('Malanje','ANG','97602');
INSERT INTO province VALUES ('Rif Dimashq','SYR','18032');
INSERT INTO province VALUES ('Şanlıurfa','TR','19336');
INSERT INTO province VALUES ('Jersey','GBJ','117');
INSERT INTO province VALUES ('Davao','RP','20357');
INSERT INTO province VALUES ('Maldives','MV','300');
INSERT INTO province VALUES ('Hordaland','N','15438');
INSERT INTO province VALUES ('Nicaragua','NIC','129494');
INSERT INTO province VALUES ('Regions of Republican Subordination','TJ','28600');
INSERT INTO province VALUES ('Rhode Island','USA','2678');
INSERT INTO province VALUES ('Toshkent','UZ','15000');
INSERT INTO province VALUES ('Mecklenburg-Vorpommern','D','23194');
INSERT INTO province VALUES ('Yaroslavskaya','R','36400');
INSERT INTO province VALUES ('Nay Pyi Taw','MYA','7054');
INSERT INTO province VALUES ('Katavi','EAT','45843');
INSERT INTO province VALUES ('Khatlon','TJ','24600');
INSERT INTO province VALUES ('Ebonyi','NGR','6421');
INSERT INTO province VALUES ('Lempira','HN','4234');
INSERT INTO province VALUES ('Gorontalo','RI','11257');
INSERT INTO province VALUES ('Extremadura','E','41634');
INSERT INTO province VALUES ('Valais','CH','5224');
INSERT INTO province VALUES ('Shamāl Dārfūr','SUD','320000');
INSERT INTO province VALUES ('Al-Baha','SA','9921');
INSERT INTO province VALUES ('Blekinge','S','2946');
INSERT INTO province VALUES ('Dagestan','R','50300');
INSERT INTO province VALUES ('Namibia','NAM','825418');
INSERT INTO province VALUES ('Marshall Islands','MH','181.3');
INSERT INTO province VALUES ('Azerbaijan','AZ','86600');
INSERT INTO province VALUES ('Continental','GQ','26017');
INSERT INTO province VALUES ('HaDarom','IL','14185');
INSERT INTO province VALUES ('Liberecký','CZ','3162');
INSERT INTO province VALUES ('Mimaropa','RP','29620');
INSERT INTO province VALUES ('Ardebil','IR','17800');
INSERT INTO province VALUES ('Sistan and Baluchestan','IR','181785');
INSERT INTO province VALUES ('Distrito Federal','MEX','1485');
INSERT INTO province VALUES ('Murmanskaya','R','144900');
INSERT INTO province VALUES ('Yucatán','MEX','39612');
INSERT INTO province VALUES ('Sachsen-Anhalt','D','20450');
INSERT INTO province VALUES ('Sassandra-Marahoué','CI','23950');
INSERT INTO province VALUES ('Caraş-Severin','RO','8519');
INSERT INTO province VALUES ('Qom','IR','11526');
INSERT INTO province VALUES ('Chad','TCH','1284000');
INSERT INTO province VALUES ('Sédhiou','SN','7341');
INSERT INTO province VALUES ('Monagas','YV','28900');
INSERT INTO province VALUES ('An-Nīl al-Azraq','SUD','45844');
INSERT INTO province VALUES ('Ar Raqqah','SYR','19616');
INSERT INTO province VALUES ('Timor-Leste','TL','15007');
INSERT INTO province VALUES ('Hormozgan','IR','70697');
INSERT INTO province VALUES ('Delaware','USA','5047');
INSERT INTO province VALUES ('Bahia','BR','564692');
INSERT INTO province VALUES ('Kütahya','TR','12013');
INSERT INTO province VALUES ('Gujarat','IND','196244');
INSERT INTO province VALUES ('Cauca','CO','29308');
INSERT INTO province VALUES ('Oriental','MA','82900');
INSERT INTO province VALUES ('Louga','SN','24889');
INSERT INTO province VALUES ('Jewish Autonomous Oblast','R','36266');
INSERT INTO province VALUES ('Virgin Islands','VIRG','346');
INSERT INTO province VALUES ('Sulawesi Tengah','RI','61841');
INSERT INTO province VALUES ('Ituri','CGO','65658');
INSERT INTO province VALUES ('Eastern','EAU','39478.8');
INSERT INTO province VALUES ('Aust-Agder','N','9157');
INSERT INTO province VALUES ('Flevoland','NL','2412');
INSERT INTO province VALUES ('Saga','J','2439');
INSERT INTO province VALUES ('Dosso','RN','33844');
INSERT INTO province VALUES ('Dnipropetrovska','UA','31923');
INSERT INTO province VALUES ('Gôh-Djiboua','CI','15700');
INSERT INTO province VALUES ('Singida','EAT','49340');
INSERT INTO province VALUES ('Erzincan','TR','11727');
INSERT INTO province VALUES ('Västra Götaland','S','23948');
INSERT INTO province VALUES ('Jura','CH','838');
INSERT INTO province VALUES ('Aseer','SA','76693');
INSERT INTO province VALUES ('Cajamarca','PE','33317');
INSERT INTO province VALUES ('Gomel','BY','40361');
INSERT INTO province VALUES ('Ontario','CDN','908607');
INSERT INTO province VALUES ('Nebraska','USA','198974');
INSERT INTO province VALUES ('Oromia','ETH','298164');
INSERT INTO province VALUES ('Central','Z','94394');
INSERT INTO province VALUES ('Kumamoto','J','7404');
INSERT INTO province VALUES ('Vichada','CO','100242');
INSERT INTO province VALUES ('California','USA','403466');
INSERT INTO province VALUES ('Illinois','USA','143793');
INSERT INTO province VALUES ('Eastern Visayas','RP','23251');
INSERT INTO province VALUES ('Montserrat','MNTS','102');
INSERT INTO province VALUES ('Baikonur','KZ','57');
INSERT INTO province VALUES ('Kalimantan Barat','RI','147307');
INSERT INTO province VALUES ('Pará','BR','1247689');
INSERT INTO province VALUES ('Osaka','J','1898');
INSERT INTO province VALUES ('Oyo','NGR','28245');
INSERT INTO province VALUES ('Oost-Vlaanderen','B','2982');
INSERT INTO province VALUES ('Van','TR','19414');
INSERT INTO province VALUES ('Jambi','RI','50058');
INSERT INTO province VALUES ('Thailand','THA','514000');
INSERT INTO province VALUES ('Bratislavský','SK','2052');
INSERT INTO province VALUES ('Päijät-Häme','SF','5125');
INSERT INTO province VALUES ('Yoro','HN','7781');
INSERT INTO province VALUES ('Sirdaryo','UZ','5100');
INSERT INTO province VALUES ('Basel-Stadt','CH','37');
INSERT INTO province VALUES ('Ordu','TR','5952');
INSERT INTO province VALUES ('Kelantan','MAL','15099');
INSERT INTO province VALUES ('Yamagata','J','9323');
INSERT INTO province VALUES ('Piauí','BR','251529');
INSERT INTO province VALUES ('Tabouk','SA','146072');
INSERT INTO province VALUES ('Western','Z','126386');
INSERT INTO province VALUES ('Aghion Oros','GR','335');
INSERT INTO province VALUES ('Shamāl Kurdufān','SUD','185302');
INSERT INTO province VALUES ('Etelä-Savo','SF','14257');
INSERT INTO province VALUES ('Çanakkale','TR','9950');
INSERT INTO province VALUES ('Maluku','RI','46914');
INSERT INTO province VALUES ('Red River Delta','VN','21059.3');
INSERT INTO province VALUES ('Kocaeli','TR','3625');
INSERT INTO province VALUES ('Jazan','SA','11671');
INSERT INTO province VALUES ('Shaanxi','CN','195800');
INSERT INTO province VALUES ('Toscana','I','22993');
INSERT INTO province VALUES ('HaMerkaz','IL','1294');
INSERT INTO province VALUES ('Adamaoua','CAM','63701');
INSERT INTO province VALUES ('Hamburg','D','755');
INSERT INTO province VALUES ('Samsun','TR','9364');
INSERT INTO province VALUES ('Florida','USA','138887');
INSERT INTO province VALUES ('Mehedinţi','RO','4932');
INSERT INTO province VALUES ('Gaza Strip','GAZA','365');
INSERT INTO province VALUES ('Yerushalayim','IL','653');
INSERT INTO province VALUES ('Saarland','D','2568');
INSERT INTO province VALUES ('Békés','H','5629');
INSERT INTO province VALUES ('Melaka','MAL','1664');
INSERT INTO province VALUES ('Maysan','IRQ','16072');
INSERT INTO province VALUES ('Tambacounda','SN','42364');
INSERT INTO province VALUES ('Kemerovskaya','R','95500');
INSERT INTO province VALUES ('Upper West','GH','18476');
INSERT INTO province VALUES ('Zimbabwe','ZW','390580');
INSERT INTO province VALUES ('Nordjylland','DK','7933');
INSERT INTO province VALUES ('Tel Aviv','IL','172');
INSERT INTO province VALUES ('Jharkhand','IND','79716');
INSERT INTO province VALUES ('Vaud','CH','3212');
INSERT INTO province VALUES ('Novgorodskaya','R','55300');
INSERT INTO province VALUES ('Thiès','SN','6670');
INSERT INTO province VALUES ('Tolima','CO','23562');
INSERT INTO province VALUES ('West-Vlaanderen','B','3144');
INSERT INTO province VALUES ('Papua Barat','RI','97024');
INSERT INTO province VALUES ('Basrah','IRQ','19070');
INSERT INTO province VALUES ('Afar','ETH','72052');
INSERT INTO province VALUES ('Gracias a Dios','HN','16997');
INSERT INTO province VALUES ('Shizuoka','J','7780');
INSERT INTO province VALUES ('Kärnten','A','9538');
INSERT INTO province VALUES ('Veszprém','H','4463');
INSERT INTO province VALUES ('Hiroshima','J','8479');
INSERT INTO province VALUES ('As Sulaymaniyah','IRQ','17023');
INSERT INTO province VALUES ('México, Estado de','MEX','22356');
INSERT INTO province VALUES ('Piura','PE','35892');
INSERT INTO province VALUES ('Pomorskie','PL','18310');
INSERT INTO province VALUES ('Balkan','TM','138500');
INSERT INTO province VALUES ('Hunan','CN','210500');
INSERT INTO province VALUES ('Mekong River Delta','VN','40572');
INSERT INTO province VALUES ('New Caledonia','NCL','19060');
INSERT INTO province VALUES ('Şırnak','TR','7151');
INSERT INTO province VALUES ('Castilla-La Mancha','E','79408');
INSERT INTO province VALUES ('Western Sahara','WSA','266000');
INSERT INTO province VALUES ('Attikis','GR','3808');
INSERT INTO province VALUES ('Isla de la Juventud','C','2419');
INSERT INTO province VALUES ('Ireland','IRL','70280');
INSERT INTO province VALUES ('Anzoátegui','YV','43300');
INSERT INTO province VALUES ('Tulcea','RO','8498');
INSERT INTO province VALUES ('Saint Kitts and Nevis','KN','269');
INSERT INTO province VALUES ('Dominica','WD','746');
INSERT INTO province VALUES ('Free State','RSA','129825');
INSERT INTO province VALUES ('San José','CR','4965');
INSERT INTO province VALUES ('Kiribati','KIR','717');
INSERT INTO province VALUES ('Ruvuma','EAT','63669');
INSERT INTO province VALUES ('Marrakech Tensift Al Haouz','MA','31160');
INSERT INTO province VALUES ('Banskobystrický','SK','9453');
INSERT INTO province VALUES ('Tolna','H','3703');
INSERT INTO province VALUES ('Tete','MOC','98417');
INSERT INTO province VALUES ('Nitriansky','SK','6343');
INSERT INTO province VALUES ('Hodh Chargui','RIM','182700');
INSERT INTO province VALUES ('Comoé','CI','14150');
INSERT INTO province VALUES ('Friuli-Venezia Giulia','I','7858');
INSERT INTO province VALUES ('Sankt-Peterburg','R','1431');
INSERT INTO province VALUES ('Groningen','NL','2959');
INSERT INTO province VALUES ('Daraa','SYR','3730');
INSERT INTO province VALUES ('Basel-Landschaft','CH','517');
INSERT INTO province VALUES ('Falcón','YV','24800');
INSERT INTO province VALUES ('Estonia','EST','45100');
INSERT INTO province VALUES ('Opolskie','PL','9411');
INSERT INTO province VALUES ('Corse','F','8679');
INSERT INTO province VALUES ('İzmir','TR','12015');
INSERT INTO province VALUES ('Omskaya','R','139700');
INSERT INTO province VALUES ('Bucureşti','RO','237');
INSERT INTO province VALUES ('Tyva','R','170500');
INSERT INTO province VALUES ('Matam','SN','29445');
INSERT INTO province VALUES ('Kasai-Oriental','CGO','9481');
INSERT INTO province VALUES ('Arizona','USA','294207');
INSERT INTO province VALUES ('Riau','RI','87023');
INSERT INTO province VALUES ('Turks and Caicos Islands','TUCA','430');
INSERT INTO province VALUES ('Královéhradecký','CZ','4758');
INSERT INTO province VALUES ('Amazonas','YV','183500');
INSERT INTO province VALUES ('Kayseri','TR','17109');
INSERT INTO province VALUES ('Wien','A','414');
INSERT INTO province VALUES ('Bamako','RMM','252');
INSERT INTO province VALUES ('Akwa Ibom','NGR','6772');
INSERT INTO province VALUES ('Araucanía','RCH','31842');
INSERT INTO province VALUES ('New York','USA','122057');
INSERT INTO province VALUES ('Micronesia','FSM','702');
INSERT INTO province VALUES ('Andijon','UZ','4200');
INSERT INTO province VALUES ('Pohjanmaa','SF','7753');
INSERT INTO province VALUES ('Cantabria','E','5323');
INSERT INTO province VALUES ('Hawaii','USA','16635');
INSERT INTO province VALUES ('Samoa','WS','2860');
INSERT INTO province VALUES ('Gilan','IR','14042');
INSERT INTO province VALUES ('Shinyanga','EAT','18901');
INSERT INTO province VALUES ('Hamah','SYR','8883');
INSERT INTO province VALUES ('Andorra','AND','450');
INSERT INTO province VALUES ('La Habana','C','728');
INSERT INTO province VALUES ('Mureş','RO','6713');
INSERT INTO province VALUES ('Missouri','USA','178040');
INSERT INTO province VALUES ('Manyara','EAT','44522');
INSERT INTO province VALUES ('Uppsala','S','8207');
INSERT INTO province VALUES ('West Virginia','USA','62259');
INSERT INTO province VALUES ('Peloponnisos','GR','15489');
INSERT INTO province VALUES ('Cluj','RO','6674');
INSERT INTO province VALUES ('Macao','MACX','16');
INSERT INTO province VALUES ('Mtwara','EAT','16710');
INSERT INTO province VALUES ('Meta','CO','85635');
INSERT INTO province VALUES ('Formosa','RA','72066');
INSERT INTO province VALUES ('New Mexico','USA','314161');
INSERT INTO province VALUES ('Tanger Tetouan','MA','11570');
INSERT INTO province VALUES ('Pernambuco','BR','98311');
INSERT INTO province VALUES ('Kaskazini Pemba','EAT','574');
INSERT INTO province VALUES ('KwaZulu-Natal','RSA','94361');
INSERT INTO province VALUES ('Limpopo','RSA','125754');
INSERT INTO province VALUES ('Thüringen','D','16172');
INSERT INTO province VALUES ('Karnataka','IND','191791');
INSERT INTO province VALUES ('Fejér','H','4358');
INSERT INTO province VALUES ('Zachodniopomorskie','PL','22892');
INSERT INTO province VALUES ('Anambra','NGR','4816');
INSERT INTO province VALUES ('Bayburt','TR','3739');
INSERT INTO province VALUES ('Chechenskaya','R','12300');
INSERT INTO province VALUES ('Ayacucho','PE','43814');
INSERT INTO province VALUES ('Orlovskaya','R','24700');
INSERT INTO province VALUES ('Lacs','CI','26100');
INSERT INTO province VALUES ('Tokushima','J','4146');
INSERT INTO province VALUES ('Melilla','MEL','12');
INSERT INTO province VALUES ('Sint Maarten','SX','34');
INSERT INTO province VALUES ('Olt','RO','5498');
INSERT INTO province VALUES ('Dar es Salaam','EAT','1393');
INSERT INTO province VALUES ('Chin','MYA','36018');
INSERT INTO province VALUES ('Enugu','NGR','7660');
INSERT INTO province VALUES ('Córdoba','CO','25020');
INSERT INTO province VALUES ('Valparaíso','RCH','16396');
INSERT INTO province VALUES ('Sud-Ouest','CAM','25410');
INSERT INTO province VALUES ('Georgia','USA','148959');
INSERT INTO province VALUES ('Espírito Santo','BR','46077');
INSERT INTO province VALUES ('Vest-Agder','N','7276');
INSERT INTO province VALUES ('Gumma','J','6362');
INSERT INTO province VALUES ('Vysočina','CZ','6795');
INSERT INTO province VALUES ('Puducherry','IND','490');
INSERT INTO province VALUES ('Al-Qaseem','SA','58046');
INSERT INTO province VALUES ('Baja California Sur','MEX','73922');
INSERT INTO province VALUES ('Lampung','RI','34623');
INSERT INTO province VALUES ('Quebec','CDN','1356547');
INSERT INTO province VALUES ('Ayeyarwady','MYA','35031');
INSERT INTO province VALUES ('YeDebub Biheroch Bihereseboch na Hizboch','ETH','105887');
INSERT INTO province VALUES ('Tiris Zemmour','RIM','252900');
INSERT INTO province VALUES ('Northern Midlands and Mountains','VN','95274.7');
INSERT INTO province VALUES ('Mazandaran','IR','23842');
INSERT INTO province VALUES ('Soccsksargen','RP','22513');
INSERT INTO province VALUES ('DKI Jakarta','RI','664');
INSERT INTO province VALUES ('Putumayo','CO','24885');
INSERT INTO province VALUES ('Manitoba','CDN','552329');
INSERT INTO province VALUES ('Comayagua','HN','5124');
INSERT INTO province VALUES ('Quindío','CO','1845');
INSERT INTO province VALUES ('Lisboa','P','2761');
INSERT INTO province VALUES ('Distrito Federal','RA','203');
INSERT INTO province VALUES ('Shanxi','CN','157100');
INSERT INTO province VALUES ('Dominican Republic','DOM','48730');
INSERT INTO province VALUES ('Wasaṭ Dārfūr','SUD','34000');
INSERT INTO province VALUES ('Atacama','RCH','75176');
INSERT INTO province VALUES ('Morelos','MEX','4892');
INSERT INTO province VALUES ('Lithuania','LT','65200');
INSERT INTO province VALUES ('Donetska','UA','26517');
INSERT INTO province VALUES ('Neuquén','RA','94078');
INSERT INTO province VALUES ('Braga','P','2673');
INSERT INTO province VALUES ('Mississippi','USA','121531');
INSERT INTO province VALUES ('Zaporizka','UA','27183');
INSERT INTO province VALUES ('Sabah','MAL','73631');
INSERT INTO province VALUES ('Alabama','USA','131171');
INSERT INTO province VALUES ('Bremen','D','419');
INSERT INTO province VALUES ('Udmurtskaya','R','42100');
INSERT INTO province VALUES ('Uşak','TR','5363');
INSERT INTO province VALUES ('Sakarya','TR','4880');
INSERT INTO province VALUES ('Guatemala','GCA','108890');
INSERT INTO province VALUES ('Vallée du Bandama','CI','28300');
INSERT INTO province VALUES ('Śląskie','PL','12333');
INSERT INTO province VALUES ('Sergipe','BR','21910');
INSERT INTO province VALUES ('Mayotte','MAYO','374');
INSERT INTO province VALUES ('Satu-Mare','RO','4417');
INSERT INTO province VALUES ('Paraguay','PY','406750');
INSERT INTO province VALUES ('Vrancea','RO','4857');
INSERT INTO province VALUES ('Grodno','BY','25118');
INSERT INTO province VALUES ('Sichuan','CN','488000');
INSERT INTO province VALUES ('Yemen','YE','527970');
INSERT INTO province VALUES ('Woroba','CI','31100');
INSERT INTO province VALUES ('Kostanai','KZ','196001');
INSERT INTO province VALUES ('Seychelles','SY','455');
INSERT INTO province VALUES ('Ternopilska','UA','13824');
INSERT INTO province VALUES ('Querétaro','MEX','11683');
INSERT INTO province VALUES ('Sakha','R','3083523');
INSERT INTO province VALUES ('Bulgaria','BG','110910');
INSERT INTO province VALUES ('An-Nīl al-Abyaḍ','SUD','30411');
INSERT INTO province VALUES ('Nevşehir','TR','5391');
INSERT INTO province VALUES ('Kalimantan Utara','RI','75468');
INSERT INTO province VALUES ('Cocos Islands','COCO','14');
INSERT INTO province VALUES ('Sulawesi Tenggara','RI','38067');
INSERT INTO province VALUES ('Cherkaska','UA','20916');
INSERT INTO province VALUES ('Salta','RA','155488');
INSERT INTO province VALUES ('Al-Qaḍārif','SUD','75263');
INSERT INTO province VALUES ('Vaslui','RO','5318');
INSERT INTO province VALUES ('Coimbra','P','3947');
INSERT INTO province VALUES ('Kaduna','NGR','45711');
INSERT INTO province VALUES ('Bihor','RO','7544');
INSERT INTO province VALUES ('Tokyo','J','2187');
INSERT INTO province VALUES ('Nizhnii Novgorodskaya','R','74800');
INSERT INTO province VALUES ('Ashanti','GH','24389');
INSERT INTO province VALUES ('Alborz','IR','5122');
INSERT INTO province VALUES ('Lagunes','CI','20450');
INSERT INTO province VALUES ('Baranya','H','4429');
INSERT INTO province VALUES ('Tonga','TO','748');
INSERT INTO province VALUES ('Braşov','RO','5363');
INSERT INTO province VALUES ('Acre','BR','152581');
INSERT INTO province VALUES ('Liberia','LB','111370');
INSERT INTO province VALUES ('Camagüey','C','15386');
INSERT INTO province VALUES ('Cunene','ANG','87342');
INSERT INTO province VALUES ('Geita','EAT','20054');
INSERT INTO province VALUES ('Podlaskie','PL','20187');
INSERT INTO province VALUES ('Gorj','RO','5601');
INSERT INTO province VALUES ('Skåne','S','11034');
INSERT INTO province VALUES ('Gabon','G','267670');
INSERT INTO province VALUES ('Pointe-Noire','RCB','44');
INSERT INTO province VALUES ('Kinshasa','CGO','9965');
INSERT INTO province VALUES ('Tabora','EAT','76150');
INSERT INTO province VALUES ('Örebro','S','8545');
INSERT INTO province VALUES ('Ancash','PE','35914');
INSERT INTO province VALUES ('Niamey','RN','402');
INSERT INTO province VALUES ('Zala','H','3783');
INSERT INTO province VALUES ('Hidalgo','MEX','20846');
INSERT INTO province VALUES ('Khmelnytska','UA','20629');
INSERT INTO province VALUES ('Amazonas','BR','1570745');
INSERT INTO province VALUES ('Anhui','CN','139900');
INSERT INTO province VALUES ('Singapore','SGP','632.6');
INSERT INTO province VALUES ('Somalia','SO','637660');
INSERT INTO province VALUES ('Sachsen','D','18419');
INSERT INTO province VALUES ('Gambia','WAG','11300');
INSERT INTO province VALUES ('Muslim Mindanao','RP','21065');
INSERT INTO province VALUES ('Central Visayas','RP','15885');
INSERT INTO province VALUES ('Campeche','MEX','57924');
INSERT INTO province VALUES ('Brunei','BRU','5770');
INSERT INTO province VALUES ('Świętokrzyskie','PL','11710');
INSERT INTO province VALUES ('Karaman','TR','8868');
INSERT INTO province VALUES ('Guangxi','CN','220400');
INSERT INTO province VALUES ('Bretagne','F','27207');
INSERT INTO province VALUES ('Bali','RI','5780');
INSERT INTO province VALUES ('al-Anbar','IRQ','138288');
INSERT INTO province VALUES ('Jawa Barat','RI','35377');
INSERT INTO province VALUES ('Cagayan Valley','RP','28228');
INSERT INTO province VALUES ('Gaziantep','TR','6844');
INSERT INTO province VALUES ('Diyarbakır','TR','15204');
INSERT INTO province VALUES ('al-Najaf','IRQ','28824');
INSERT INTO province VALUES ('Abuja','NGR','7753');
INSERT INTO province VALUES ('Illes Balears','E','4991');
INSERT INTO province VALUES ('Northwest Territories','CDN','1143793');
INSERT INTO province VALUES ('La Paz','BOL','133985');
INSERT INTO province VALUES ('Guizhou','CN','174000');
INSERT INTO province VALUES ('Falkland Islands','FALK','12173');
INSERT INTO province VALUES ('Timiş','RO','8696');
INSERT INTO province VALUES ('Sud-Ubangi','CGO','51648');
INSERT INTO province VALUES ('Galaţi','RO','4466');
INSERT INTO province VALUES ('Henan','CN','167000');
INSERT INTO province VALUES ('Mykolaïvska','UA','24585');
INSERT INTO province VALUES ('Apure','YV','76500');
INSERT INTO province VALUES ('Jiangxi','CN','164800');
INSERT INTO province VALUES ('Diourbel','SN','4824');
INSERT INTO province VALUES ('Sulawesi Utara','RI','13851');
INSERT INTO province VALUES ('Arusha','EAT','37576');
INSERT INTO province VALUES ('Vorarlberg','A','2601');
INSERT INTO province VALUES ('Palau','PAL','458');
INSERT INTO province VALUES ('Magdalena','CO','23188');
INSERT INTO province VALUES ('Duhouk','IRQ','6553');
INSERT INTO province VALUES ('Surkhandarya','UZ','20800');
INSERT INTO province VALUES ('Bauchi','NGR','49933');
INSERT INTO province VALUES ('Tumbes','PE','4669');
INSERT INTO province VALUES ('Negeri Sembilan','MAL','6686');
INSERT INTO province VALUES ('Kırklareli','TR','6299');
INSERT INTO province VALUES ('Bourgogne-Franche-Comté','F','47784');
INSERT INTO province VALUES ('Montana','USA','376962');
INSERT INTO province VALUES ('Brčko','BIH','493');
INSERT INTO province VALUES ('Uíge','ANG','58698');
INSERT INTO province VALUES ('Alberta','CDN','640081');
INSERT INTO province VALUES ('Umbria','I','8456');
INSERT INTO province VALUES ('Tverskaya','R','84100');
INSERT INTO province VALUES ('Koulikoro','RMM','95848');
INSERT INTO province VALUES ('Maryland','USA','25142');
INSERT INTO province VALUES ('Mwanza','EAT','9467');
INSERT INTO province VALUES ('Ecuador','EC','283560');
INSERT INTO province VALUES ('Giresun','TR','6831');
INSERT INTO province VALUES ('Ialomiţa','RO','4452');
INSERT INTO province VALUES ('Western Cape','RSA','129462');
INSERT INTO province VALUES ('Kyzylorda','KZ','226019');
INSERT INTO province VALUES ('Quintana Roo','MEX','42360');
INSERT INTO province VALUES ('Akmola','KZ','146219');
INSERT INTO province VALUES ('Las Tunas','C','6592');
INSERT INTO province VALUES ('Kalimantan Timur','RI','129067');
INSERT INTO province VALUES ('Kosovo','KOS','10887');
INSERT INTO province VALUES ('East of England','GB','19108');
INSERT INTO province VALUES ('Oppland','N','25192');
INSERT INTO province VALUES ('Kerbela','IRQ','5034');
INSERT INTO province VALUES ('Sofala','MOC','67753');
INSERT INTO province VALUES ('Kalimantan Selatan','RI','38744');
INSERT INTO province VALUES ('Södermanland','S','6102');
INSERT INTO province VALUES ('Delta','NGR','17239');
INSERT INTO province VALUES ('Volta','GH','20570');
INSERT INTO province VALUES ('Jämtland','S','49341');
INSERT INTO province VALUES ('Junín','PE','44197');
INSERT INTO province VALUES ('Rheinland-Pfalz','D','19854');
INSERT INTO province VALUES ('Abia','NGR','4902');
INSERT INTO province VALUES ('FATA','PK','27220');
INSERT INTO province VALUES ('Antioquia','CO','63612');
INSERT INTO province VALUES ('Bolívar','CO','25978');
INSERT INTO province VALUES ('Hims','SYR','42223');
INSERT INTO province VALUES ('Euskadi','E','7237');
INSERT INTO province VALUES ('Vila Real','P','4328');
INSERT INTO province VALUES ('Olomoucký','CZ','5266');
INSERT INTO province VALUES ('Tshopo','CGO','199567');
INSERT INTO province VALUES ('Khabarovskiy','R','752600');
INSERT INTO province VALUES ('Kasai','CGO','93784');
INSERT INTO province VALUES ('Sao Tome and Principe','STP','1001');
INSERT INTO province VALUES ('HaZafon','IL','4473');
INSERT INTO province VALUES ('Kagera','EAT','25265');
INSERT INTO province VALUES ('Texas','USA','676587');
INSERT INTO province VALUES ('Astrakhanskaya','R','44100');
INSERT INTO province VALUES ('Hatay','TR','5831');
INSERT INTO province VALUES ('Isle of Man','GBM','588');
INSERT INTO province VALUES ('Lebanon','RL','10400');
INSERT INTO province VALUES ('Cayman Islands','CAYM','262');
INSERT INTO province VALUES ('Nauru','NAU','21');
INSERT INTO province VALUES ('Cabinda','ANG','7270');
INSERT INTO province VALUES ('Sulawesi Selatan','RI','46717');
INSERT INTO province VALUES ('Kusini Pemba','EAT','332');
INSERT INTO province VALUES ('Győr-Moson-Sopron','H','4208');
INSERT INTO province VALUES ('Akhal','TM','97428');
INSERT INTO province VALUES ('Campania','I','13590');
INSERT INTO province VALUES ('North Dakota','USA','178711');
INSERT INTO province VALUES ('Sicilia','I','25711');
INSERT INTO province VALUES ('Kanagawa','J','2415');
INSERT INTO province VALUES ('Pasco','PE','25319');
INSERT INTO province VALUES ('Mato Grosso','BR','903358');
INSERT INTO province VALUES ('Bhutan','BHT','47000');
INSERT INTO province VALUES ('Kırşehir','TR','6530');
INSERT INTO province VALUES ('Overijssel','NL','3420');
INSERT INTO province VALUES ('Nouakchott','RIM','1000');
INSERT INTO province VALUES ('Trnavský','SK','4145');
INSERT INTO province VALUES ('Haryana','IND','44212');
INSERT INTO province VALUES ('Tlaxcala','MEX','3991');
INSERT INTO province VALUES ('Iowa','USA','144669');
INSERT INTO province VALUES ('Kerman','IR','180726');
INSERT INTO province VALUES ('Provence-Alpes-Côte d''Azur','F','31399');
INSERT INTO province VALUES ('Tennessee','USA','106798');
INSERT INTO province VALUES ('West Kazakhstan','KZ','151339');
INSERT INTO province VALUES ('District of Columbia','USA','158');
INSERT INTO province VALUES ('Ceará','BR','148825');
INSERT INTO province VALUES ('Tunceli','TR','7685');
INSERT INTO province VALUES ('Puglia','I','19357');
INSERT INTO province VALUES ('Magadanskaya','R','461400');
INSERT INTO province VALUES ('Ilocos','RP','13012');
INSERT INTO province VALUES ('Saint Martin','SMAR','54');
INSERT INTO province VALUES ('Équateur','CGO','103902');
INSERT INTO province VALUES ('Moskovskaya','R','45900');
INSERT INTO province VALUES ('Lagos','RCH','48583');
INSERT INTO province VALUES ('Francisco Morazán','HN','8618');
INSERT INTO province VALUES ('Comoros','COM','2170');
INSERT INTO province VALUES ('Amazonas','CO','109665');
INSERT INTO province VALUES ('Ouest','CAM','13892');
INSERT INTO province VALUES ('Atlántico','CO','3388');
INSERT INTO province VALUES ('Durango','MEX','123451');
INSERT INTO province VALUES ('Mpumalanga','RSA','76495');
INSERT INTO province VALUES ('New South Wales','AUS','800808');
INSERT INTO province VALUES ('Moldova','MD','33700');
INSERT INTO province VALUES ('Manisa','TR','13228');
INSERT INTO province VALUES ('Vermont','USA','23871');
INSERT INTO province VALUES ('Mariy-El','R','23200');
INSERT INTO province VALUES ('Taiwan','RC','36179');
INSERT INTO province VALUES ('Sverdlovskaya','R','194300');
INSERT INTO province VALUES ('Krym','UA','26080');
INSERT INTO province VALUES ('Emilia-Romagna','I','22445');
INSERT INTO province VALUES ('Ryazanskaya','R','39600');
INSERT INTO province VALUES ('Reunion','REUN','2510');
INSERT INTO province VALUES ('New Jersey','USA','19047');
INSERT INTO province VALUES ('Kirovskaya','R','120800');
INSERT INTO province VALUES ('Harghita','RO','6638');
INSERT INTO province VALUES ('Gharb al-Dārfūr','SUD','23000');
INSERT INTO province VALUES ('Kaffrine','SN','11262');
INSERT INTO province VALUES ('Benin','BEN','112620');
INSERT INTO province VALUES ('Nordrhein-Westfalen','D','34097');
INSERT INTO province VALUES ('Trentino-Alto Adige','I','13606');
INSERT INTO province VALUES ('Central African Republic','RCA','622980');
INSERT INTO province VALUES ('Olancho','HN','24057');
INSERT INTO province VALUES ('Assam','IND','78438');
INSERT INTO province VALUES ('Alaska','USA','1477953');
INSERT INTO province VALUES ('Maputo','MOC','22693');
INSERT INTO province VALUES ('Tuvalu','TUV','26');
INSERT INTO province VALUES ('Gifu','J','10621');
INSERT INTO province VALUES ('Ziguinchor','SN','7352');
INSERT INTO province VALUES ('Nord-Ouest','CAM','17300');
INSERT INTO province VALUES ('Lombardia','I','23862');
INSERT INTO province VALUES ('Sibiu','RO','5432');
INSERT INTO province VALUES ('Piemonte','I','25402');
INSERT INTO province VALUES ('Ríos','RCH','18429');
INSERT INTO province VALUES ('Tartus','SYR','1892');
INSERT INTO province VALUES ('Tombouctou','RMM','496611');
INSERT INTO province VALUES ('Fargʻona','UZ','6800');
INSERT INTO province VALUES ('Latvia','LV','64100');
INSERT INTO province VALUES ('Central','GH','9826');
INSERT INTO province VALUES ('Pulau Pinang','MAL','1048');
INSERT INTO province VALUES ('Khakasiya','R','61900');
INSERT INTO province VALUES ('Boreioy Aigaioy','GR','3835');
INSERT INTO province VALUES ('Benue','NGR','31276');
INSERT INTO province VALUES ('Chuvashia','R','18300');
INSERT INTO province VALUES ('Lusaka','Z','21896');
INSERT INTO province VALUES ('Calabarzon','RP','16873');
INSERT INTO province VALUES ('Halab','SYR','18500');
INSERT INTO province VALUES ('Maluku Utara','RI','31982');
INSERT INTO province VALUES ('Muğla','TR','12949');
INSERT INTO province VALUES ('Komárom-Esztergom','H','2264');
INSERT INTO province VALUES ('Shiga','J','4017');
INSERT INTO province VALUES ('Simiyu','EAT','25212');
INSERT INTO province VALUES ('Santander','CO','30537');
INSERT INTO province VALUES ('Copperbelt','Z','31328');
INSERT INTO province VALUES ('Dire Dawa','ETH','1558');
INSERT INTO province VALUES ('Queensland','AUS','1729958');
INSERT INTO province VALUES ('Vinnytska','UA','26492');
INSERT INTO province VALUES ('Nevada','USA','284332');
INSERT INTO province VALUES ('Basilicata','I','9994');
INSERT INTO province VALUES ('Amazonas','PE','39249');
INSERT INTO province VALUES ('Dimashq','SYR','105');
INSERT INTO province VALUES ('Tillabéri','RN','97251');
INSERT INTO province VALUES ('Northern','Z','147826');
INSERT INTO province VALUES ('Littoral','CAM','20248');
INSERT INTO province VALUES ('Mauritius','MS','2040');
INSERT INTO province VALUES ('Bursa','TR','10886');
INSERT INTO province VALUES ('Yangon','MYA','10276');
INSERT INTO province VALUES ('Ulyanovskaya','R','37300');
INSERT INTO province VALUES ('Tocantins','BR','277620');
INSERT INTO province VALUES ('Vitebsk','BY','40049');
INSERT INTO province VALUES ('Fukui','J','4189');
INSERT INTO province VALUES ('Namibe','ANG','57091');
INSERT INTO province VALUES ('Plzeňský','CZ','7560');
INSERT INTO province VALUES ('Arunachal Pradesh','IND','83743');
INSERT INTO province VALUES ('Kigoma','EAT','37040');
INSERT INTO province VALUES ('Al Qunaytirah','SYR','1861');
INSERT INTO province VALUES ('Choluteca','HN','4360');
INSERT INTO province VALUES ('Hyogo','J','8396');
INSERT INTO province VALUES ('Schwyz','CH','908');
INSERT INTO province VALUES ('Goa','IND','3702');
INSERT INTO province VALUES ('Aichi','J','5165');
INSERT INTO province VALUES ('Faroe Islands','FO','1400');
INSERT INTO province VALUES ('Prince Edward Island','CDN','5685');
INSERT INTO province VALUES ('North Ossetia-Alania','R','8000');
INSERT INTO province VALUES ('Al-Jouf','SA','100212');
INSERT INTO province VALUES ('Greenland','GL','2175600');
INSERT INTO province VALUES ('Dakar','SN','547');
INSERT INTO province VALUES ('Lualaba','CGO','121308');
INSERT INTO province VALUES ('Mordoviya','R','26200');
INSERT INTO province VALUES ('Buenos Aires','RA','307571');
INSERT INTO province VALUES ('Braganca','P','6608');
INSERT INTO province VALUES ('Zamboanga Peninsula','RP','17046');
INSERT INTO province VALUES ('Sankuru','CGO','104331');
INSERT INTO province VALUES ('Beja','P','10225');
INSERT INTO province VALUES ('Kilimanjaro','EAT','13250');
INSERT INTO province VALUES ('Savanes','CI','40200');
INSERT INTO province VALUES ('Rondônia','BR','237576');
INSERT INTO province VALUES ('Andalucía','E','87585');
INSERT INTO province VALUES ('Suriname','SME','163270');
INSERT INTO province VALUES ('Kyoto','J','4613');
INSERT INTO province VALUES ('Lipetskaya','R','24100');
INSERT INTO province VALUES ('Haut-Lomami','CGO','108204');
INSERT INTO province VALUES ('Lvivska','UA','21831');
INSERT INTO province VALUES ('Northern Mariana Islands','NMIS','477');
INSERT INTO province VALUES ('Žilinský','SK','6808');
INSERT INTO province VALUES ('El Salvador','ES','21040');
INSERT INTO province VALUES ('Punjab','PK','205345');
INSERT INTO province VALUES ('Leningradskaya','R','83908');
INSERT INTO province VALUES ('Panamá','PA','11289');
INSERT INTO province VALUES ('Berlin','D','891');
INSERT INTO province VALUES ('Sjælland','DK','7273');
INSERT INTO province VALUES ('Islas de la Bahía','HN','236');
INSERT INTO province VALUES ('Tunisia','TN','163610');
INSERT INTO province VALUES ('Delhi','IND','1483');
INSERT INTO province VALUES ('Sogn og Fjordane','N','18623');
INSERT INTO province VALUES ('Bitlis','TR','7094');
INSERT INTO province VALUES ('Limburg','B','2422');
INSERT INTO province VALUES ('Ocotepeque','HN','1630');
INSERT INTO province VALUES ('Sikkim','IND','7096');
INSERT INTO province VALUES ('Gibraltar','GBZ','6.5');
INSERT INTO province VALUES ('Huila','CO','19890');
INSERT INTO province VALUES ('Buxoro','UZ','39400');
INSERT INTO province VALUES ('Kayin','MYA','30382');
INSERT INTO province VALUES ('Schleswig-Holstein','D','15799');
INSERT INTO province VALUES ('Chaouia Ouardigha','MA','7010');
INSERT INTO province VALUES ('Tarija','BOL','37623');
INSERT INTO province VALUES ('Gansu','CN','366500');
INSERT INTO province VALUES ('Ciego de Ávila','C','6971');
INSERT INTO province VALUES ('Brest','BY','32790');
INSERT INTO province VALUES ('Veraguas','PA','10587');
INSERT INTO province VALUES ('Libya','LAR','1759540');
INSERT INTO province VALUES ('Aysén','RCH','108494');
INSERT INTO province VALUES ('Kaluzhskaya','R','29900');
INSERT INTO province VALUES ('Huánuco','PE','36848');
INSERT INTO province VALUES ('Castilla y León','E','94351');
INSERT INTO province VALUES ('Kymenlaakso','SF','5149');
INSERT INTO province VALUES ('Khulna','BD','22284');
INSERT INTO province VALUES ('Western','GH','23921');
INSERT INTO province VALUES ('Baghdad','IRQ','4555');
INSERT INTO province VALUES ('Sivas','TR','28567');
INSERT INTO province VALUES ('Kuala Lumpur','MAL','243');
INSERT INTO province VALUES ('Oberösterreich','A','11979');
INSERT INTO province VALUES ('Mérida','YV','11300');
INSERT INTO province VALUES ('Harari','ETH','333');
INSERT INTO province VALUES ('Rangpur','BD','16184');
INSERT INTO province VALUES ('Antigua and Barbuda','AG','442');
INSERT INTO province VALUES ('Středočeský','CZ','11014');
INSERT INTO province VALUES ('Hodh El Gharbi','RIM','53400');
INSERT INTO province VALUES ('Kagawa','J','1876');
INSERT INTO province VALUES ('Caldas','CO','7888');
INSERT INTO province VALUES ('Kédougou','SN','16800');
INSERT INTO province VALUES ('Nariño','CO','33268');
INSERT INTO province VALUES ('Herrera','PA','2362');
INSERT INTO province VALUES ('Greater Accra','GH','3245');
INSERT INTO province VALUES ('Los Santos','PA','3809');
INSERT INTO province VALUES ('Balochistan','PK','347190');
INSERT INTO province VALUES ('Djibouti','DJI','22000');
INSERT INTO province VALUES ('Zonguldak','TR','3309');
INSERT INTO province VALUES ('Zhambyl','KZ','144264');
INSERT INTO province VALUES ('Podkarpackie','PL','17845');
INSERT INTO province VALUES ('Oaxaca','MEX','93793');
INSERT INTO province VALUES ('Laos','LAO','236800');
INSERT INTO province VALUES ('Tanga','EAT','26677');
INSERT INTO province VALUES ('Jamaica','JA','10991');
INSERT INTO province VALUES ('Ash-Shamālīyah','SUD','348765');
INSERT INTO province VALUES ('Lakshadweep','IND','30');
INSERT INTO province VALUES ('Tirol','A','12640');
INSERT INTO province VALUES ('Janūb Kurdufān','SUD','79470');
INSERT INTO province VALUES ('Norrbotten','S','98244');
INSERT INTO province VALUES ('Extrême-Nord','CAM','34263');
INSERT INTO province VALUES ('Banten','RI','9662');
INSERT INTO province VALUES ('Arequipa','PE','63345');
INSERT INTO province VALUES ('Pohjois-Savo','SF','16768');
INSERT INTO province VALUES ('Malta','M','316');
INSERT INTO province VALUES ('Huambo','ANG','34270');
INSERT INTO province VALUES ('Lazio','I','17235');
INSERT INTO province VALUES ('Hedmark','N','27397');
INSERT INTO province VALUES ('Midtjylland','DK','13124');
INSERT INTO province VALUES ('Okinawa','J','2276');
INSERT INTO province VALUES ('Carabobo','YV','4369');
INSERT INTO province VALUES ('Friesland','NL','5748');
INSERT INTO province VALUES ('Al Ladhiqiyah','SYR','2297');
INSERT INTO province VALUES ('Giurgiu','RO','3526');
INSERT INTO province VALUES ('La Pampa','RA','143440');
INSERT INTO province VALUES ('Tomskaya','R','316900');
INSERT INTO province VALUES ('Mogilev','BY','29079');
INSERT INTO province VALUES ('Croatia','HR','56538');
INSERT INTO province VALUES ('Thessalias','GR','14036');
INSERT INTO province VALUES ('Souss Massa Daraa','MA','70880');
INSERT INTO province VALUES ('Qoraqalpogʻiston','UZ','165590');
INSERT INTO province VALUES ('Hail','SA','103887');
INSERT INTO province VALUES ('Erzurum','TR','25330');
INSERT INTO province VALUES ('Amasya','TR','5703');
INSERT INTO province VALUES ('Budapest','H','525');
INSERT INTO province VALUES ('Chaco','RA','99633');
INSERT INTO province VALUES ('Ivanovskaya','R','23900');
INSERT INTO province VALUES ('Ishikawa','J','4185');
INSERT INTO province VALUES ('Rabat Sale Zemmour Zaer','MA','9580');
INSERT INTO province VALUES ('Yobe','NGR','46909');
INSERT INTO province VALUES ('Al-Kharṭūm','SUD','22142');
INSERT INTO province VALUES ('Corrientes','RA','88199');
INSERT INTO province VALUES ('Puntarenas','CR','11265');
INSERT INTO province VALUES ('Gombe','NGR','17982');
INSERT INTO province VALUES ('Guanajuato','MEX','30608');
INSERT INTO province VALUES ('Adana','TR','14045');
INSERT INTO province VALUES ('Valenciana','E','23253');
INSERT INTO province VALUES ('Santiago de Estero','RA','136351');
INSERT INTO province VALUES ('Tamaulipas','MEX','80174');
INSERT INTO province VALUES ('Valle d''Aosta','I','3263');
INSERT INTO province VALUES ('Aomori','J','9644');
INSERT INTO province VALUES ('Altayskiy','R','169100');
INSERT INTO province VALUES ('Cuanza Sul','ANG','55600');
INSERT INTO province VALUES ('Chiriquí','PA','6490');
INSERT INTO province VALUES ('Copán','HN','3242');
INSERT INTO province VALUES ('Mayabeque','C','3743');
INSERT INTO province VALUES ('Cross River','NGR','21636');
INSERT INTO province VALUES ('Sinaloa','MEX','57377');
INSERT INTO province VALUES ('Nidwalden','CH','276');
INSERT INTO province VALUES ('Minas Gerais','BR','586528');
INSERT INTO province VALUES ('Sumska','UA','23832');
INSERT INTO province VALUES ('Yunnan','CN','436200');
INSERT INTO province VALUES ('North East','GB','8573');
INSERT INTO province VALUES ('Manipur','IND','22327');
INSERT INTO province VALUES ('Bocas del Toro','PA','4657');
INSERT INTO province VALUES ('Intibucá','HN','3122');
INSERT INTO province VALUES ('Lékoumou','RCB','20950');
INSERT INTO province VALUES ('Utrecht','NL','1449');
INSERT INTO province VALUES ('Eritrea','ER','121320');
INSERT INTO province VALUES ('Tahoua','RN','113371');
INSERT INTO province VALUES ('Ibaraki','J','6095');
INSERT INTO province VALUES ('La Libertad','PE','25499');
INSERT INTO province VALUES ('Tshuapa','CGO','132957');
INSERT INTO province VALUES ('Mon','MYA','12296');
INSERT INTO province VALUES ('Chelyabinskaya','R','87900');
INSERT INTO province VALUES ('Kogi','NGR','29581');
INSERT INTO province VALUES ('Kalmar','S','11217');
INSERT INTO province VALUES ('Qasqadaryo','UZ','28400');
INSERT INTO province VALUES ('Tianjin','CN','11300');
INSERT INTO province VALUES ('Dalarna','S','28188');
INSERT INTO province VALUES ('Almaty','KZ','223924');
INSERT INTO province VALUES ('Connecticut','USA','12542');
INSERT INTO province VALUES ('Ehime','J','5678');
INSERT INTO province VALUES ('Aydın','TR','7904');
INSERT INTO province VALUES ('Kurskaya','R','29800');
INSERT INTO province VALUES ('Sierra Leone','SLE','71740');
INSERT INTO province VALUES ('Artemisa','C','4003');
INSERT INTO province VALUES ('Muş','TR','8067');
INSERT INTO province VALUES ('Niedersachsen','D','47613');
INSERT INTO province VALUES ('Västerbotten','S','55186');
INSERT INTO province VALUES ('North and South Central Coast','VN','95834.5');
INSERT INTO province VALUES ('Michoacán','MEX','58643');
INSERT INTO province VALUES ('Mato Grosso do Sul','BR','357125');
INSERT INTO province VALUES ('Pitcairn','PITC','47');
INSERT INTO province VALUES ('Brong Ahafo','GH','39557');
INSERT INTO province VALUES ('Komi','R','415900');
INSERT INTO province VALUES ('Al-Baḥr al-Aḥmar','SUD','218887');
INSERT INTO province VALUES ('Marche','I','9365');
INSERT INTO province VALUES ('Meghalaya','IND','22429');
INSERT INTO province VALUES ('Jigawa','NGR','24515');
INSERT INTO province VALUES ('Somali','ETH','327068');
INSERT INTO province VALUES ('Kepulauan Riau','RI','8201');
INSERT INTO province VALUES ('Al-Hudud ash Shamaliyah','SA','111797');
INSERT INTO province VALUES ('Yalova','TR','850');
INSERT INTO province VALUES ('Karelia','R','172400');
INSERT INTO province VALUES ('Santa Catarina','BR','95346');
INSERT INTO province VALUES ('San Martín','PE','51253');
INSERT INTO province VALUES ('Wyoming','USA','251470');
INSERT INTO province VALUES ('Washington','USA','172119');
INSERT INTO province VALUES ('Akita','J','11636');
INSERT INTO province VALUES ('Dâmboviţa','RO','4054');
INSERT INTO province VALUES ('Nouvelle-Aquitaine','F','84061');
INSERT INTO province VALUES ('Samarskaya','R','53600');
INSERT INTO province VALUES ('Luhanska','UA','26683');
INSERT INTO province VALUES ('Jihočeský','CZ','10056');
INSERT INTO province VALUES ('Catalunya','E','32163');
INSERT INTO province VALUES ('Almaty City','KZ','319');
INSERT INTO province VALUES ('Kamchatka','R','472300');
INSERT INTO province VALUES ('Gümüşhane','TR','6437');
INSERT INTO province VALUES ('Oregon','USA','248608');
INSERT INTO province VALUES ('Taza Al Hoceima Taounate','MA','24155');
INSERT INTO province VALUES ('Mersin','TR','15512');
INSERT INTO province VALUES ('Vladimirskaya','R','29084');
INSERT INTO province VALUES ('Leiria','P','3515');
INSERT INTO province VALUES ('Amurskaya','R','363700');
INSERT INTO province VALUES ('Sucre','YV','11800');
INSERT INTO province VALUES ('Jász-Nagykun-Szolnok','H','5581');
INSERT INTO province VALUES ('Sumatera Barat','RI','42012');
INSERT INTO province VALUES ('Nuevo Léon','MEX','64220');
INSERT INTO province VALUES ('Osun','NGR','8699');
INSERT INTO province VALUES ('Roraima','BR','224298');
INSERT INTO province VALUES ('Kwango','CGO','89974');
INSERT INTO province VALUES ('Casanare','CO','44640');
INSERT INTO province VALUES ('Bougainville','PNG','9300');
INSERT INTO province VALUES ('Andaman and Nicobar Islands','IND','8249');
INSERT INTO province VALUES ('Arauca','CO','23818');
INSERT INTO province VALUES ('Coquimbo','RCH','40579');
INSERT INTO province VALUES ('Georgia','GE','69700');
INSERT INTO province VALUES ('Cienfuegos','C','4188');
INSERT INTO province VALUES ('Aksaray','TR','7965');
INSERT INTO province VALUES ('Sri Lanka','CL','65610');
INSERT INTO province VALUES ('Imo','NGR','5182');
INSERT INTO province VALUES ('Viana do Castelo','P','2255');
INSERT INTO province VALUES ('Grand Est','F','57433');
INSERT INTO province VALUES ('Cuanza Norte','ANG','24110');
INSERT INTO province VALUES ('Tierra del Fuego','RA','21571');
INSERT INTO province VALUES ('Markazi','IR','29127');
INSERT INTO province VALUES ('Solomon Islands','SOL','28450');
INSERT INTO province VALUES ('Kayah','MYA','11731');
INSERT INTO province VALUES ('Ningxia','CN','66400');
INSERT INTO province VALUES ('Hajdú-Bihar','H','6210');
INSERT INTO province VALUES ('Saint Vincent and the Grenadines','WV','389');
INSERT INTO province VALUES ('Krasnoyarsk','R','2339700');
INSERT INTO province VALUES ('Pavlodar','KZ','124800');
INSERT INTO province VALUES ('Saratovskaya','R','100200');
INSERT INTO province VALUES ('Slovenia','SLO','20256');
INSERT INTO province VALUES ('Saint Barthelemy','SBAR','21');
INSERT INTO province VALUES ('Kaolack','SN','5357');
INSERT INTO province VALUES ('Norte de Santander','CO','21658');
INSERT INTO province VALUES ('West Azarbayejan','IR','37411');
INSERT INTO province VALUES ('Bihar','IND','94163');
INSERT INTO province VALUES ('Michigan','USA','146435');
INSERT INTO province VALUES ('Al Hasakah','SYR','23334');
INSERT INTO province VALUES ('Upper East','GH','8842');
INSERT INTO province VALUES ('Kaliningradskaya','R','15100');
INSERT INTO province VALUES ('Bingöl','TR','8253');
INSERT INTO province VALUES ('Nayarit','MEX','27815');
INSERT INTO province VALUES ('Bas-Sassandra','CI','28350');
INSERT INTO province VALUES ('Ilfov','RO','1583');
INSERT INTO province VALUES ('Tarapacá','RCH','42225');
INSERT INTO province VALUES ('Pando','BOL','63827');
INSERT INTO province VALUES ('Toshkent City','UZ','300');
INSERT INTO province VALUES ('Dolnośląskie','PL','19946');
INSERT INTO province VALUES ('Indiana','USA','92789');
INSERT INTO province VALUES ('Navoiy','UZ','110800');
INSERT INTO province VALUES ('Gharb Kurdufān','SUD','111373');
INSERT INTO province VALUES ('Uttarakhand','IND','53483');
INSERT INTO province VALUES ('Sud','CAM','47191');
INSERT INTO province VALUES ('Ağrı','TR','11498');
INSERT INTO province VALUES ('Khersonska','UA','28461');
INSERT INTO province VALUES ('Diala','IRQ','17685');
INSERT INTO province VALUES ('Asturias','E','10603');
INSERT INTO province VALUES ('Himachal Pradesh','IND','55673');
INSERT INTO province VALUES ('Dashhowuz','TM','73600');
INSERT INTO province VALUES ('North West','RSA','104882');
INSERT INTO province VALUES ('Okayama','J','7113');
INSERT INTO province VALUES ('Northern Mindanao','RP','20496');
INSERT INTO province VALUES ('al-Muthanna','IRQ','51740');
INSERT INTO province VALUES ('Serbia','SRB','77474');
INSERT INTO province VALUES ('Akershus','N','4917');
INSERT INTO province VALUES ('Ingushskaya','R','3750');
INSERT INTO province VALUES ('Kurdestan','IR','29137');
INSERT INTO province VALUES ('Pinar del Río','C','8883');
INSERT INTO province VALUES ('Zhejiang','CN','101800');
INSERT INTO province VALUES ('Kidal','RMM','151430');
INSERT INTO province VALUES ('Vanuatu','VU','14760');
INSERT INTO province VALUES ('Puerto Rico','PR','8870');
INSERT INTO province VALUES ('Baden-Württemberg','D','35751');
INSERT INTO province VALUES ('Cortés','HN','3923');
INSERT INTO province VALUES ('İstanbul','TR','5315');
INSERT INTO province VALUES ('Nagano','J','13562');
INSERT INTO province VALUES ('Lappia','SF','92674');
INSERT INTO province VALUES ('Sikasso','RMM','70280');
INSERT INTO province VALUES ('Ilam','IR','20133');
INSERT INTO province VALUES ('Punjab','IND','50362');
INSERT INTO province VALUES ('Madrid','E','8022');
INSERT INTO province VALUES ('Tulskaya','R','25700');
INSERT INTO province VALUES ('Guyana','GUY','214970');
INSERT INTO province VALUES ('Gävleborg','S','18198');
INSERT INTO province VALUES ('Golestan','IR','20367');
INSERT INTO province VALUES ('Western Australia','AUS','2526574');
INSERT INTO province VALUES ('Cuvette-Ouest','RCB','26600');
INSERT INTO province VALUES ('Pennsylvania','USA','115883');
INSERT INTO province VALUES ('Guernsey','GBG','194');
INSERT INTO province VALUES ('Ashgabat','TM','100');
INSERT INTO province VALUES ('Elazığ','TR','9281');
INSERT INTO province VALUES ('Bío-Bío','RCH','37068');
INSERT INTO province VALUES ('Brakna','RIM','33000');
INSERT INTO province VALUES ('Heilongjiang','CN','463600');
INSERT INTO province VALUES ('Eastern Cape','RSA','168966');
INSERT INTO province VALUES ('Semnan','IR','97491');
INSERT INTO province VALUES ('Mopti','RMM','79017');
INSERT INTO province VALUES ('Malawi','MW','118480');
INSERT INTO province VALUES ('Nord-Ubangi','CGO','56644');
INSERT INTO province VALUES ('Permskij','R','160600');
INSERT INTO province VALUES ('Dayr az Zawr','SYR','33060');
INSERT INTO province VALUES ('Nueva Esparta','YV','1151');
INSERT INTO province VALUES ('Minsk City','BY','305');
INSERT INTO province VALUES ('Wasit','IRQ','17153');
INSERT INTO province VALUES ('Granma','C','8374');
INSERT INTO province VALUES ('Northern Territory','AUS','1348198');
INSERT INTO province VALUES ('Shimane','J','6707');
INSERT INTO province VALUES ('Nordland','N','38482');
INSERT INTO province VALUES ('Chernivetska','UA','8096');
INSERT INTO province VALUES ('Papua','RI','319036');
INSERT INTO province VALUES ('Tadla Azilal','MA','17125');
INSERT INTO province VALUES ('Košický','SK','6753');
INSERT INTO province VALUES ('Bengo','ANG','31371');
INSERT INTO province VALUES ('Saint-Louis','SN','19241');
INSERT INTO province VALUES ('Eswatini','SD','17360');
INSERT INTO province VALUES ('Heredia','CR','2656');
INSERT INTO province VALUES ('Montagnes','CI','30825');
INSERT INTO province VALUES ('Rwanda','RWA','26340');
INSERT INTO province VALUES ('Abruzzo','I','10762');
INSERT INTO province VALUES ('Hainan','CN','34300');
INSERT INTO province VALUES ('Mara','EAT','21760');
INSERT INTO province VALUES ('Wisconsin','USA','140268');
INSERT INTO province VALUES ('Bashkortostan','R','143600');
INSERT INTO province VALUES ('East Azarbayejan','IR','45651');
INSERT INTO province VALUES ('Putrajaya','MAL','49');
INSERT INTO province VALUES ('Kerala','IND','38852');
INSERT INTO province VALUES ('Algeria','DZ','2381740');
INSERT INTO province VALUES ('Chubut','RA','224686');
INSERT INTO province VALUES ('Liège','B','3862');
INSERT INTO province VALUES ('Kabardino-Balkarskaya','R','12500');
INSERT INTO province VALUES ('Suceava','RO','8553');
INSERT INTO province VALUES ('Sannār','SUD','37844');
INSERT INTO province VALUES ('Wielkopolskie','PL','29826');
INSERT INTO province VALUES ('Galicia','E','29559');
INSERT INTO province VALUES ('DI Yogyakarta','RI','3133');
INSERT INTO province VALUES ('Yaracuy','YV','7100');
INSERT INTO province VALUES ('Occitanie','F','72724');
INSERT INTO province VALUES ('Gambella','ETH','29782');
INSERT INTO province VALUES ('Gotland','S','3151');
INSERT INTO province VALUES ('Hunedoara','RO','7062');
INSERT INTO province VALUES ('Miyazaki','J','7735');
INSERT INTO province VALUES ('Janūb Dārfūr','SUD','72000');
INSERT INTO province VALUES ('Ivano-Frankivska','UA','13927');
INSERT INTO province VALUES ('North Khorasan','IR','28434');
INSERT INTO province VALUES ('Isparta','TR','8871');
INSERT INTO province VALUES ('Zambézia','MOC','103478');
INSERT INTO province VALUES ('Zuid-Holland','NL','3418');
INSERT INTO province VALUES ('Iceland','IS','103000');
INSERT INTO province VALUES ('Coahuila','MEX','151562');
INSERT INTO province VALUES ('Île-de-France','F','12012');
INSERT INTO province VALUES ('Tamil Nadu','IND','130060');
INSERT INTO province VALUES ('Western','EAU','55276.6');
INSERT INTO province VALUES ('Mai-Ndombe','CGO','127465');
INSERT INTO province VALUES ('Telemark','N','15296');
INSERT INTO province VALUES ('Luzern','CH','1493');
INSERT INTO province VALUES ('Aktobe','KZ','300629');
INSERT INTO province VALUES ('Ipeiroy','GR','9203');
INSERT INTO province VALUES ('Inchiri','RIM','46800');
INSERT INTO province VALUES ('Aargau','CH','1403');
INSERT INTO province VALUES ('Addis Ababa','ETH','526');
INSERT INTO province VALUES ('Normandie','F','29906');
INSERT INTO province VALUES ('Kilis','TR','1427');
INSERT INTO province VALUES ('Maule','RCH','30296');
INSERT INTO province VALUES ('Libertador General Bernardo O''Higgins','RCH','16387');
INSERT INTO province VALUES ('Dushanbe','TJ','100');
INSERT INTO province VALUES ('Caraga','RP','21478');
INSERT INTO province VALUES ('Lunda-Norte','ANG','103760');
INSERT INTO province VALUES ('North Carolina','USA','125920');
INSERT INTO province VALUES ('Alagoas','BR','27767');
INSERT INTO province VALUES ('Tabasco','MEX','24737');
INSERT INTO province VALUES ('Afghanistan','AFG','647500');
INSERT INTO province VALUES ('Guidimagha','RIM','10300');
INSERT INTO province VALUES ('Entre Ríos','RA','78781');
INSERT INTO province VALUES ('Al-Madinah Al-Monawarah','SA','151990');
INSERT INTO province VALUES ('Astana','KZ','710');
INSERT INTO province VALUES ('Likouala','RCB','66044');
INSERT INTO province VALUES ('Stereas Elladas','GR','15549');
INSERT INTO province VALUES ('Nampula','MOC','79010');
INSERT INTO province VALUES ('Östergötland','S','10602');
INSERT INTO province VALUES ('Cook Islands','COOK','240');
INSERT INTO province VALUES ('San Luis','RA','76748');
INSERT INTO province VALUES ('Nunavut','CDN','1877787');
INSERT INTO province VALUES ('Azad Jammu and Kashmir','PK','13297');
INSERT INTO province VALUES ('Lambayeque','PE','14231');
INSERT INTO province VALUES ('Fukushima','J','13782');
INSERT INTO province VALUES ('Dytikis Elladas','GR','11350');
INSERT INTO province VALUES ('Tyumenskaya','R','150100');
INSERT INTO province VALUES ('Antalya','TR','20790');
INSERT INTO province VALUES ('Odisha','IND','155707');
INSERT INTO province VALUES ('Ngöbe Buglé','PA','6814');
INSERT INTO province VALUES ('La Paz','HN','2330');
INSERT INTO province VALUES ('Karabük','TR','4108');
INSERT INTO province VALUES ('American Samoa','AMSA','199');
INSERT INTO province VALUES ('Kurganskaya','R','71000');
INSERT INTO province VALUES ('Guantánamo','C','6167');
INSERT INTO province VALUES ('Pirkanmaa','SF','12585');
INSERT INTO province VALUES ('Albania','AL','28750');
INSERT INTO province VALUES ('Artvin','TR','7367');
INSERT INTO province VALUES ('Cesar','CO','22905');
INSERT INTO province VALUES ('French Polynesia','FPOL','4167');
INSERT INTO province VALUES ('Kars','TR','10139');
INSERT INTO province VALUES ('Zhytomyrska','UA','29827');
INSERT INTO province VALUES ('Andhra Pradesh','IND','160205');
INSERT INTO province VALUES ('Csongrád','H','4262');
INSERT INTO province VALUES ('Trabzon','TR','4664');
INSERT INTO province VALUES ('Fribourg','CH','1670');
INSERT INTO province VALUES ('Metro Manila','RP','633');
INSERT INTO province VALUES ('Ucayali','PE','102410');
INSERT INTO province VALUES ('South-Kazakhstan','KZ','117249');
INSERT INTO province VALUES ('Nord-Kivu','CGO','59483');
INSERT INTO province VALUES ('Bács-Kiskun','H','8444');
INSERT INTO province VALUES ('Dadra and Nagar Haveli','IND','491');
INSERT INTO province VALUES ('Saint Helena','HELX','391');
INSERT INTO province VALUES ('Sulawesi Barat','RI','16787');
INSERT INTO province VALUES ('New Brunswick','CDN','71377');
INSERT INTO province VALUES ('Southeast','VN','23590.8');
INSERT INTO province VALUES ('Bahamas','BS','13940');
INSERT INTO province VALUES ('Esfahan','IR','107018');
INSERT INTO province VALUES ('Volynska','UA','20144');
INSERT INTO province VALUES ('South Dakota','USA','196350');
INSERT INTO province VALUES ('Martinique','MART','1128');
INSERT INTO province VALUES ('Limburg','NL','2208');
INSERT INTO province VALUES ('Afyonkarahisar','TR','14718');
INSERT INTO province VALUES ('Santa Bárbara','HN','5024');
INSERT INTO province VALUES ('Inhambane','MOC','68775');
INSERT INTO province VALUES ('Veracruz','MEX','71820');
INSERT INTO province VALUES ('Kayes','RMM','119743');
INSERT INTO province VALUES ('Mongala','CGO','58141');
INSERT INTO province VALUES ('Haut-Uele','CGO','89683');
INSERT INTO province VALUES ('Madre de Dios','PE','85300');
INSERT INTO province VALUES ('Vas','H','3336');
INSERT INTO province VALUES ('Atlántida','HN','4372');
INSERT INTO province VALUES ('Sucre','CO','10917');
INSERT INTO province VALUES ('Hauts-de-France','F','31813');
INSERT INTO province VALUES ('Mardin','TR','8806');
INSERT INTO province VALUES ('Algarve','P','4960');
INSERT INTO province VALUES ('Bern','CH','5959');
INSERT INTO province VALUES ('Ceuta','CEU','18');
INSERT INTO province VALUES ('Sălaj','RO','3864');
INSERT INTO province VALUES ('Hessen','D','21114');
INSERT INTO province VALUES ('Ogun','NGR','16980');
INSERT INTO province VALUES ('Hainaut','B','3785');
INSERT INTO province VALUES ('Evora','P','7393');
INSERT INTO province VALUES ('Sharq Dārfūr','SUD','55000');
INSERT INTO province VALUES ('Ústecký','CZ','5334');
INSERT INTO province VALUES ('Callao','PE','146');
INSERT INTO province VALUES ('Aragón','E','47721');
INSERT INTO province VALUES ('Çankırı','TR','7491');
INSERT INTO province VALUES ('East Midlands','GB','15606');
INSERT INTO province VALUES ('Zaire','ANG','40130');
INSERT INTO province VALUES ('Poltavska','UA','28750');
INSERT INTO province VALUES ('Pest','H','6391');
INSERT INTO province VALUES ('Calabria','I','15080');
INSERT INTO province VALUES ('Uusimaa','SF','9097');
INSERT INTO province VALUES ('Telangana','IND','114840');
INSERT INTO province VALUES ('Centre-Val de Loire','F','39150');
INSERT INTO province VALUES ('Niğde','TR','7365');
INSERT INTO province VALUES ('Portalegre','P','6065');
INSERT INTO province VALUES ('Pohjois-Pohjanmaa','SF','36815');
INSERT INTO province VALUES ('Małopolskie','PL','15182');
INSERT INTO province VALUES ('Bié','ANG','70314');
INSERT INTO province VALUES ('Doukala Abda','MA','13285');
INSERT INTO province VALUES ('Lindi','EAT','66040');
INSERT INTO province VALUES ('Northern Cape','RSA','372889');
INSERT INTO province VALUES ('Brandenburg','D','29483');
INSERT INTO province VALUES ('Malatya','TR','12102');
INSERT INTO province VALUES ('Colorado','USA','268431');
INSERT INTO province VALUES ('Mie','J','5777');
INSERT INTO province VALUES ('North Macedonia','MK','25333');
INSERT INTO province VALUES ('Noord-Brabant','NL','5081');
INSERT INTO province VALUES ('Beijing','CN','16808');
INSERT INTO province VALUES ('Darién','PA','11892');
INSERT INTO province VALUES ('Cusco','PE','71986');
INSERT INTO province VALUES ('Delta Amacuro','YV','40200');
INSERT INTO province VALUES ('Ohio','USA','105829');
INSERT INTO province VALUES ('Kwara','NGR','34467');
INSERT INTO province VALUES ('Rogaland','N','9375');
INSERT INTO province VALUES ('Tekirdağ','TR','6342');
INSERT INTO province VALUES ('West Bank','WB','5655');
INSERT INTO province VALUES ('Dhaka','BD','20692');
INSERT INTO province VALUES ('Luxembourg','B','4439');
INSERT INTO province VALUES ('Haiti','RH','27750');
INSERT INTO province VALUES ('South Carolina','USA','77857');
INSERT INTO province VALUES ('Baja California','MEX','71445');
INSERT INTO province VALUES ('Osmaniye','TR','3195');
INSERT INTO province VALUES ('Troms','N','25862');
INSERT INTO province VALUES ('Vologodskaya','R','145700');
INSERT INTO province VALUES ('Nova Scotia','CDN','52939');
INSERT INTO province VALUES ('Kagoshima','J','9188');
INSERT INTO province VALUES ('Mymensingh','BD','10485');
INSERT INTO province VALUES ('Guadeloupe','GUAD','1628');
INSERT INTO province VALUES ('Adamawa','NGR','38823');
INSERT INTO province VALUES ('South Australia','AUS','984179');
INSERT INTO province VALUES ('Lima City','PE','2670');
INSERT INTO province VALUES ('Burgenland','A','3961');
INSERT INTO province VALUES ('Kebbi','NGR','37727');
INSERT INTO province VALUES ('British Columbia','CDN','922509');
INSERT INTO province VALUES ('Noord-Holland','NL','4090');
INSERT INTO province VALUES ('Hokkaido','J','83456');
INSERT INTO province VALUES ('Togo','RT','56790');
INSERT INTO province VALUES ('Jiangsu','CN','102600');
INSERT INTO province VALUES ('Belize','BZ','22960');
INSERT INTO province VALUES ('Jalisco','MEX','78599');
INSERT INTO province VALUES ('North-Kazakhstan','KZ','97993');
INSERT INTO province VALUES ('Kronoberg','S','8466');
INSERT INTO province VALUES ('Nineveh','IRQ','37323');
INSERT INTO province VALUES ('Kyïvska','UA','28121');
INSERT INTO province VALUES ('Mendoza','RA','148827');
INSERT INTO province VALUES ('Abidjan','CI','2150');
INSERT INTO province VALUES ('Gharb Chrarda Beni Hssen','MA','8805');
INSERT INTO province VALUES ('Tagant','RIM','98340');
INSERT INTO province VALUES ('Batman','TR','4659');
INSERT INTO province VALUES ('Nagaland','IND','16579');
INSERT INTO province VALUES ('Kastamonu','TR','13157');
INSERT INTO province VALUES ('Santiago','RCH','15403');
INSERT INTO province VALUES ('Rio Grande do Norte','BR','52796');
INSERT INTO province VALUES ('Lomami','CGO','56426');
INSERT INTO province VALUES ('Niassa','MOC','122827');
INSERT INTO province VALUES ('Puebla','MEX','34289');
INSERT INTO province VALUES ('Ionion Nison','GR','2306');
INSERT INTO province VALUES ('Kusini Unguja','EAT','854');
INSERT INTO province VALUES ('Khuzestan','IR','64055');
INSERT INTO province VALUES ('Oita','J','6339');
INSERT INTO province VALUES ('As Suwayda','SYR','5550');
INSERT INTO province VALUES ('Goiás','BR','340086');
INSERT INTO province VALUES ('Santiago de Cuba','C','6227');
INSERT INTO province VALUES ('Mbeya','EAT','60350');
INSERT INTO province VALUES ('Liguria','I','5421');
INSERT INTO province VALUES ('Pays de la Loire','F','32082');
INSERT INTO province VALUES ('Glarus','CH','685');
INSERT INTO province VALUES ('Hebei','CN','202700');
INSERT INTO province VALUES ('Edirne','TR','6097');
INSERT INTO province VALUES ('Adygeya','R','7600');
INSERT INTO province VALUES ('Fukuoka','J','4977');
INSERT INTO province VALUES ('Risaralda','CO','4140');
INSERT INTO province VALUES ('Jizzax','UZ','20500');
INSERT INTO province VALUES ('Najran','SA','149511');
INSERT INTO province VALUES ('West Midlands','GB','12998');
INSERT INTO province VALUES ('Maharashtra','IND','307713');
INSERT INTO province VALUES ('South Korea','ROK','98480');
INSERT INTO province VALUES ('La Guajira','CO','20848');
INSERT INTO province VALUES ('Santarem','P','6747');
INSERT INTO province VALUES ('Cuvette','RCB','48250');
INSERT INTO province VALUES ('Sardegna','I','24089');
INSERT INTO province VALUES ('Tacna','PE','16075');
INSERT INTO province VALUES ('Keski-Suomi','SF','16703');
INSERT INTO province VALUES ('Uruguay','ROU','176220');
INSERT INTO province VALUES ('Viseu','P','5007');
INSERT INTO province VALUES ('Zinder','RN','155778');
INSERT INTO province VALUES ('Apurímac','PE','20895');
INSERT INTO province VALUES ('Maramureş','RO','6304');
INSERT INTO province VALUES ('Daman and Diu','IND','111');
INSERT INTO province VALUES ('Oman','OM','212460');
INSERT INTO province VALUES ('Diffa','RN','156906');
INSERT INTO province VALUES ('Salzburg','A','7156');
INSERT INTO province VALUES ('Ekiti','NGR','5887');
INSERT INTO province VALUES ('Guaviare','CO','42327');
INSERT INTO province VALUES ('Valle de Cauca','CO','22140');
INSERT INTO province VALUES ('Dolj','RO','7414');
INSERT INTO province VALUES ('Castelo Branco','P','6675');
INSERT INTO province VALUES ('Rio Grande do Sul','BR','268887');
INSERT INTO province VALUES ('Perlis','MAL','821');
INSERT INTO province VALUES ('Çorum','TR','12796');
INSERT INTO province VALUES ('Halland','S','5460');
INSERT INTO province VALUES ('French Guiana','FGU','83534');
INSERT INTO province VALUES ('Santa Cruz','BOL','370621');
INSERT INTO province VALUES ('Aguascalientes','MEX','5617');
INSERT INTO province VALUES ('Cape Verde','CV','4033');
INSERT INTO province VALUES ('Värmland','S','17591');
INSERT INTO province VALUES ('Kouilou','RCB','13650');
INSERT INTO province VALUES ('Kassalā','SUD','36710');
INSERT INTO province VALUES ('Tochigi','J','6408');
INSERT INTO province VALUES ('Federacija Bosne i Hercegovine','BIH','26110');
INSERT INTO province VALUES ('Genève','CH','282');
INSERT INTO province VALUES ('Central Highlands','VN','54641.1');
INSERT INTO province VALUES ('Konya','TR','40813');
INSERT INTO province VALUES ('FCT Islamabad','PK','906');
INSERT INTO province VALUES ('Prešovský','SK','8973');
INSERT INTO province VALUES ('Erbil','IRQ','15074');
INSERT INTO province VALUES ('Norfolk Island','NORF','34.6');
INSERT INTO province VALUES ('North-Western','Z','125826');
INSERT INTO province VALUES ('Zulia','YV','50230');
INSERT INTO province VALUES ('Zlínský','CZ','3963');
INSERT INTO province VALUES ('Cidade de Maputo','MOC','347');
INSERT INTO province VALUES ('Bonaire','NLB','294');
INSERT INTO province VALUES ('South West','GB','23837');
INSERT INTO province VALUES ('Distrito Federal','YV','433');
INSERT INTO province VALUES ('Uri','CH','1076');
INSERT INTO province VALUES ('Potosí','BOL','118218');
INSERT INTO province VALUES ('Balıkesir','TR','14472');
INSERT INTO province VALUES ('Minnesota','USA','206232');
INSERT INTO province VALUES ('Kano','NGR','21276');
INSERT INTO province VALUES ('Nógrád','H','2545');
INSERT INTO province VALUES ('Bruxelles','B','161');
INSERT INTO province VALUES ('Aceh','RI','57956');
INSERT INTO province VALUES ('Appenzell Ausserrhoden','CH','242');
INSERT INTO province VALUES ('Xizang','CN','1221600');
INSERT INTO province VALUES ('Antwerpen','B','2867');
INSERT INTO province VALUES ('Chittagong','BD','33908');
INSERT INTO province VALUES ('Plateaux','RCB','38400');
INSERT INTO province VALUES ('Tokat','TR','10072');
INSERT INTO province VALUES ('Sokoto','NGR','33776');
INSERT INTO province VALUES ('Tigray','ETH','85366');
INSERT INTO province VALUES ('Prahova','RO','4715');
INSERT INTO province VALUES ('Kansas','USA','211754');
INSERT INTO province VALUES ('North','PNG','229400');
INSERT INTO province VALUES ('Boyacá','CO','23189');
INSERT INTO province VALUES ('Rivers','NGR','10432');
INSERT INTO province VALUES ('Kolda','SN','13771');
INSERT INTO province VALUES ('Shanghai','CN','6200');
INSERT INTO province VALUES ('Siirt','TR','5473');
INSERT INTO province VALUES ('Jordan','JOR','89213');
INSERT INTO province VALUES ('Eastern','Z','69106');
INSERT INTO province VALUES ('Brăila','RO','4765');
INSERT INTO province VALUES ('Nara','J','3691');
INSERT INTO province VALUES ('Yamaguchi','J','6113');
INSERT INTO province VALUES ('Kyïv','UA','836');
INSERT INTO province VALUES ('Sud-Kivu','CGO','69130');
INSERT INTO province VALUES ('Etelä-Karjala','SF','5327');
INSERT INTO province VALUES ('Oruro','BOL','53588');
INSERT INTO province VALUES ('Guinea-Bissau','GUB','36120');
INSERT INTO province VALUES ('Arkansas','USA','134771');
INSERT INTO province VALUES ('Zacatecas','MEX','75539');
INSERT INTO province VALUES ('Łódzkie','PL','18218');
INSERT INTO province VALUES ('Gao','RMM','170572');
INSERT INTO province VALUES ('Colima','MEX','5625');
INSERT INTO province VALUES ('Lesotho','LS','30350');
INSERT INTO province VALUES ('Saskatchewan','CDN','588239');
INSERT INTO province VALUES ('Mizoram','IND','21081');
INSERT INTO province VALUES ('Pool','RCB','33955');
INSERT INTO province VALUES ('Egypt','ET','1001450');
INSERT INTO province VALUES ('Västernorrland','S','21683');
INSERT INTO province VALUES ('Pskovskaya','R','55300');
INSERT INTO province VALUES ('Bistriţa-Năsăud','RO','5355');
INSERT INTO province VALUES ('La Rioja','RA','89680');
INSERT INTO province VALUES ('Scotland','GB','78133');
INSERT INTO province VALUES ('British Virgin Islands','BVI','153');
INSERT INTO province VALUES ('Guerrero','MEX','63620');
INSERT INTO province VALUES ('Orenburgskaya','R','124000');
INSERT INTO province VALUES ('North West','GB','14105');
INSERT INTO province VALUES ('Kongo Central','CGO','53920');
INSERT INTO province VALUES ('Utah','USA','212818');
INSERT INTO province VALUES ('Niue','NIUE','260');
INSERT INTO province VALUES ('Neuchâtel','CH','803');
INSERT INTO province VALUES ('Argeş','RO','6826');
INSERT INTO province VALUES ('Trarza','RIM','67800');
INSERT INTO province VALUES ('Ségou','RMM','64821');
INSERT INTO province VALUES ('Buryatiya','R','351300');
INSERT INTO province VALUES ('Vatican City','V','0.44');
INSERT INTO province VALUES ('Trinidad and Tobago','TT','5130');
INSERT INTO province VALUES ('Kırıkkale','TR','4569');
INSERT INTO province VALUES ('Botoşani','RO','4985');
INSERT INTO province VALUES ('Barinas','YV','35200');
INSERT INTO province VALUES ('Hamedan','IR','19368');
INSERT INTO province VALUES ('Nusa Tenggara Timur','RI','48718');
INSERT INTO province VALUES ('São Paulo','BR','248209');
INSERT INTO province VALUES ('Toyama','J','4247');
INSERT INTO province VALUES ('Canarias','E','7447');
INSERT INTO province VALUES ('Nepal','NEP','140800');
