INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Mangistau','KZ','Маңғыстау');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('North Khorasan','IR','خراسان شمالي');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('East Azarbayejan','IR','آذربايجان شرقي');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Anhui','CN','安徽');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Hodh Chargui','RIM','الحوض الشرقي');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Jiangxi','CN','江西');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Rakhine','MYA','ရခိုင်ပြည်နယ်');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Miyazaki','J','宮崎県');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Kohgiluyeh and Boyer-Ahmad','IR','كهگيلويه وبويراحمد');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Primorskiy','R','Приморский');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('al-Najaf','IRQ','النجف');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Tiris Zemmour','RIM','تيرس زمور');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Assaba','RIM','لعصابة');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Amurskaya','R','Амурская');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Rajshahi','BD','রাজশাহী');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Minsk','BY','Минской');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Zabaykalskiy','R','Забайкальский');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Toyama','J','富山県');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Khakasiya','R','Хакасия');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Aktobe','KZ','Ақтөбе');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Aghion Oros','GR','Άγιο Όρος (Αυτοδιοίκητο)');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Aseer','SA','عسير');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('HaMerkaz','IL','המרכז');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Astrakhanskaya','R','Астраханская');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Fujian','CN','福建');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Al-Jazīrah','SUD','الجزيرة');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Khersonska','UA','Херсонська');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Hainan','CN','海南');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Krym','UA','Крим');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Rangpur','BD','রংপুর');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Saratovskaya','R','Саратовская');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Al Ladhiqiyah','SYR','اللاذقية');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Kentrikis Makedonias','GR','Κεντρικής Μακεδονίας');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Salah al-Deen','IRQ','صلاح الدين');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Shanghai','CN','上海');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Tokyo','J','東京都');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Chittagong','BD','চট্টগ্রাম');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Mary','TM','Mary');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Wasit','IRQ','واسط');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Beijing','CN','北京');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Tabouk','SA','تبوك');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('al-Qadisiya','IRQ','القادسية');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Volgogradskaya','R','Волгоградская');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Tulskaya','R','Тульская');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Iwate','J','岩手県');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Sakhalin','R','Сахалинская');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Sistan and Baluchestan','IR','سيستان وبلوچستان');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Atyrau','KZ','Атырау');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Al-Baha','SA','ﺔﺣﺎﺒﻟﺍ');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Hokkaido','J','北海道');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Kostanai','KZ','Қостанай');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Fars','IR','فارس');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Kurdestan','IR','كردستان');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Wasaṭ Dārfūr','SUD','وسط دارفور‎');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Tomskaya','R','Томская');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Henan','CN','河南');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Arkhangelskaya','R','Архангельская');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Al Qunaytirah','SYR','القنيطرة');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Sverdlovskaya','R','Свердловская');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Hamedan','IR','همدان');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Ishikawa','J','石川県');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Saitama','J','埼玉県');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Fukushima','J','福島県');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Heilongjiang','CN','黑龙江');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Dhaka','BD','ঢাকা');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Tyva','R','Тыва');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Xinjiang','CN','新疆维吾尔');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Kirovskaya','R','Кировская');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Diala','IRQ','ديالى');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Tel Aviv','IL','מחוז תל אביב');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Ternopilska','UA','Тернопільська');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Gilan','IR','گيلان');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Volynska','UA','Волинська');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Vologodskaya','R','Вологодская');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Idlib','SYR','ادلب');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Sannār','SUD','سنار');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Shamāl Dārfūr','SUD','شمال دارفور');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Vinnytska','UA','Вінницька');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Shandong','CN','山东');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Bashkortostan','R','Башкортостан');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Tianjin','CN','天津');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Odeska','UA','Одеська');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Mazandaran','IR','مازندران');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Ipeiroy','GR','Ηπείρου');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Thessalias','GR','Θεσσαλίας');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Qom','IR','قم');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Magadanskaya','R','Магаданская');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Novgorodskaya','R','Новгородская');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('As Suwayda','SYR','السويداء');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Jazan','SA','جازان');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Hormozgan','IR','هرمزگان');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Hebei','CN','河北');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Nineveh','IRQ','نينوى');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Nagano','J','長野県');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Kermanshah','IR','كرمانشاه');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Khabarovskiy','R','Хабаровский');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Zaporizka','UA','Запорізька');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Yamalo Nenets ao','R','Ямало-Ненецкий автономный округ');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Wakayama','J','和歌山県');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Al-Qaḍārif','SUD','القضارف');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Chukotka','R','Чукотский');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Almaty City','KZ','Алматы');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Osaka','J','大阪府');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Kirkuk','IRQ','كركوك');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Kostromskaya','R','Костромская');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Liaoning','CN','辽宁');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Okinawa','J','沖縄県');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Hiroshima','J','広島県');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Yunnan','CN','云南');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Novosibirskaya','R','Новосибирская');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Yamaguchi','J','山口県');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Kerman','IR','كرمان');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Gumma','J','群馬県');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Regions of Republican Subordination','TJ','Шањру ноњияњои тобеи љумњурї');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Duhouk','IRQ','دهوك');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Al-Jouf','SA','الجوف');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Bago','MYA','ပဲခူးတိုင်းဒေသကြီး');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Hail','SA','حائل');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Attikis','GR','Αττικής');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Zanjan','IR','زنجان');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Adrar','RIM','أدرار');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Shimane','J','島根県');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Mandalay','MYA','မန္တလေးတိုင်းဒေသကြီး');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Ibaraki','J','茨城県');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Ar Raqqah','SYR','الرقة');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Khulna','BD','খুলনা');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Penzenskaya','R','Пензенская');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Donetska','UA','Донецька');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Stereas Elladas','GR','Στερεάς Ελλάδας');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Khmelnytska','UA','Хмельницька');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Brest','BY','Брестской');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Al-Hudud ash Shamaliyah','SA','الحدود الشمالية');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Zhejiang','CN','浙江');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Kharkivska','UA','Харківська');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Minsk City','BY','Мінск');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Boreioy Aigaioy','GR','Βορείου Αιγαίου');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Ivano-Frankivska','UA','Івано-Франківська');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Qazvin','IR','قزوين');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Gharb al-Dārfūr','SUD','غرب دارفور');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('West Azarbayejan','IR','آذربايجان غربي');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Makkah Al-Mokarramah','SA','مكة المكرمة');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Kagoshima','J','鹿児島県');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Hunan','CN','湖南');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Kochi','J','高知県');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Rif Dimashq','SYR','ريف دمشق');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Khatlon','TJ','Хатлон');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Tanintharyi','MYA','တနင်္သာရီတိုင်းဒေသကြီး');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Yazd','IR','يزد');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Alborz','IR','البرز');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Kagawa','J','香川県');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Pavlodar','KZ','Павлодар');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Dnipropetrovska','UA','Дніпропетровська');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Tyumenskaya','R','Тюменская');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Aichi','J','愛知県');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('North Ossetia-Alania','R','Северная Осетия-Алания');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Kurganskaya','R','Курганская');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Permskij','R','Пермский');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Tochigi','J','栃木県');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('South-Kazakhstan','KZ','Оңтүстік Қазақстан');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Sughd','TJ','Суѓд');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Babylon','IRQ','بابل');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Maysan','IRQ','ميسان');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Semnan','IR','سمنان');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('South Khorasan','IR','خراسان جنوبي');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Shaanxi','CN','陕西');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Altayskiy','R','Алтайский');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Stavropolskiy','R','Ставропольский');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Mariy-El','R','Марий Эл');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Nay Pyi Taw','MYA','နေပြည်တော် ပြည်တောင်စုနယ်မြေ');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Sichuan','CN','四川');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Dytikis Makedonias','GR','Δυτικής Μακεδονίας');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Pskovskaya','R','Псковская');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Hamah','SYR','حماة');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Kalmykiya','R','Калмыкия');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Yaroslavskaya','R','Ярославская');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Saga','J','佐賀県');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Dushanbe','TJ','Душанбе');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Chaharmahal and Bakhtiyari','IR','چهارمحال وبختيارئ');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Tottori','J','鳥取県');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Al-Baḥr al-Aḥmar','SUD','البحر الأحمر');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('HaZafon','IL','מחוז הצפון');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Kyïvska','UA','Київська');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Chuvashia','R','Чувашская');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Cherkaska','UA','Черкаська');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Kyzylorda','KZ','Қызылорда');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Grodno','BY','Гродненской');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Yamanashi','J','山梨県');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('al-Muthanna','IRQ','المثنى');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Ionion Nison','GR','Ιονίων Νήσων');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Mie','J','三重県');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Akhal','TM','Ahal');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Akita','J','秋田県');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Hyogo','J','兵庫県');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Kurskaya','R','Курская');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Balkan','TM','Balkan');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Chernihivska','UA','Чернігівська');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Mogilev','BY','Могилевской');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Yamagata','J','山形県');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Kaliningradskaya','R','Калининградская');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Chechenskaya','R','Чеченская');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Shanxi','CN','山西');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Nouakchott','RIM','نواكشوط');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Sylhet','BD','সিলেট');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Al-Qaseem','SA','القصيم');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Fukui','J','福井県');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Oita','J','大分県');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Dytikis Elladas','GR','Δυτικής Ελλάδας');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Karachayevo-Cherkesskaya','R','Карачаево-Черкесская');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Inchiri','RIM','إينشيري');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Najran','SA','نجران');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Zhambyl','KZ','Жамбыл');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Hefa','IL','מחוז חיפה');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('HaDarom','IL','מחוז הדרום');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Markazi','IR','مركزي');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Kaluzhskaya','R','Калужская');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Jiangsu','CN','江苏');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Baikonur','KZ','Байкоңыр');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Chin','MYA','ချင်းပြည်နယ်');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Khanty Mansi ao','R','Ханты-Мансийский автономный округ — Югра');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Kyïv','UA','Київ');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Ryazanskaya','R','Рязанская');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Ayeyarwady','MYA','ဧရာဝတီတိုင်းဒေသကြီး');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Guangdong','CN','广东');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Tambovskaya','R','Тамбовская');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Qinghai','CN','青海');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Shan','MYA','ရှမ်းပြည်နယ်');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('North-Kazakhstan','KZ','Солтүстік Қазақстан');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Yangon','MYA','ရန်ကုန်တိုင်းဒေသကြီး');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Al Hasakah','SYR','الحسكة');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Ehime','J','愛媛県');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Mordoviya','R','Мордовия');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Irkutskaya','R','Иркутская');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Chernivetska','UA','Чернівецька');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Shiga','J','滋賀県');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Kassalā','SUD','كسلا');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Zakarpatska','UA','Закарпатська');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Kemerovskaya','R','Кемеровская');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Janūb Kurdufān','SUD','جنوب كردفان');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Lvivska','UA','Львівська');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Erbil','IRQ','أربيل');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Ulyanovskaya','R','Ульяновская');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Akmola','KZ','Ақмола');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Kabardino-Balkarskaya','R','Кабардино-Балкарская');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Lorestan','IR','لرستان');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Xizang','CN','西藏');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Golestan','IR','گلستان');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Tokushima','J','徳島県');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Ningxia','CN','宁夏');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Sharq Dārfūr','SUD','شرق دارفور‏');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Kayah','MYA','ကယားပြည်နယ်');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Voronezhskaya','R','Воронежская');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Thi Qar','IRQ','ذي قار');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Kritis','GR','Κρήτης');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Tverskaya','R','Тверская');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Al-Kharṭūm','SUD','الخرطوم');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Jewish Autonomous Oblast','R','Еврейская');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Kayin','MYA','ကရင်ပြည်နယ်');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Baghdad','IRQ','بغداد');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Gomel','BY','Гомельской');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Jilin','CN','吉林');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Rostovskaya','R','Ростовская');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Vladimirskaya','R','Владимирская');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Tatarstan','R','Татарстан');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Moskovskaya','R','Московская');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Gifu','J','岐阜県');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Murmanskaya','R','Мурманская');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Nara','J','奈良県');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Luhanska','UA','Луганська');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Mon','MYA','မွန်ပြည်နယ်');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Basrah','IRQ','البصرة');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Peloponnisos','GR','Πελοποννήσου');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Buryatiya','R','Бурятия');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Kerbela','IRQ','كربلاء');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Dayr az Zawr','SYR','دير الزور');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Niigata','J','新潟県');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Orenburgskaya','R','Оренбургская');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Guangxi','CN','广西');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Nizhnii Novgorodskaya','R','Нижегородская');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Gorgol','RIM','كوركول');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Tehran','IR','تهران');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Tartus','SYR','طرطوس');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Chongqing','CN','重庆');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Okayama','J','岡山県');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Tagant','RIM','تكانت');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Guidimagha','RIM','غيديماغا');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Orlovskaya','R','Орловская');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Notioy Aigaioy','GR','Νότιου Αιγαίου');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Chelyabinskaya','R','Челябинская');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('An-Nīl al-Abyaḍ','SUD','النيل الأبيض');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Bryanskaya','R','Брянская');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Kamchatka','R','Камчатский');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Poltavska','UA','Полтавська');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Lebap','TM','Lebap');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Khuzestan','IR','خوزستان');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Magwe','MYA','မကွေးတိုင်းဒေသကြီး');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Moscow','R','Москва');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Sankt-Peterburg','R','Санкт-Петербург');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Lipetskaya','R','Липецкая');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Almaty','KZ','Алматы');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Dashhowuz','TM','Daşoguz');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Aomori','J','青森県');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Sakha','R','Саха (Якутия)');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Yerushalayim','IL','מחוז ירושלים');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Bushehr','IR','بوشهر');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Esfahan','IR','اصفهان');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Kachin','MYA','ကချင်ပြည်နယ်');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Krasnoyarsk','R','Красноярский');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Komi','R','Коми');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Al-Madinah Al-Monawarah','SA','المدينة المنورة');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Ivanovskaya','R','Ивановская');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Adygeya','R','Адыгея');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Gorno-Badakhshan','TJ','Вилояти Мухтори Кўњистони Бадахшон');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Chiba','J','千葉県');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Mykolaïvska','UA','Миколаївська');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Fukuoka','J','福岡県');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Samarskaya','R','Самарская');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Nei Mongol','CN','内蒙古');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Janūb Dārfūr','SUD','جنوب دارفور');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Nahr an-Nīl','SUD','نهر النيل');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('West Kazakhstan','KZ','Батыс Қазақстан');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Gansu','CN','甘肃');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Gharb Kurdufān','SUD','غرب كردفان');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Anatolikis Makedonias kai Thrakis','GR','Ανατολικής Μακεδονίας και Θράκης');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Hims','SYR','حمص');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Ilam','IR','ايلام');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Belgorodskaya','R','Белгородская');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Ardebil','IR','اردبيل');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('al-Anbar','IRQ','الانبار');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Miyagi','J','宮城県');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Rivnenska','UA','Рівненська');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Daraa','SYR','درعا');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Sumska','UA','Сумська');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Brakna','RIM','لبراكنة');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Shamāl Kurdufān','SUD','شمال كردفان');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Hubei','CN','湖北');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Khorasan-e-Razavi','IR','خراسان رضوي');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Mymensingh','BD','ময়মনসিংহ বিভাগ');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Omskaya','R','Омская');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Ingushskaya','R','Ингушетия');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Trarza','RIM','الترارزه');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Leningradskaya','R','Ленинградская');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Sevastopol','UA','Севастополь');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Dakhlet Nouadhibou','RIM','داخلة نواذيبو');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Guizhou','CN','贵州');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Vitebsk','BY','Витебской');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Ashgabat','TM','Aşgabat');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Dimashq','SYR','مدينة دمشق');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Altay','R','Алтай');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Karaganda','KZ','Қарағанды');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Krasnodarskiy','R','Краснодарский край');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Kumamoto','J','熊本県');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Dagestan','R','Дагестан');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Smolenskaya','R','Смоленская');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Shizuoka','J','静岡県');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Hodh El Gharbi','RIM','الحوض الغربي');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('East-Kazakhstan','KZ','Шығыс Қазақстан');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('An-Nīl al-Azraq','SUD','النيل الأزرق');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Barisal','BD','বরিশাল');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Halab','SYR','حلب');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Nagasaki','J','長崎県');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Zhytomyrska','UA','Житомирська');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Sagaing','MYA','စစ်ကိုင်းတိုင်းဒေသကြီး');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Ash-Shamālīyah','SUD','الشمالية');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Kanagawa','J','神奈川県');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Astana','KZ','Астана');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Karelia','R','Карелия');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Kirovohradska','UA','Кіровоградська');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Udmurtskaya','R','Удмуртская');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Kyoto','J','京都府');
INSERT INTO province_local_name (province_name,country_code,province_local_name) VALUES ('Ash Sharqiyah','SA','الشرقية');
